// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type OrchestrionPath struct {
	ID int `json:"ID,omitempty"`
	Url string `json:"Url,omitempty"`
	File string `json:"File,omitempty"`
	File_en string `json:"File_en,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
}
