// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type OnlineStatus struct {
	Name_en string `json:"Name_en,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	Icon string `json:"Icon,omitempty"`
	Name string `json:"Name,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Priority int `json:"Priority,omitempty"`
	ID int `json:"ID,omitempty"`
	IconID int `json:"IconID,omitempty"`
}
