// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type Orchestrion struct {
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	Description_ja string `json:"Description_ja,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	OrchestrionUiparam struct {
		GameContentLinks interface{} `json:"GameContentLinks,omitempty"`
		ID int `json:"ID,omitempty"`
		OrchestrionCategory struct {
			Name_de string `json:"Name_de,omitempty"`
			Name_en string `json:"Name_en,omitempty"`
			Name_fr string `json:"Name_fr,omitempty"`
			Name_ja string `json:"Name_ja,omitempty"`
			ID int `json:"ID,omitempty"`
			Name string `json:"Name,omitempty"`
		}
		OrchestrionCategoryTarget string `json:"OrchestrionCategoryTarget,omitempty"`
		OrchestrionCategoryTargetID int `json:"OrchestrionCategoryTargetID,omitempty"`
		Order int `json:"Order,omitempty"`
		Url string `json:"Url,omitempty"`
	}
	Name string `json:"Name,omitempty"`
	ID int `json:"ID,omitempty"`
	Url string `json:"Url,omitempty"`
	Description_de string `json:"Description_de,omitempty"`
	Description_en string `json:"Description_en,omitempty"`
	Description_fr string `json:"Description_fr,omitempty"`
	GamePatch struct {
		Name string `json:"Name,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_kr string `json:"Name_kr,omitempty"`
		ExVersion int `json:"ExVersion,omitempty"`
		IsExpansion bool `json:"IsExpansion,omitempty"`
		Name_cn string `json:"Name_cn,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		ReleaseDate int `json:"ReleaseDate,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Version int `json:"Version,omitempty"`
		Banner interface{} `json:"Banner,omitempty"`
		ID int `json:"ID,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		Url string `json:"Url,omitempty"`
	}
	Description string `json:"Description,omitempty"`
}
