// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type RetainerTaskParameter struct {
	Url string `json:"Url,omitempty"`
	GameContentLinks struct {
		RetainerTask struct {
			RetainerTaskParameter []interface{} `json:"RetainerTaskParameter,omitempty"`
		}
	}
	GatheringDoL1 int `json:"GatheringDoL1,omitempty"`
	GatheringFSH1 int `json:"GatheringFSH1,omitempty"`
	ItemLevelDoW0 int `json:"ItemLevelDoW0,omitempty"`
	ItemLevelDoW1 int `json:"ItemLevelDoW1,omitempty"`
	GatheringDoL0 int `json:"GatheringDoL0,omitempty"`
	GatheringFSH0 int `json:"GatheringFSH0,omitempty"`
	ID int `json:"ID,omitempty"`
}
