// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ChocoboRaceRank struct {
	IconID int `json:"IconID,omitempty"`
	NameTarget string `json:"NameTarget,omitempty"`
	NameTargetID int `json:"NameTargetID,omitempty"`
	Url string `json:"Url,omitempty"`
	Fee int `json:"Fee,omitempty"`
	Icon string `json:"Icon,omitempty"`
	Name struct {
		ID int `json:"ID,omitempty"`
		Text string `json:"Text,omitempty"`
		Text_de string `json:"Text_de,omitempty"`
		Text_en string `json:"Text_en,omitempty"`
		Text_fr string `json:"Text_fr,omitempty"`
		Text_ja string `json:"Text_ja,omitempty"`
	}
	RatingMax int `json:"RatingMax,omitempty"`
	RatingMin int `json:"RatingMin,omitempty"`
	GameContentLinks struct {
		ChocoboRace struct {
			ChocoboRaceRank []interface{} `json:"ChocoboRaceRank,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
}
