// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type QuickChat struct {
	TextOutput_fr string `json:"TextOutput_fr,omitempty"`
	AddonTarget string `json:"AddonTarget,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	NameAction_fr string `json:"NameAction_fr,omitempty"`
	QuickChatTransientTarget string `json:"QuickChatTransientTarget,omitempty"`
	QuickChatTransientTargetID int `json:"QuickChatTransientTargetID,omitempty"`
	TextOutput_de string `json:"TextOutput_de,omitempty"`
	IconID int `json:"IconID,omitempty"`
	NameAction_en string `json:"NameAction_en,omitempty"`
	Url string `json:"Url,omitempty"`
	Addon struct {
		ID int `json:"ID,omitempty"`
		Text string `json:"Text,omitempty"`
		Text_de string `json:"Text_de,omitempty"`
		Text_en string `json:"Text_en,omitempty"`
		Text_fr string `json:"Text_fr,omitempty"`
		Text_ja string `json:"Text_ja,omitempty"`
	}
	AddonTargetID int `json:"AddonTargetID,omitempty"`
	NameAction_de string `json:"NameAction_de,omitempty"`
	NameAction_ja string `json:"NameAction_ja,omitempty"`
	TextOutput_en string `json:"TextOutput_en,omitempty"`
	TextOutput_ja string `json:"TextOutput_ja,omitempty"`
	ID int `json:"ID,omitempty"`
	Icon string `json:"Icon,omitempty"`
	NameAction string `json:"NameAction,omitempty"`
	QuickChatTransient struct {
		TextOutput_de string `json:"TextOutput_de,omitempty"`
		TextOutput_en string `json:"TextOutput_en,omitempty"`
		TextOutput_fr string `json:"TextOutput_fr,omitempty"`
		TextOutput_ja string `json:"TextOutput_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		TextOutput string `json:"TextOutput,omitempty"`
	}
	TextOutput string `json:"TextOutput,omitempty"`
}
