// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type WeeklyBingoOrderData struct {
	Data int `json:"Data,omitempty"`
	Icon string `json:"Icon,omitempty"`
	Text struct {
		Description_fr string `json:"Description_fr,omitempty"`
		Description_ja string `json:"Description_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		Description string `json:"Description,omitempty"`
		Description_de string `json:"Description_de,omitempty"`
		Description_en string `json:"Description_en,omitempty"`
	}
	Url string `json:"Url,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	IconID int `json:"IconID,omitempty"`
	TextTarget string `json:"TextTarget,omitempty"`
	TextTargetID int `json:"TextTargetID,omitempty"`
}
