// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type StatusLoopVFX struct {
	GameContentLinks struct {
		Status struct {
			VFX []interface{} `json:"VFX,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	Url string `json:"Url,omitempty"`
	VFX struct {
		ID int `json:"ID,omitempty"`
		Location string `json:"Location,omitempty"`
		Location_en string `json:"Location_en,omitempty"`
	}
	VFXTarget string `json:"VFXTarget,omitempty"`
	VFXTargetID int `json:"VFXTargetID,omitempty"`
}
