// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type DefaultTalk struct {
	Text2_en int `json:"Text2_en,omitempty"`
	Text2_fr int `json:"Text2_fr,omitempty"`
	Url string `json:"Url,omitempty"`
	ActionTimelinePose1 int `json:"ActionTimelinePose1,omitempty"`
	GameContentLinks struct {
		SpecialShop struct {
			CompleteText []interface{} `json:"CompleteText,omitempty"`
		}
	}
	Text0_fr string `json:"Text0_fr,omitempty"`
	Text1_de int `json:"Text1_de,omitempty"`
	Text1_en int `json:"Text1_en,omitempty"`
	ActionTimelinePose2 int `json:"ActionTimelinePose2,omitempty"`
	Text0 string `json:"Text0,omitempty"`
	Text0_de string `json:"Text0_de,omitempty"`
	Text2 int `json:"Text2,omitempty"`
	Text2_ja int `json:"Text2_ja,omitempty"`
	Text1_ja int `json:"Text1_ja,omitempty"`
	Text2_de int `json:"Text2_de,omitempty"`
	ActionTimelinePose0 struct {
		Key string `json:"Key,omitempty"`
		Key_en string `json:"Key_en,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	ActionTimelinePose0Target string `json:"ActionTimelinePose0Target,omitempty"`
	ID int `json:"ID,omitempty"`
	Text0_en string `json:"Text0_en,omitempty"`
	Text1_fr int `json:"Text1_fr,omitempty"`
	ActionTimelinePose0TargetID int `json:"ActionTimelinePose0TargetID,omitempty"`
	Text0_ja string `json:"Text0_ja,omitempty"`
	Text1 int `json:"Text1,omitempty"`
}
