// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type CompanionTransient struct {
	MinionSkillTypeTargetID int `json:"MinionSkillTypeTargetID,omitempty"`
	SpecialActionDescription_fr string `json:"SpecialActionDescription_fr,omitempty"`
	Defense int `json:"Defense,omitempty"`
	DescriptionEnhanced_de string `json:"DescriptionEnhanced_de,omitempty"`
	Description_fr string `json:"Description_fr,omitempty"`
	Tooltip_ja string `json:"Tooltip_ja,omitempty"`
	Url string `json:"Url,omitempty"`
	DescriptionEnhanced string `json:"DescriptionEnhanced,omitempty"`
	DescriptionEnhanced_ja string `json:"DescriptionEnhanced_ja,omitempty"`
	SpecialActionDescription_en string `json:"SpecialActionDescription_en,omitempty"`
	StrengthGate int `json:"StrengthGate,omitempty"`
	Tooltip_de string `json:"Tooltip_de,omitempty"`
	Attack int `json:"Attack,omitempty"`
	Description_ja string `json:"Description_ja,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	SpecialActionName_fr string `json:"SpecialActionName_fr,omitempty"`
	Description_de string `json:"Description_de,omitempty"`
	SpecialActionDescription string `json:"SpecialActionDescription,omitempty"`
	StrengthShield int `json:"StrengthShield,omitempty"`
	Tooltip_en string `json:"Tooltip_en,omitempty"`
	Tooltip_fr string `json:"Tooltip_fr,omitempty"`
	SpecialActionName_ja string `json:"SpecialActionName_ja,omitempty"`
	StrengthEye int `json:"StrengthEye,omitempty"`
	Tooltip string `json:"Tooltip,omitempty"`
	Description string `json:"Description,omitempty"`
	DescriptionEnhanced_fr string `json:"DescriptionEnhanced_fr,omitempty"`
	ID int `json:"ID,omitempty"`
	SpecialActionName_de string `json:"SpecialActionName_de,omitempty"`
	SpecialActionName_en string `json:"SpecialActionName_en,omitempty"`
	DescriptionEnhanced_en string `json:"DescriptionEnhanced_en,omitempty"`
	HasAreaAttack int `json:"HasAreaAttack,omitempty"`
	MinionSkillTypeTarget string `json:"MinionSkillTypeTarget,omitempty"`
	SpecialActionDescription_de string `json:"SpecialActionDescription_de,omitempty"`
	Speed int `json:"Speed,omitempty"`
	Description_en string `json:"Description_en,omitempty"`
	MinionSkillType struct {
		Name_ja string `json:"Name_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
	}
	SpecialActionDescription_ja string `json:"SpecialActionDescription_ja,omitempty"`
	SpecialActionName string `json:"SpecialActionName,omitempty"`
	StrengthArcana int `json:"StrengthArcana,omitempty"`
}
