// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ActivityFeedButtons struct {
	Url string `json:"Url,omitempty"`
	BannerURL_en string `json:"BannerURL_en,omitempty"`
	Description string `json:"Description,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	Language string `json:"Language,omitempty"`
	PictureURL string `json:"PictureURL,omitempty"`
	BannerURL string `json:"BannerURL,omitempty"`
	Description_en string `json:"Description_en,omitempty"`
	Language_en string `json:"Language_en,omitempty"`
	PictureURL_en string `json:"PictureURL_en,omitempty"`
}
