// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type CompleteJournal struct {
	Cutscene12 struct {
		ID int `json:"ID,omitempty"`
		Path string `json:"Path,omitempty"`
		Path_en string `json:"Path_en,omitempty"`
	}
	Cutscene15 struct {
		Path_en string `json:"Path_en,omitempty"`
		ID int `json:"ID,omitempty"`
		Path string `json:"Path,omitempty"`
	}
	Cutscene16TargetID int `json:"Cutscene16TargetID,omitempty"`
	Cutscene9 struct {
		ID int `json:"ID,omitempty"`
		Path string `json:"Path,omitempty"`
		Path_en string `json:"Path_en,omitempty"`
	}
	Name_ja string `json:"Name_ja,omitempty"`
	Cutscene23 int `json:"Cutscene23,omitempty"`
	Cutscene5 struct {
		ID int `json:"ID,omitempty"`
		Path string `json:"Path,omitempty"`
		Path_en string `json:"Path_en,omitempty"`
	}
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	Cutscene7 struct {
		ID int `json:"ID,omitempty"`
		Path string `json:"Path,omitempty"`
		Path_en string `json:"Path_en,omitempty"`
	}
	Name_en string `json:"Name_en,omitempty"`
	Cutscene19Target string `json:"Cutscene19Target,omitempty"`
	Cutscene21Target string `json:"Cutscene21Target,omitempty"`
	Cutscene2TargetID int `json:"Cutscene2TargetID,omitempty"`
	Cutscene4Target string `json:"Cutscene4Target,omitempty"`
	Cutscene22 int `json:"Cutscene22,omitempty"`
	Cutscene5Target string `json:"Cutscene5Target,omitempty"`
	Cutscene8TargetID int `json:"Cutscene8TargetID,omitempty"`
	Cutscene9Target string `json:"Cutscene9Target,omitempty"`
	Cutscene10 struct {
		Path_en string `json:"Path_en,omitempty"`
		ID int `json:"ID,omitempty"`
		Path string `json:"Path,omitempty"`
	}
	Cutscene10TargetID int `json:"Cutscene10TargetID,omitempty"`
	Cutscene17TargetID int `json:"Cutscene17TargetID,omitempty"`
	Cutscene1TargetID int `json:"Cutscene1TargetID,omitempty"`
	IconID int `json:"IconID,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Cutscene13 struct {
		ID int `json:"ID,omitempty"`
		Path string `json:"Path,omitempty"`
		Path_en string `json:"Path_en,omitempty"`
	}
	Cutscene4 struct {
		Path_en string `json:"Path_en,omitempty"`
		ID int `json:"ID,omitempty"`
		Path string `json:"Path,omitempty"`
	}
	Cutscene6TargetID int `json:"Cutscene6TargetID,omitempty"`
	Cutscene13TargetID int `json:"Cutscene13TargetID,omitempty"`
	Cutscene2 struct {
		ID int `json:"ID,omitempty"`
		Path string `json:"Path,omitempty"`
		Path_en string `json:"Path_en,omitempty"`
	}
	Cutscene21 struct {
		ID int `json:"ID,omitempty"`
		Path string `json:"Path,omitempty"`
		Path_en string `json:"Path_en,omitempty"`
	}
	Cutscene0Target string `json:"Cutscene0Target,omitempty"`
	Cutscene1 struct {
		ID int `json:"ID,omitempty"`
		Path string `json:"Path,omitempty"`
		Path_en string `json:"Path_en,omitempty"`
	}
	Cutscene2Target string `json:"Cutscene2Target,omitempty"`
	Cutscene3Target string `json:"Cutscene3Target,omitempty"`
	Cutscene17Target string `json:"Cutscene17Target,omitempty"`
	Cutscene19 struct {
		ID int `json:"ID,omitempty"`
		Path string `json:"Path,omitempty"`
		Path_en string `json:"Path_en,omitempty"`
	}
	Cutscene20Target string `json:"Cutscene20Target,omitempty"`
	Cutscene8Target string `json:"Cutscene8Target,omitempty"`
	Cutscene3 struct {
		ID int `json:"ID,omitempty"`
		Path string `json:"Path,omitempty"`
		Path_en string `json:"Path_en,omitempty"`
	}
	Cutscene7TargetID int `json:"Cutscene7TargetID,omitempty"`
	Cutscene11TargetID int `json:"Cutscene11TargetID,omitempty"`
	Cutscene17 struct {
		Path string `json:"Path,omitempty"`
		Path_en string `json:"Path_en,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	Cutscene19TargetID int `json:"Cutscene19TargetID,omitempty"`
	Cutscene1Target string `json:"Cutscene1Target,omitempty"`
	RequiredLevel int `json:"RequiredLevel,omitempty"`
	Url string `json:"Url,omitempty"`
	Cutscene0TargetID int `json:"Cutscene0TargetID,omitempty"`
	Cutscene12TargetID int `json:"Cutscene12TargetID,omitempty"`
	Cutscene13Target string `json:"Cutscene13Target,omitempty"`
	Cutscene18TargetID int `json:"Cutscene18TargetID,omitempty"`
	Cutscene18Target string `json:"Cutscene18Target,omitempty"`
	Cutscene9TargetID int `json:"Cutscene9TargetID,omitempty"`
	Cutscene11Target string `json:"Cutscene11Target,omitempty"`
	Cutscene14 struct {
		ID int `json:"ID,omitempty"`
		Path string `json:"Path,omitempty"`
		Path_en string `json:"Path_en,omitempty"`
	}
	Cutscene15Target string `json:"Cutscene15Target,omitempty"`
	Cutscene16 struct {
		ID int `json:"ID,omitempty"`
		Path string `json:"Path,omitempty"`
		Path_en string `json:"Path_en,omitempty"`
	}
	Name string `json:"Name,omitempty"`
	Cutscene14Target string `json:"Cutscene14Target,omitempty"`
	Cutscene18 struct {
		ID int `json:"ID,omitempty"`
		Path string `json:"Path,omitempty"`
		Path_en string `json:"Path_en,omitempty"`
	}
	Cutscene6 struct {
		ID int `json:"ID,omitempty"`
		Path string `json:"Path,omitempty"`
		Path_en string `json:"Path_en,omitempty"`
	}
	Cutscene6Target string `json:"Cutscene6Target,omitempty"`
	Cutscene8 struct {
		ID int `json:"ID,omitempty"`
		Path string `json:"Path,omitempty"`
		Path_en string `json:"Path_en,omitempty"`
	}
	Name_de string `json:"Name_de,omitempty"`
	Cutscene12Target string `json:"Cutscene12Target,omitempty"`
	Cutscene14TargetID int `json:"Cutscene14TargetID,omitempty"`
	Cutscene16Target string `json:"Cutscene16Target,omitempty"`
	Cutscene20 struct {
		ID int `json:"ID,omitempty"`
		Path string `json:"Path,omitempty"`
		Path_en string `json:"Path_en,omitempty"`
	}
	Cutscene10Target string `json:"Cutscene10Target,omitempty"`
	Cutscene4TargetID int `json:"Cutscene4TargetID,omitempty"`
	Cutscene5TargetID int `json:"Cutscene5TargetID,omitempty"`
	Icon string `json:"Icon,omitempty"`
	Cutscene21TargetID int `json:"Cutscene21TargetID,omitempty"`
	Cutscene3TargetID int `json:"Cutscene3TargetID,omitempty"`
	Cutscene7Target string `json:"Cutscene7Target,omitempty"`
	Cutscene0 struct {
		ID int `json:"ID,omitempty"`
		Path string `json:"Path,omitempty"`
		Path_en string `json:"Path_en,omitempty"`
	}
	Cutscene11 struct {
		ID int `json:"ID,omitempty"`
		Path string `json:"Path,omitempty"`
		Path_en string `json:"Path_en,omitempty"`
	}
	Cutscene15TargetID int `json:"Cutscene15TargetID,omitempty"`
	Cutscene20TargetID int `json:"Cutscene20TargetID,omitempty"`
}
