// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type GilShop struct {
	Url string `json:"Url,omitempty"`
	ID int `json:"ID,omitempty"`
	IconID int `json:"IconID,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	QuestRequired0 int `json:"QuestRequired0,omitempty"`
	FailTalk int `json:"FailTalk,omitempty"`
	Name string `json:"Name,omitempty"`
	QuestRequired3 int `json:"QuestRequired3,omitempty"`
	AcceptTalk int `json:"AcceptTalk,omitempty"`
	Icon string `json:"Icon,omitempty"`
	Items []interface{} `json:"Items,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	QuestRequired1 int `json:"QuestRequired1,omitempty"`
	QuestRequired2 int `json:"QuestRequired2,omitempty"`
	GameContentLinks struct {
		PreHandler struct {
			GilShop []interface{} `json:"GilShop,omitempty"`
		}
	}
}
