// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type EquipRaceCategory struct {
	Url string `json:"Url,omitempty"`
	Lalafell int `json:"Lalafell,omitempty"`
	Male int `json:"Male,omitempty"`
	Miqo'te int `json:"Miqo'te,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	Hyur int `json:"Hyur,omitempty"`
	ID int `json:"ID,omitempty"`
	Roegadyn int `json:"Roegadyn,omitempty"`
	AuRa int `json:"AuRa,omitempty"`
	Elezen int `json:"Elezen,omitempty"`
	Female int `json:"Female,omitempty"`
}
