// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type AddonHud struct {
	ID int `json:"ID,omitempty"`
	Long_de string `json:"Long_de,omitempty"`
	Long_ja string `json:"Long_ja,omitempty"`
	Short string `json:"Short,omitempty"`
	Function_de string `json:"Function_de,omitempty"`
	Function_en string `json:"Function_en,omitempty"`
	Function_fr string `json:"Function_fr,omitempty"`
	Function_ja string `json:"Function_ja,omitempty"`
	Short_ja string `json:"Short_ja,omitempty"`
	Long_fr string `json:"Long_fr,omitempty"`
	Short_en string `json:"Short_en,omitempty"`
	Short_fr string `json:"Short_fr,omitempty"`
	Url string `json:"Url,omitempty"`
	Function string `json:"Function,omitempty"`
	Long string `json:"Long,omitempty"`
	Long_en string `json:"Long_en,omitempty"`
	Short_de string `json:"Short_de,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
}
