// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type CabinetCategory struct {
	Icon string `json:"Icon,omitempty"`
	CategoryTargetID int `json:"CategoryTargetID,omitempty"`
	ID int `json:"ID,omitempty"`
	GameContentLinks struct {
		Cabinet struct {
			Category []interface{} `json:"Category,omitempty"`
		}
	}
	IconID int `json:"IconID,omitempty"`
	MenuOrder int `json:"MenuOrder,omitempty"`
	Url string `json:"Url,omitempty"`
	Category struct {
		Text_en string `json:"Text_en,omitempty"`
		Text_fr string `json:"Text_fr,omitempty"`
		Text_ja string `json:"Text_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		Text string `json:"Text,omitempty"`
		Text_de string `json:"Text_de,omitempty"`
	}
	CategoryTarget string `json:"CategoryTarget,omitempty"`
}
