// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type RetainerTaskRandom struct {
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	Name string `json:"Name,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Requirement int `json:"Requirement,omitempty"`
	Url string `json:"Url,omitempty"`
	ID int `json:"ID,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
}
