// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ContentExAction struct {
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	Name struct {
		AttackTypeTargetID int `json:"AttackTypeTargetID,omitempty"`
		StatusGainSelf int `json:"StatusGainSelf,omitempty"`
		AnimationEndTargetID int `json:"AnimationEndTargetID,omitempty"`
		Aspect int `json:"Aspect,omitempty"`
		ActionCombo int `json:"ActionCombo,omitempty"`
		AnimationStartTargetID int `json:"AnimationStartTargetID,omitempty"`
		CanTargetSelf int `json:"CanTargetSelf,omitempty"`
		Cost int `json:"Cost,omitempty"`
		AnimationStartTarget string `json:"AnimationStartTarget,omitempty"`
		ClassJobCategory struct {
			ADV int `json:"ADV,omitempty"`
			BRD int `json:"BRD,omitempty"`
			CUL int `json:"CUL,omitempty"`
			MIN int `json:"MIN,omitempty"`
			NIN int `json:"NIN,omitempty"`
			ACN int `json:"ACN,omitempty"`
			AST int `json:"AST,omitempty"`
			MRD int `json:"MRD,omitempty"`
			WVR int `json:"WVR,omitempty"`
			GLA int `json:"GLA,omitempty"`
			MCH int `json:"MCH,omitempty"`
			PLD int `json:"PLD,omitempty"`
			THM int `json:"THM,omitempty"`
			GSM int `json:"GSM,omitempty"`
			MNK int `json:"MNK,omitempty"`
			Name_ja string `json:"Name_ja,omitempty"`
			RDM int `json:"RDM,omitempty"`
			ROG int `json:"ROG,omitempty"`
			Name_fr string `json:"Name_fr,omitempty"`
			WAR int `json:"WAR,omitempty"`
			ARM int `json:"ARM,omitempty"`
			BTN int `json:"BTN,omitempty"`
			CNJ int `json:"CNJ,omitempty"`
			DRK int `json:"DRK,omitempty"`
			Name_en string `json:"Name_en,omitempty"`
			Name string `json:"Name,omitempty"`
			SAM int `json:"SAM,omitempty"`
			SCH int `json:"SCH,omitempty"`
			ALC int `json:"ALC,omitempty"`
			BSM int `json:"BSM,omitempty"`
			CRP int `json:"CRP,omitempty"`
			DRG int `json:"DRG,omitempty"`
			LNC int `json:"LNC,omitempty"`
			SMN int `json:"SMN,omitempty"`
			ARC int `json:"ARC,omitempty"`
			LTW int `json:"LTW,omitempty"`
			Name_de string `json:"Name_de,omitempty"`
			WHM int `json:"WHM,omitempty"`
			BLM int `json:"BLM,omitempty"`
			FSH int `json:"FSH,omitempty"`
			ID int `json:"ID,omitempty"`
			PGL int `json:"PGL,omitempty"`
		}
		Recast100ms int `json:"Recast100ms,omitempty"`
		CanTargetFriendly int `json:"CanTargetFriendly,omitempty"`
		VFX int `json:"VFX,omitempty"`
		Cast100ms int `json:"Cast100ms,omitempty"`
		Icon string `json:"Icon,omitempty"`
		XAxisModifier int `json:"XAxisModifier,omitempty"`
		ClassJobLevel int `json:"ClassJobLevel,omitempty"`
		CanTargetHostile int `json:"CanTargetHostile,omitempty"`
		AnimationStart struct {
			ID int `json:"ID,omitempty"`
			Name int `json:"Name,omitempty"`
			VFX int `json:"VFX,omitempty"`
		}
		ActionTimelineHit struct {
			ID int `json:"ID,omitempty"`
			Key string `json:"Key,omitempty"`
			Key_en string `json:"Key_en,omitempty"`
		}
		AnimationEnd struct {
			ID int `json:"ID,omitempty"`
			Key string `json:"Key,omitempty"`
			Key_en string `json:"Key_en,omitempty"`
		}
		AnimationEndTarget string `json:"AnimationEndTarget,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		TargetArea int `json:"TargetArea,omitempty"`
		ActionCategoryTargetID int `json:"ActionCategoryTargetID,omitempty"`
		ActionProcStatus int `json:"ActionProcStatus,omitempty"`
		CooldownGroup int `json:"CooldownGroup,omitempty"`
		Omen struct {
			FileName string `json:"FileName,omitempty"`
			FileName_en string `json:"FileName_en,omitempty"`
			ID int `json:"ID,omitempty"`
		}
		OmenTargetID int `json:"OmenTargetID,omitempty"`
		ActionCategoryTarget string `json:"ActionCategoryTarget,omitempty"`
		ActionTimelineHitTarget string `json:"ActionTimelineHitTarget,omitempty"`
		AttackType struct {
			ID int `json:"ID,omitempty"`
			Name string `json:"Name,omitempty"`
			Name_de string `json:"Name_de,omitempty"`
			Name_en string `json:"Name_en,omitempty"`
			Name_fr string `json:"Name_fr,omitempty"`
			Name_ja string `json:"Name_ja,omitempty"`
		}
		AttackTypeTarget string `json:"AttackTypeTarget,omitempty"`
		ClassJobCategoryTarget string `json:"ClassJobCategoryTarget,omitempty"`
		PreservesCombo int `json:"PreservesCombo,omitempty"`
		ActionData int `json:"ActionData,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		IsPvP int `json:"IsPvP,omitempty"`
		IsRoleAction int `json:"IsRoleAction,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		ActionCategory struct {
			ID int `json:"ID,omitempty"`
			Name string `json:"Name,omitempty"`
			Name_de string `json:"Name_de,omitempty"`
			Name_en string `json:"Name_en,omitempty"`
			Name_fr string `json:"Name_fr,omitempty"`
			Name_ja string `json:"Name_ja,omitempty"`
		}
		ClassJob int `json:"ClassJob,omitempty"`
		ClassJobCategoryTargetID int `json:"ClassJobCategoryTargetID,omitempty"`
		OmenTarget string `json:"OmenTarget,omitempty"`
		Range int `json:"Range,omitempty"`
		CastType int `json:"CastType,omitempty"`
		CanTargetDead int `json:"CanTargetDead,omitempty"`
		ID int `json:"ID,omitempty"`
		AffectsPosition int `json:"AffectsPosition,omitempty"`
		CostType int `json:"CostType,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		CanTargetParty int `json:"CanTargetParty,omitempty"`
		EffectRange int `json:"EffectRange,omitempty"`
		IconID int `json:"IconID,omitempty"`
		ActionTimelineHitTargetID int `json:"ActionTimelineHitTargetID,omitempty"`
	}
	NameTarget string `json:"NameTarget,omitempty"`
	NameTargetID int `json:"NameTargetID,omitempty"`
	Url string `json:"Url,omitempty"`
	Charges int `json:"Charges,omitempty"`
}
