// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type LeveAssignmentType struct {
	Name_ja string `json:"Name_ja,omitempty"`
	GameContentLinks struct {
		Leve struct {
			LeveAssignmentType []interface{} `json:"LeveAssignmentType,omitempty"`
		}
	}
	IconID int `json:"IconID,omitempty"`
	IsFaction int `json:"IsFaction,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Url string `json:"Url,omitempty"`
	ID int `json:"ID,omitempty"`
	Icon string `json:"Icon,omitempty"`
	Name string `json:"Name,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
}
