// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type GatheringPointBase struct {
	Item1 int `json:"Item1,omitempty"`
	Item3 int `json:"Item3,omitempty"`
	IsLimited int `json:"IsLimited,omitempty"`
	Item2 int `json:"Item2,omitempty"`
	Url string `json:"Url,omitempty"`
	GatheringLevel int `json:"GatheringLevel,omitempty"`
	GatheringTypeTarget string `json:"GatheringTypeTarget,omitempty"`
	Item4 int `json:"Item4,omitempty"`
	Item5 int `json:"Item5,omitempty"`
	Item7 int `json:"Item7,omitempty"`
	GameContentLinks struct {
		GatheringPoint struct {
			GatheringPointBase []interface{} `json:"GatheringPointBase,omitempty"`
		}
	}
	GatheringType struct {
		ID int `json:"ID,omitempty"`
		IconMain string `json:"IconMain,omitempty"`
		IconMainID int `json:"IconMainID,omitempty"`
		IconOff string `json:"IconOff,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		IconOffID int `json:"IconOffID,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
	}
	GatheringTypeTargetID int `json:"GatheringTypeTargetID,omitempty"`
	ID int `json:"ID,omitempty"`
	Item0 int `json:"Item0,omitempty"`
	Item6 int `json:"Item6,omitempty"`
}
