// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type CompanyCraftDraftCategory struct {
	CompanyCraftType0TargetID int `json:"CompanyCraftType0TargetID,omitempty"`
	CompanyCraftType4Target string `json:"CompanyCraftType4Target,omitempty"`
	CompanyCraftType6 struct {
		Name_ja string `json:"Name_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
	}
	GameContentLinks struct {
		CompanyCraftDraft struct {
			CompanyCraftDraftCategory []interface{} `json:"CompanyCraftDraftCategory,omitempty"`
		}
		CompanyCraftSequence struct {
			CompanyCraftDraftCategory []interface{} `json:"CompanyCraftDraftCategory,omitempty"`
		}
	}
	CompanyCraftType2Target string `json:"CompanyCraftType2Target,omitempty"`
	CompanyCraftType3 struct {
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	CompanyCraftType5Target string `json:"CompanyCraftType5Target,omitempty"`
	CompanyCraftType2TargetID int `json:"CompanyCraftType2TargetID,omitempty"`
	CompanyCraftType4TargetID int `json:"CompanyCraftType4TargetID,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	CompanyCraftType0 struct {
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	CompanyCraftType1 struct {
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	CompanyCraftType1Target string `json:"CompanyCraftType1Target,omitempty"`
	Name string `json:"Name,omitempty"`
	CompanyCraftType4 struct {
		ID int `json:"ID,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
	}
	CompanyCraftType6Target string `json:"CompanyCraftType6Target,omitempty"`
	CompanyCraftType1TargetID int `json:"CompanyCraftType1TargetID,omitempty"`
	CompanyCraftType3Target string `json:"CompanyCraftType3Target,omitempty"`
	CompanyCraftType3TargetID int `json:"CompanyCraftType3TargetID,omitempty"`
	CompanyCraftType5 struct {
		Name_ja string `json:"Name_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
	}
	CompanyCraftType6TargetID int `json:"CompanyCraftType6TargetID,omitempty"`
	CompanyCraftType7TargetID int `json:"CompanyCraftType7TargetID,omitempty"`
	CompanyCraftType8 int `json:"CompanyCraftType8,omitempty"`
	ID int `json:"ID,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	Url string `json:"Url,omitempty"`
	CompanyCraftType0Target string `json:"CompanyCraftType0Target,omitempty"`
	CompanyCraftType5TargetID int `json:"CompanyCraftType5TargetID,omitempty"`
	CompanyCraftType7 struct {
		ID int `json:"ID,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
	}
	CompanyCraftType2 struct {
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	CompanyCraftType7Target string `json:"CompanyCraftType7Target,omitempty"`
	CompanyCraftType9 int `json:"CompanyCraftType9,omitempty"`
}
