// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type MoveTimeline struct {
	MoveRight struct {
		Key_en string `json:"Key_en,omitempty"`
		ID int `json:"ID,omitempty"`
		Key string `json:"Key,omitempty"`
	}
	MoveTurnRightTargetID int `json:"MoveTurnRightTargetID,omitempty"`
	MoveUp struct {
		Key string `json:"Key,omitempty"`
		Key_en string `json:"Key_en,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	MoveBackTargetID int `json:"MoveBackTargetID,omitempty"`
	MoveRightTarget string `json:"MoveRightTarget,omitempty"`
	MoveTurnRight struct {
		ID int `json:"ID,omitempty"`
		Key string `json:"Key,omitempty"`
		Key_en string `json:"Key_en,omitempty"`
	}
	MoveDownTargetID int `json:"MoveDownTargetID,omitempty"`
	MoveForwardTarget string `json:"MoveForwardTarget,omitempty"`
	MoveTurnRightTarget string `json:"MoveTurnRightTarget,omitempty"`
	Extra struct {
		Key_en string `json:"Key_en,omitempty"`
		ID int `json:"ID,omitempty"`
		Key string `json:"Key,omitempty"`
	}
	ID int `json:"ID,omitempty"`
	MoveRightTargetID int `json:"MoveRightTargetID,omitempty"`
	MoveTurnLeftTarget string `json:"MoveTurnLeftTarget,omitempty"`
	MoveUpTargetID int `json:"MoveUpTargetID,omitempty"`
	Idle struct {
		Key_en string `json:"Key_en,omitempty"`
		ID int `json:"ID,omitempty"`
		Key string `json:"Key,omitempty"`
	}
	MoveLeftTargetID int `json:"MoveLeftTargetID,omitempty"`
	MoveBackTarget string `json:"MoveBackTarget,omitempty"`
	ExtraTargetID int `json:"ExtraTargetID,omitempty"`
	IdleTarget string `json:"IdleTarget,omitempty"`
	MoveDownTarget string `json:"MoveDownTarget,omitempty"`
	MoveForwardTargetID int `json:"MoveForwardTargetID,omitempty"`
	MoveTurnLeft struct {
		ID int `json:"ID,omitempty"`
		Key string `json:"Key,omitempty"`
		Key_en string `json:"Key_en,omitempty"`
	}
	MoveUpTarget string `json:"MoveUpTarget,omitempty"`
	ExtraTarget string `json:"ExtraTarget,omitempty"`
	IdleTargetID int `json:"IdleTargetID,omitempty"`
	MoveLeft struct {
		ID int `json:"ID,omitempty"`
		Key string `json:"Key,omitempty"`
		Key_en string `json:"Key_en,omitempty"`
	}
	MoveTurnLeftTargetID int `json:"MoveTurnLeftTargetID,omitempty"`
	MoveDown struct {
		Key string `json:"Key,omitempty"`
		Key_en string `json:"Key_en,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	MoveForward struct {
		Key string `json:"Key,omitempty"`
		Key_en string `json:"Key_en,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	Url string `json:"Url,omitempty"`
	MoveBack struct {
		Key_en string `json:"Key_en,omitempty"`
		ID int `json:"ID,omitempty"`
		Key string `json:"Key,omitempty"`
	}
	MoveLeftTarget string `json:"MoveLeftTarget,omitempty"`
}
