// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type Pet struct {
	GameContentLinks struct {
		PetAction struct {
			Pet []interface{} `json:"Pet,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	Name string `json:"Name,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	GamePatch interface{} `json:"GamePatch,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	Url string `json:"Url,omitempty"`
}
