// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type BGM struct {
	GameContentLinks struct {
		Leve struct {
			BGM []interface{} `json:"BGM,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	Url string `json:"Url,omitempty"`
	File string `json:"File,omitempty"`
	File_en string `json:"File_en,omitempty"`
}
