// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type GcArmyTraining struct {
	TacticalBonus int `json:"TacticalBonus,omitempty"`
	Description_fr string `json:"Description_fr,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	MentalBonus int `json:"MentalBonus,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	Name string `json:"Name,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Url string `json:"Url,omitempty"`
	Description_en string `json:"Description_en,omitempty"`
	Description_ja string `json:"Description_ja,omitempty"`
	Description string `json:"Description,omitempty"`
	Description_de string `json:"Description_de,omitempty"`
	Experience int `json:"Experience,omitempty"`
	PhysicalBonus int `json:"PhysicalBonus,omitempty"`
}
