// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type WorldDCGroupType struct {
	Name_en string `json:"Name_en,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks struct {
		World struct {
			DataCenter []interface{} `json:"DataCenter,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	Name string `json:"Name,omitempty"`
}
