// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type GuildOrderGuide struct {
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	Url string `json:"Url,omitempty"`
}
