// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type AirshipExplorationLevel struct {
	ExpToNext int `json:"ExpToNext,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	Url string `json:"Url,omitempty"`
}
