// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type FCActivity struct {
	Url string `json:"Url,omitempty"`
	FCActivityCategory struct {
		ID int `json:"ID,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
	}
	FCActivityCategoryTargetID int `json:"FCActivityCategoryTargetID,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	Text string `json:"Text,omitempty"`
	Text_fr string `json:"Text_fr,omitempty"`
	FCActivityCategoryTarget string `json:"FCActivityCategoryTarget,omitempty"`
	Text_de string `json:"Text_de,omitempty"`
	Text_en string `json:"Text_en,omitempty"`
	Text_ja string `json:"Text_ja,omitempty"`
}
