// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ArrayEventHandler struct {
	MULTIREF11 int `json:"MULTIREF11,omitempty"`
	MULTIREF2 int `json:"MULTIREF2,omitempty"`
	MULTIREF6 int `json:"MULTIREF6,omitempty"`
	MULTIREF10 int `json:"MULTIREF10,omitempty"`
	MULTIREF12 int `json:"MULTIREF12,omitempty"`
	MULTIREF14 int `json:"MULTIREF14,omitempty"`
	MULTIREF5 int `json:"MULTIREF5,omitempty"`
	MULTIREF7 int `json:"MULTIREF7,omitempty"`
	MULTIREF8 int `json:"MULTIREF8,omitempty"`
	MULTIREF9 int `json:"MULTIREF9,omitempty"`
	MULTIREF0 int `json:"MULTIREF0,omitempty"`
	MULTIREF1 int `json:"MULTIREF1,omitempty"`
	MULTIREF13 int `json:"MULTIREF13,omitempty"`
	MULTIREF15 int `json:"MULTIREF15,omitempty"`
	MULTIREF3 int `json:"MULTIREF3,omitempty"`
	MULTIREF4 int `json:"MULTIREF4,omitempty"`
	Url string `json:"Url,omitempty"`
	ID int `json:"ID,omitempty"`
	GameContentLinks struct {
		BNpcBase struct {
			ArrayEventHandler []interface{} `json:"ArrayEventHandler,omitempty"`
		}
	}
}
