// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type DpsChallenge struct {
	Description_en string `json:"Description_en,omitempty"`
	GameContentLinks struct {
		DpsChallengeOfficer struct {
			ChallengeName18 []interface{} `json:"ChallengeName18,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	PlaceNameTargetID int `json:"PlaceNameTargetID,omitempty"`
	InstanceContentTarget string `json:"InstanceContentTarget,omitempty"`
	Name string `json:"Name,omitempty"`
	PlayerLevel int `json:"PlayerLevel,omitempty"`
	Url string `json:"Url,omitempty"`
	PlaceNameTarget string `json:"PlaceNameTarget,omitempty"`
	Description string `json:"Description,omitempty"`
	Description_de string `json:"Description_de,omitempty"`
	Icon string `json:"Icon,omitempty"`
	IconID int `json:"IconID,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Order int `json:"Order,omitempty"`
	Description_fr string `json:"Description_fr,omitempty"`
	Description_ja string `json:"Description_ja,omitempty"`
	InstanceContent struct {
		InstanceContentBuff int `json:"InstanceContentBuff,omitempty"`
		InstanceContentTextDataObjectiveEnd struct {
			Text_de string `json:"Text_de,omitempty"`
			Text_en string `json:"Text_en,omitempty"`
			Text_fr string `json:"Text_fr,omitempty"`
			Text_ja string `json:"Text_ja,omitempty"`
			ID int `json:"ID,omitempty"`
			Text string `json:"Text,omitempty"`
		}
		InstanceContentTextDataBossStart int `json:"InstanceContentTextDataBossStart,omitempty"`
		InstanceContentTextDataObjectiveStartTarget string `json:"InstanceContentTextDataObjectiveStartTarget,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		NewPlayerBonusB int `json:"NewPlayerBonusB,omitempty"`
		PartyCondition int `json:"PartyCondition,omitempty"`
		SortKey int `json:"SortKey,omitempty"`
		InstanceContentTextDataBossEnd int `json:"InstanceContentTextDataBossEnd,omitempty"`
		BossCurrencyB1 int `json:"BossCurrencyB1,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		TerritoryTypeTargetID int `json:"TerritoryTypeTargetID,omitempty"`
		BNpcBaseBossTargetID int `json:"BNpcBaseBossTargetID,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		InstanceContentBuffTargetID int `json:"InstanceContentBuffTargetID,omitempty"`
		FinalBossCurrencyC int `json:"FinalBossCurrencyC,omitempty"`
		InstanceContentTextDataObjectiveEndTarget string `json:"InstanceContentTextDataObjectiveEndTarget,omitempty"`
		BossCurrencyC3 int `json:"BossCurrencyC3,omitempty"`
		BossCurrencyB0 int `json:"BossCurrencyB0,omitempty"`
		InstanceContentTextDataObjectiveStart struct {
			ID int `json:"ID,omitempty"`
			Text string `json:"Text,omitempty"`
			Text_de string `json:"Text_de,omitempty"`
			Text_en string `json:"Text_en,omitempty"`
			Text_fr string `json:"Text_fr,omitempty"`
			Text_ja string `json:"Text_ja,omitempty"`
		}
		BossCurrencyB2 int `json:"BossCurrencyB2,omitempty"`
		BossCurrencyC0 int `json:"BossCurrencyC0,omitempty"`
		BossCurrencyC2 int `json:"BossCurrencyC2,omitempty"`
		BossCurrencyA1 int `json:"BossCurrencyA1,omitempty"`
		BossCurrencyA4 int `json:"BossCurrencyA4,omitempty"`
		FinalBossCurrencyB int `json:"FinalBossCurrencyB,omitempty"`
		InstanceContentTextDataObjectiveStartTargetID int `json:"InstanceContentTextDataObjectiveStartTargetID,omitempty"`
		BGM struct {
			File_en string `json:"File_en,omitempty"`
			ID int `json:"ID,omitempty"`
			File string `json:"File,omitempty"`
		}
		InstanceContentTypeTargetID int `json:"InstanceContentTypeTargetID,omitempty"`
		InstanceContentType struct {
			ID int `json:"ID,omitempty"`
		}
		NewPlayerBonusA int `json:"NewPlayerBonusA,omitempty"`
		BGMTargetID int `json:"BGMTargetID,omitempty"`
		BossCurrencyC4 int `json:"BossCurrencyC4,omitempty"`
		TerritoryTypeTarget string `json:"TerritoryTypeTarget,omitempty"`
		TimeLimitMin int `json:"TimeLimitMin,omitempty"`
		BossCurrencyB3 int `json:"BossCurrencyB3,omitempty"`
		BossCurrencyC1 int `json:"BossCurrencyC1,omitempty"`
		InstanceContentTypeTarget string `json:"InstanceContentTypeTarget,omitempty"`
		Name string `json:"Name,omitempty"`
		Order int `json:"Order,omitempty"`
		TerritoryType struct {
			ArrayEventHandler int `json:"ArrayEventHandler,omitempty"`
			Bg_en string `json:"Bg_en,omitempty"`
			ID int `json:"ID,omitempty"`
			Name string `json:"Name,omitempty"`
			Name_en string `json:"Name_en,omitempty"`
			PlaceNameZone int `json:"PlaceNameZone,omitempty"`
			WeatherRate int `json:"WeatherRate,omitempty"`
			Aetheryte int `json:"Aetheryte,omitempty"`
			Bg string `json:"Bg,omitempty"`
			Map int `json:"Map,omitempty"`
			PlaceName int `json:"PlaceName,omitempty"`
			PlaceNameRegion int `json:"PlaceNameRegion,omitempty"`
			TerritoryIntendedUse int `json:"TerritoryIntendedUse,omitempty"`
		}
		BGMTarget string `json:"BGMTarget,omitempty"`
		BossCurrencyA3 int `json:"BossCurrencyA3,omitempty"`
		InstanceContentTextDataObjectiveEndTargetID int `json:"InstanceContentTextDataObjectiveEndTargetID,omitempty"`
		BNpcBaseBoss int `json:"BNpcBaseBoss,omitempty"`
		BossCurrencyA0 int `json:"BossCurrencyA0,omitempty"`
		ID int `json:"ID,omitempty"`
		WeekRestriction int `json:"WeekRestriction,omitempty"`
		BNpcBaseBossTarget string `json:"BNpcBaseBossTarget,omitempty"`
		BossCurrencyA2 int `json:"BossCurrencyA2,omitempty"`
		BossCurrencyB4 int `json:"BossCurrencyB4,omitempty"`
		FinalBossCurrencyA int `json:"FinalBossCurrencyA,omitempty"`
		InstanceContentBuffTarget string `json:"InstanceContentBuffTarget,omitempty"`
	}
	InstanceContentTargetID int `json:"InstanceContentTargetID,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	PlaceName struct {
		Name string `json:"Name,omitempty"`
		NameNoArticle_en string `json:"NameNoArticle_en,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		Icon string `json:"Icon,omitempty"`
		NameNoArticle string `json:"NameNoArticle,omitempty"`
		NameNoArticle_de string `json:"NameNoArticle_de,omitempty"`
		NameNoArticle_fr string `json:"NameNoArticle_fr,omitempty"`
		NameNoArticle_ja string `json:"NameNoArticle_ja,omitempty"`
	}
}
