// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ChocoboRaceTerritory struct {
	ID int `json:"ID,omitempty"`
	Icon string `json:"Icon,omitempty"`
	IconID int `json:"IconID,omitempty"`
	Name struct {
		ID int `json:"ID,omitempty"`
		Text string `json:"Text,omitempty"`
		Text_de string `json:"Text_de,omitempty"`
		Text_en string `json:"Text_en,omitempty"`
		Text_fr string `json:"Text_fr,omitempty"`
		Text_ja string `json:"Text_ja,omitempty"`
	}
	NameTarget string `json:"NameTarget,omitempty"`
	NameTargetID int `json:"NameTargetID,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks struct {
		ChocoboRace struct {
			ChocoboRaceTerritory []interface{} `json:"ChocoboRaceTerritory,omitempty"`
		}
	}
}
