// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type RacingChocoboNameCategory struct {
	Name string `json:"Name,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	GameContentLinks struct {
		RacingChocoboNameInfo struct {
			RacingChocoboNameCategory []interface{} `json:"RacingChocoboNameCategory,omitempty"`
		}
	}
	Name_en string `json:"Name_en,omitempty"`
	SortKey int `json:"SortKey,omitempty"`
	Url string `json:"Url,omitempty"`
	ID int `json:"ID,omitempty"`
}
