// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type LeveVfx struct {
	IconID int `json:"IconID,omitempty"`
	Url string `json:"Url,omitempty"`
	Effect string `json:"Effect,omitempty"`
	Effect_en string `json:"Effect_en,omitempty"`
	GameContentLinks struct {
		Leve struct {
			LeveVfxFrame []interface{} `json:"LeveVfxFrame,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	Icon string `json:"Icon,omitempty"`
}
