// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type World struct {
	ID int `json:"ID,omitempty"`
	Url string `json:"Url,omitempty"`
	DataCenter struct {
		ID int `json:"ID,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
	}
	DataCenterTarget string `json:"DataCenterTarget,omitempty"`
	DataCenterTargetID int `json:"DataCenterTargetID,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
}
