// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ModelChara struct {
	GameContentLinks struct {
		BNpcBase struct {
			ModelChara []interface{} `json:"ModelChara,omitempty"`
		}
		Transformation struct {
			Model []interface{} `json:"Model,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	Model int `json:"Model,omitempty"`
	Type int `json:"Type,omitempty"`
	Url string `json:"Url,omitempty"`
	Variant int `json:"Variant,omitempty"`
	Base int `json:"Base,omitempty"`
}
