// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type PvPTrait struct {
	Url string `json:"Url,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	Trait1 int `json:"Trait1,omitempty"`
	Trait2 int `json:"Trait2,omitempty"`
	Trait3 int `json:"Trait3,omitempty"`
}
