// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ChocoboRaceAbility struct {
	Name_fr string `json:"Name_fr,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	Description_en string `json:"Description_en,omitempty"`
	ID int `json:"ID,omitempty"`
	Icon string `json:"Icon,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Description_de string `json:"Description_de,omitempty"`
	Description_ja string `json:"Description_ja,omitempty"`
	IconID int `json:"IconID,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	Url string `json:"Url,omitempty"`
	ChocoboRaceAbilityTypeTarget string `json:"ChocoboRaceAbilityTypeTarget,omitempty"`
	ChocoboRaceAbilityTypeTargetID int `json:"ChocoboRaceAbilityTypeTargetID,omitempty"`
	Description string `json:"Description,omitempty"`
	Value int `json:"Value,omitempty"`
	ChocoboRaceAbilityType struct {
		IsActive int `json:"IsActive,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	Description_fr string `json:"Description_fr,omitempty"`
	Name string `json:"Name,omitempty"`
}
