// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type GCRankLimsaFemaleText struct {
	Name string `json:"Name,omitempty"`
	NameRank_ja string `json:"NameRank_ja,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	NameRank string `json:"NameRank,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Plural string `json:"Plural,omitempty"`
	Plural_fr string `json:"Plural_fr,omitempty"`
	Plural_ja string `json:"Plural_ja,omitempty"`
	NameRank_de string `json:"NameRank_de,omitempty"`
	NameRank_en string `json:"NameRank_en,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	NameRank_fr string `json:"NameRank_fr,omitempty"`
	Plural_de string `json:"Plural_de,omitempty"`
	Plural_en string `json:"Plural_en,omitempty"`
}
