// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type MacroIconRedirectOld struct {
	ID int `json:"ID,omitempty"`
	IconNew string `json:"IconNew,omitempty"`
	IconNewID int `json:"IconNewID,omitempty"`
	IconOld string `json:"IconOld,omitempty"`
	IconOldID int `json:"IconOldID,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
}
