// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type EObjName struct {
	ID int `json:"ID,omitempty"`
	Singular string `json:"Singular,omitempty"`
	Singular_de string `json:"Singular_de,omitempty"`
	Singular_en string `json:"Singular_en,omitempty"`
	Singular_fr string `json:"Singular_fr,omitempty"`
	Singular_ja string `json:"Singular_ja,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks struct {
		SkyIsland2MissionDetail struct {
			EObj []interface{} `json:"EObj,omitempty"`
		}
	}
}
