// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type DisposalShopFilterType struct {
	Category string `json:"Category,omitempty"`
	Category_de string `json:"Category_de,omitempty"`
	Category_en string `json:"Category_en,omitempty"`
	Category_fr string `json:"Category_fr,omitempty"`
	Category_ja string `json:"Category_ja,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	Url string `json:"Url,omitempty"`
}
