// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type FishingRecordTypeTransient struct {
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	Image string `json:"Image,omitempty"`
	ImageID int `json:"ImageID,omitempty"`
	Url string `json:"Url,omitempty"`
}
