// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type AchievementCategory struct {
	Name string `json:"Name,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	ID int `json:"ID,omitempty"`
	AchievementKindTarget string `json:"AchievementKindTarget,omitempty"`
	AchievementKindTargetID int `json:"AchievementKindTargetID,omitempty"`
	GameContentLinks struct {
		Achievement struct {
			AchievementCategory []interface{} `json:"AchievementCategory,omitempty"`
		}
	}
	Name_en string `json:"Name_en,omitempty"`
	Url string `json:"Url,omitempty"`
	AchievementKind struct {
		ID int `json:"ID,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
	}
}
