// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type EventIconType struct {
	ID int `json:"ID,omitempty"`
	MapIconAvailable string `json:"MapIconAvailable,omitempty"`
	MapIconInvalidID int `json:"MapIconInvalidID,omitempty"`
	NpcIconAvailableID int `json:"NpcIconAvailableID,omitempty"`
	NpcIconInvalid string `json:"NpcIconInvalid,omitempty"`
	GameContentLinks struct {
		Quest struct {
			EventIconType []interface{} `json:"EventIconType,omitempty"`
		}
	}
	IconRange int `json:"IconRange,omitempty"`
	MapIconAvailableID int `json:"MapIconAvailableID,omitempty"`
	MapIconInvalid string `json:"MapIconInvalid,omitempty"`
	NpcIconAvailable string `json:"NpcIconAvailable,omitempty"`
	NpcIconInvalidID int `json:"NpcIconInvalidID,omitempty"`
	Url string `json:"Url,omitempty"`
}
