// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type BeastReputationRank struct {
	Name string `json:"Name,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	RequiredReputation int `json:"RequiredReputation,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks struct {
		Quest struct {
			BeastReputationRank []interface{} `json:"BeastReputationRank,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
}
