// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type EventItemCastTimeline struct {
	ActionTimelineTargetID int `json:"ActionTimelineTargetID,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	Url string `json:"Url,omitempty"`
	ActionTimeline struct {
		Key string `json:"Key,omitempty"`
		Key_en string `json:"Key_en,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	ActionTimelineTarget string `json:"ActionTimelineTarget,omitempty"`
}
