// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type CompanyCraftPart struct {
	CompanyCraftProcess1Target string `json:"CompanyCraftProcess1Target,omitempty"`
	CompanyCraftType struct {
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
	}
	CompanyCraftTypeTargetID int `json:"CompanyCraftTypeTargetID,omitempty"`
	GameContentLinks struct {
		CompanyCraftSequence struct {
			CompanyCraftPart0 []interface{} `json:"CompanyCraftPart0,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	CompanyCraftProcess0 struct {
		SupplyItem3Target string `json:"SupplyItem3Target,omitempty"`
		SupplyItem5TargetID int `json:"SupplyItem5TargetID,omitempty"`
		SupplyItem6 int `json:"SupplyItem6,omitempty"`
		SetQuantity3 int `json:"SetQuantity3,omitempty"`
		SetQuantity5 int `json:"SetQuantity5,omitempty"`
		SetsRequired5 int `json:"SetsRequired5,omitempty"`
		SupplyItem10 int `json:"SupplyItem10,omitempty"`
		SupplyItem0 struct {
			ID int `json:"ID,omitempty"`
			Item int `json:"Item,omitempty"`
		}
		SupplyItem0TargetID int `json:"SupplyItem0TargetID,omitempty"`
		SupplyItem1Target string `json:"SupplyItem1Target,omitempty"`
		SupplyItem9 int `json:"SupplyItem9,omitempty"`
		ID int `json:"ID,omitempty"`
		SetQuantity0 int `json:"SetQuantity0,omitempty"`
		SetQuantity10 int `json:"SetQuantity10,omitempty"`
		SetQuantity8 int `json:"SetQuantity8,omitempty"`
		SetQuantity11 int `json:"SetQuantity11,omitempty"`
		SetsRequired1 int `json:"SetsRequired1,omitempty"`
		SupplyItem3TargetID int `json:"SupplyItem3TargetID,omitempty"`
		SupplyItem8 int `json:"SupplyItem8,omitempty"`
		SetsRequired4 int `json:"SetsRequired4,omitempty"`
		SupplyItem1 struct {
			ID int `json:"ID,omitempty"`
			Item int `json:"Item,omitempty"`
		}
		SupplyItem11 int `json:"SupplyItem11,omitempty"`
		SupplyItem2Target string `json:"SupplyItem2Target,omitempty"`
		SetQuantity1 int `json:"SetQuantity1,omitempty"`
		SetQuantity4 int `json:"SetQuantity4,omitempty"`
		SetsRequired2 int `json:"SetsRequired2,omitempty"`
		SetsRequired3 int `json:"SetsRequired3,omitempty"`
		SupplyItem2 struct {
			ID int `json:"ID,omitempty"`
			Item int `json:"Item,omitempty"`
		}
		SupplyItem5 struct {
			ID int `json:"ID,omitempty"`
			Item int `json:"Item,omitempty"`
		}
		SetQuantity6 int `json:"SetQuantity6,omitempty"`
		SetQuantity7 int `json:"SetQuantity7,omitempty"`
		SetsRequired0 int `json:"SetsRequired0,omitempty"`
		SetsRequired11 int `json:"SetsRequired11,omitempty"`
		SetsRequired7 int `json:"SetsRequired7,omitempty"`
		SupplyItem3 struct {
			ID int `json:"ID,omitempty"`
			Item int `json:"Item,omitempty"`
		}
		SupplyItem4Target string `json:"SupplyItem4Target,omitempty"`
		SupplyItem5Target string `json:"SupplyItem5Target,omitempty"`
		SupplyItem0Target string `json:"SupplyItem0Target,omitempty"`
		SupplyItem2TargetID int `json:"SupplyItem2TargetID,omitempty"`
		SupplyItem7 int `json:"SupplyItem7,omitempty"`
		SetQuantity2 int `json:"SetQuantity2,omitempty"`
		SetQuantity9 int `json:"SetQuantity9,omitempty"`
		SetsRequired6 int `json:"SetsRequired6,omitempty"`
		SetsRequired9 int `json:"SetsRequired9,omitempty"`
		SupplyItem4TargetID int `json:"SupplyItem4TargetID,omitempty"`
		SetsRequired10 int `json:"SetsRequired10,omitempty"`
		SetsRequired8 int `json:"SetsRequired8,omitempty"`
		SupplyItem1TargetID int `json:"SupplyItem1TargetID,omitempty"`
		SupplyItem4 struct {
			Item int `json:"Item,omitempty"`
			ID int `json:"ID,omitempty"`
		}
	}
	CompanyCraftProcess1TargetID int `json:"CompanyCraftProcess1TargetID,omitempty"`
	CompanyCraftProcess2 struct {
		SetQuantity5 int `json:"SetQuantity5,omitempty"`
		SetsRequired0 int `json:"SetsRequired0,omitempty"`
		SetsRequired10 int `json:"SetsRequired10,omitempty"`
		SetQuantity2 int `json:"SetQuantity2,omitempty"`
		SetQuantity11 int `json:"SetQuantity11,omitempty"`
		SetsRequired11 int `json:"SetsRequired11,omitempty"`
		SetsRequired5 int `json:"SetsRequired5,omitempty"`
		SupplyItem3Target string `json:"SupplyItem3Target,omitempty"`
		SupplyItem4Target string `json:"SupplyItem4Target,omitempty"`
		SupplyItem8 int `json:"SupplyItem8,omitempty"`
		ID int `json:"ID,omitempty"`
		SetQuantity7 int `json:"SetQuantity7,omitempty"`
		SetQuantity8 int `json:"SetQuantity8,omitempty"`
		SetsRequired2 int `json:"SetsRequired2,omitempty"`
		SupplyItem0TargetID int `json:"SupplyItem0TargetID,omitempty"`
		SupplyItem6 int `json:"SupplyItem6,omitempty"`
		SetQuantity6 int `json:"SetQuantity6,omitempty"`
		SetsRequired3 int `json:"SetsRequired3,omitempty"`
		SetsRequired6 int `json:"SetsRequired6,omitempty"`
		SetsRequired9 int `json:"SetsRequired9,omitempty"`
		SupplyItem3TargetID int `json:"SupplyItem3TargetID,omitempty"`
		SupplyItem4TargetID int `json:"SupplyItem4TargetID,omitempty"`
		SetQuantity9 int `json:"SetQuantity9,omitempty"`
		SetQuantity4 int `json:"SetQuantity4,omitempty"`
		SetsRequired8 int `json:"SetsRequired8,omitempty"`
		SupplyItem1Target string `json:"SupplyItem1Target,omitempty"`
		SupplyItem7 int `json:"SupplyItem7,omitempty"`
		SupplyItem9 int `json:"SupplyItem9,omitempty"`
		SetQuantity1 int `json:"SetQuantity1,omitempty"`
		SetsRequired4 int `json:"SetsRequired4,omitempty"`
		SetsRequired7 int `json:"SetsRequired7,omitempty"`
		SupplyItem0 struct {
			ID int `json:"ID,omitempty"`
			Item int `json:"Item,omitempty"`
		}
		SupplyItem10 int `json:"SupplyItem10,omitempty"`
		SupplyItem1TargetID int `json:"SupplyItem1TargetID,omitempty"`
		SupplyItem2 struct {
			ID int `json:"ID,omitempty"`
			Item int `json:"Item,omitempty"`
		}
		SupplyItem4 struct {
			ID int `json:"ID,omitempty"`
			Item int `json:"Item,omitempty"`
		}
		SetQuantity10 int `json:"SetQuantity10,omitempty"`
		SupplyItem5 struct {
			ID int `json:"ID,omitempty"`
			Item int `json:"Item,omitempty"`
		}
		SupplyItem0Target string `json:"SupplyItem0Target,omitempty"`
		SupplyItem1 struct {
			ID int `json:"ID,omitempty"`
			Item int `json:"Item,omitempty"`
		}
		SupplyItem11 int `json:"SupplyItem11,omitempty"`
		SupplyItem5Target string `json:"SupplyItem5Target,omitempty"`
		SupplyItem5TargetID int `json:"SupplyItem5TargetID,omitempty"`
		SetQuantity3 int `json:"SetQuantity3,omitempty"`
		SetsRequired1 int `json:"SetsRequired1,omitempty"`
		SupplyItem2Target string `json:"SupplyItem2Target,omitempty"`
		SupplyItem2TargetID int `json:"SupplyItem2TargetID,omitempty"`
		SupplyItem3 struct {
			ID int `json:"ID,omitempty"`
			Item int `json:"Item,omitempty"`
		}
		SetQuantity0 int `json:"SetQuantity0,omitempty"`
	}
	CompanyCraftProcess2TargetID int `json:"CompanyCraftProcess2TargetID,omitempty"`
	CompanyCraftProcess1 struct {
		SetsRequired2 int `json:"SetsRequired2,omitempty"`
		SupplyItem4 struct {
			ID int `json:"ID,omitempty"`
			Item int `json:"Item,omitempty"`
		}
		SupplyItem6 int `json:"SupplyItem6,omitempty"`
		SupplyItem8 int `json:"SupplyItem8,omitempty"`
		ID int `json:"ID,omitempty"`
		SetQuantity4 int `json:"SetQuantity4,omitempty"`
		SetsRequired8 int `json:"SetsRequired8,omitempty"`
		SupplyItem0Target string `json:"SupplyItem0Target,omitempty"`
		SupplyItem11 int `json:"SupplyItem11,omitempty"`
		SupplyItem2 struct {
			ID int `json:"ID,omitempty"`
			Item int `json:"Item,omitempty"`
		}
		SupplyItem2TargetID int `json:"SupplyItem2TargetID,omitempty"`
		SupplyItem7 int `json:"SupplyItem7,omitempty"`
		SetQuantity11 int `json:"SetQuantity11,omitempty"`
		SetsRequired3 int `json:"SetsRequired3,omitempty"`
		SetsRequired7 int `json:"SetsRequired7,omitempty"`
		SupplyItem0TargetID int `json:"SupplyItem0TargetID,omitempty"`
		SupplyItem1TargetID int `json:"SupplyItem1TargetID,omitempty"`
		SetsRequired9 int `json:"SetsRequired9,omitempty"`
		SetQuantity0 int `json:"SetQuantity0,omitempty"`
		SetQuantity5 int `json:"SetQuantity5,omitempty"`
		SetQuantity7 int `json:"SetQuantity7,omitempty"`
		SetsRequired0 int `json:"SetsRequired0,omitempty"`
		SetsRequired6 int `json:"SetsRequired6,omitempty"`
		SupplyItem3Target string `json:"SupplyItem3Target,omitempty"`
		SupplyItem4Target string `json:"SupplyItem4Target,omitempty"`
		SupplyItem5 int `json:"SupplyItem5,omitempty"`
		SetsRequired10 int `json:"SetsRequired10,omitempty"`
		SetsRequired4 int `json:"SetsRequired4,omitempty"`
		SetsRequired5 int `json:"SetsRequired5,omitempty"`
		SupplyItem1 struct {
			Item int `json:"Item,omitempty"`
			ID int `json:"ID,omitempty"`
		}
		SupplyItem2Target string `json:"SupplyItem2Target,omitempty"`
		SupplyItem10 int `json:"SupplyItem10,omitempty"`
		SupplyItem3 struct {
			ID int `json:"ID,omitempty"`
			Item int `json:"Item,omitempty"`
		}
		SupplyItem3TargetID int `json:"SupplyItem3TargetID,omitempty"`
		SetQuantity10 int `json:"SetQuantity10,omitempty"`
		SetQuantity3 int `json:"SetQuantity3,omitempty"`
		SetQuantity8 int `json:"SetQuantity8,omitempty"`
		SetsRequired11 int `json:"SetsRequired11,omitempty"`
		SupplyItem0 struct {
			ID int `json:"ID,omitempty"`
			Item int `json:"Item,omitempty"`
		}
		SupplyItem9 int `json:"SupplyItem9,omitempty"`
		SupplyItem1Target string `json:"SupplyItem1Target,omitempty"`
		SupplyItem4TargetID int `json:"SupplyItem4TargetID,omitempty"`
		SetQuantity1 int `json:"SetQuantity1,omitempty"`
		SetQuantity2 int `json:"SetQuantity2,omitempty"`
		SetQuantity6 int `json:"SetQuantity6,omitempty"`
		SetQuantity9 int `json:"SetQuantity9,omitempty"`
		SetsRequired1 int `json:"SetsRequired1,omitempty"`
	}
	Url string `json:"Url,omitempty"`
	CompanyCraftProcess2Target string `json:"CompanyCraftProcess2Target,omitempty"`
	CompanyCraftProcess0TargetID int `json:"CompanyCraftProcess0TargetID,omitempty"`
	CompanyCraftTypeTarget string `json:"CompanyCraftTypeTarget,omitempty"`
	CompanyCraftProcess0Target string `json:"CompanyCraftProcess0Target,omitempty"`
}
