// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type GatheringItem struct {
	IsHidden int `json:"IsHidden,omitempty"`
	Item int `json:"Item,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks struct {
		GatheringNotebookList struct {
			GatheringItem12 []interface{} `json:"GatheringItem12,omitempty"`
			GatheringItem13 []interface{} `json:"GatheringItem13,omitempty"`
			GatheringItem14 []interface{} `json:"GatheringItem14,omitempty"`
			GatheringItem16 []interface{} `json:"GatheringItem16,omitempty"`
		}
		RetainerTaskNormal struct {
			GatheringLog []interface{} `json:"GatheringLog,omitempty"`
		}
	}
	GatheringItemLevel struct {
		GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
		ID int `json:"ID,omitempty"`
		Stars int `json:"Stars,omitempty"`
	}
	GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
	GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
	ID int `json:"ID,omitempty"`
}
