// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type GCSupplyDutyReward struct {
	SealsExpertDelivery int `json:"SealsExpertDelivery,omitempty"`
	SealsProvisioning int `json:"SealsProvisioning,omitempty"`
	SealsSupply int `json:"SealsSupply,omitempty"`
	Url string `json:"Url,omitempty"`
	ExperienceProvisioning int `json:"ExperienceProvisioning,omitempty"`
	ExperienceSupply int `json:"ExperienceSupply,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
}
