// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type AnimaWeaponIcon struct {
	Sharpened string `json:"Sharpened,omitempty"`
	SharpenedID int `json:"SharpenedID,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	HyperconductiveID int `json:"HyperconductiveID,omitempty"`
	ID int `json:"ID,omitempty"`
	Reborn string `json:"Reborn,omitempty"`
	RebornID int `json:"RebornID,omitempty"`
	ZodiacID int `json:"ZodiacID,omitempty"`
	Hyperconductive string `json:"Hyperconductive,omitempty"`
	Zodiac string `json:"Zodiac,omitempty"`
	ZodiacLux string `json:"ZodiacLux,omitempty"`
	ZodiacLuxID int `json:"ZodiacLuxID,omitempty"`
}
