// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ChocoboRaceAbilityType struct {
	Url string `json:"Url,omitempty"`
	GameContentLinks struct {
		ChocoboRaceAbility struct {
			ChocoboRaceAbilityType []interface{} `json:"ChocoboRaceAbilityType,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	IsActive int `json:"IsActive,omitempty"`
}
