// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type FCRights struct {
	Description_fr string `json:"Description_fr,omitempty"`
	FCRankTarget string `json:"FCRankTarget,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Description_en string `json:"Description_en,omitempty"`
	Description_ja string `json:"Description_ja,omitempty"`
	FCRank struct {
		ID int `json:"ID,omitempty"`
	}
	Name_fr string `json:"Name_fr,omitempty"`
	Description string `json:"Description,omitempty"`
	Description_de string `json:"Description_de,omitempty"`
	Icon string `json:"Icon,omitempty"`
	IconID int `json:"IconID,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	Url string `json:"Url,omitempty"`
	FCRankTargetID int `json:"FCRankTargetID,omitempty"`
	Name string `json:"Name,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
}
