// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type Companion struct {
	Defense int `json:"Defense,omitempty"`
	Description_en string `json:"Description_en,omitempty"`
	SkillCost int `json:"SkillCost,omitempty"`
	Url string `json:"Url,omitempty"`
	DescriptionEnhanced_en string `json:"DescriptionEnhanced_en,omitempty"`
	Description_fr string `json:"Description_fr,omitempty"`
	GamePatch struct {
		ExVersion int `json:"ExVersion,omitempty"`
		Name_cn string `json:"Name_cn,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		ID int `json:"ID,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		Url string `json:"Url,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_kr string `json:"Name_kr,omitempty"`
		ReleaseDate int `json:"ReleaseDate,omitempty"`
		Banner string `json:"Banner,omitempty"`
		IsExpansion bool `json:"IsExpansion,omitempty"`
		Version int `json:"Version,omitempty"`
	}
	SpecialActionName_de string `json:"SpecialActionName_de,omitempty"`
	Tooltip string `json:"Tooltip,omitempty"`
	MinionRace struct {
		Name_ja string `json:"Name_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
	}
	Plural string `json:"Plural,omitempty"`
	Rarity int `json:"Rarity,omitempty"`
	Cost int `json:"Cost,omitempty"`
	DescriptionEnhanced_de string `json:"DescriptionEnhanced_de,omitempty"`
	DescriptionEnhanced_fr string `json:"DescriptionEnhanced_fr,omitempty"`
	IconID int `json:"IconID,omitempty"`
	IconSmall string `json:"IconSmall,omitempty"`
	SpecialActionDescription_de string `json:"SpecialActionDescription_de,omitempty"`
	SpecialActionDescription_fr string `json:"SpecialActionDescription_fr,omitempty"`
	StartsWithVowel int `json:"StartsWithVowel,omitempty"`
	Tooltip_fr string `json:"Tooltip_fr,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	StrengthShield int `json:"StrengthShield,omitempty"`
	MinionRaceTarget string `json:"MinionRaceTarget,omitempty"`
	MinionSkillTypeTargetID int `json:"MinionSkillTypeTargetID,omitempty"`
	SpecialActionName_fr string `json:"SpecialActionName_fr,omitempty"`
	Speed int `json:"Speed,omitempty"`
	SpecialActionDescription_en string `json:"SpecialActionDescription_en,omitempty"`
	SpecialActionName string `json:"SpecialActionName,omitempty"`
	SpecialActionName_en string `json:"SpecialActionName_en,omitempty"`
	BehaviorTargetID int `json:"BehaviorTargetID,omitempty"`
	Description_de string `json:"Description_de,omitempty"`
	Icon string `json:"Icon,omitempty"`
	MinionSkillTypeTarget string `json:"MinionSkillTypeTarget,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Tooltip_en string `json:"Tooltip_en,omitempty"`
	Description_ja string `json:"Description_ja,omitempty"`
	Name string `json:"Name,omitempty"`
	Plural_en string `json:"Plural_en,omitempty"`
	Plural_fr string `json:"Plural_fr,omitempty"`
	StrengthArcana int `json:"StrengthArcana,omitempty"`
	Description string `json:"Description,omitempty"`
	SpecialActionDescription string `json:"SpecialActionDescription,omitempty"`
	SpecialActionDescription_ja string `json:"SpecialActionDescription_ja,omitempty"`
	SpecialActionName_ja string `json:"SpecialActionName_ja,omitempty"`
	StrengthGate int `json:"StrengthGate,omitempty"`
	Behavior struct {
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		Name string `json:"Name,omitempty"`
	}
	Name_en string `json:"Name_en,omitempty"`
	SkillAngle int `json:"SkillAngle,omitempty"`
	MinionSkillType struct {
		Name_ja string `json:"Name_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
	}
	Plural_de string `json:"Plural_de,omitempty"`
	Attack int `json:"Attack,omitempty"`
	BehaviorTarget string `json:"BehaviorTarget,omitempty"`
	DescriptionEnhanced string `json:"DescriptionEnhanced,omitempty"`
	DescriptionEnhanced_ja string `json:"DescriptionEnhanced_ja,omitempty"`
	Tooltip_ja string `json:"Tooltip_ja,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	HasAreaAttack int `json:"HasAreaAttack,omitempty"`
	MinionRaceTargetID int `json:"MinionRaceTargetID,omitempty"`
	Plural_ja string `json:"Plural_ja,omitempty"`
	Tooltip_de string `json:"Tooltip_de,omitempty"`
	HP int `json:"HP,omitempty"`
	ID int `json:"ID,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	StrengthEye int `json:"StrengthEye,omitempty"`
}
