// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ContentsNote struct {
	RequiredAmount int `json:"RequiredAmount,omitempty"`
	Url string `json:"Url,omitempty"`
	ContentType struct {
		ID int `json:"ID,omitempty"`
		Type string `json:"Type,omitempty"`
	}
	ContentTypeTarget string `json:"ContentTypeTarget,omitempty"`
	ContentTypeTargetID int `json:"ContentTypeTargetID,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
}
