// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ParamGrow struct {
	LevelModifier int `json:"LevelModifier,omitempty"`
	QuestExpModifier int `json:"QuestExpModifier,omitempty"`
	AdditionalActions int `json:"AdditionalActions,omitempty"`
	BaseSpeed int `json:"BaseSpeed,omitempty"`
	ExpToNext int `json:"ExpToNext,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	HuntingLogExpReward int `json:"HuntingLogExpReward,omitempty"`
	HpModifier int `json:"HpModifier,omitempty"`
	ID int `json:"ID,omitempty"`
	MpModifier int `json:"MpModifier,omitempty"`
	Url string `json:"Url,omitempty"`
}
