// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type SkyIsland2Mission struct {
	ID int `json:"ID,omitempty"`
	ImageID int `json:"ImageID,omitempty"`
	Objective1 struct {
		EObjTarget string `json:"EObjTarget,omitempty"`
		EObjTargetID int `json:"EObjTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		Objective string `json:"Objective,omitempty"`
		Objective_en string `json:"Objective_en,omitempty"`
		Objective_ja string `json:"Objective_ja,omitempty"`
		Range int `json:"Range,omitempty"`
		EObj int `json:"EObj,omitempty"`
		TypeTarget string `json:"TypeTarget,omitempty"`
		Type struct {
			Type int `json:"Type,omitempty"`
			ID int `json:"ID,omitempty"`
		}
		Objective_fr string `json:"Objective_fr,omitempty"`
		TypeTargetID int `json:"TypeTargetID,omitempty"`
		Objective_de string `json:"Objective_de,omitempty"`
	}
	RequiredAmount2 int `json:"RequiredAmount2,omitempty"`
	Objective3 struct {
		EObj int `json:"EObj,omitempty"`
		Objective string `json:"Objective,omitempty"`
		TypeTargetID int `json:"TypeTargetID,omitempty"`
		Type struct {
			ID int `json:"ID,omitempty"`
			Type int `json:"Type,omitempty"`
		}
		TypeTarget string `json:"TypeTarget,omitempty"`
		ID int `json:"ID,omitempty"`
		Objective_de string `json:"Objective_de,omitempty"`
		Objective_en string `json:"Objective_en,omitempty"`
		Objective_fr string `json:"Objective_fr,omitempty"`
		Objective_ja string `json:"Objective_ja,omitempty"`
		Range int `json:"Range,omitempty"`
	}
	Objective3TargetID int `json:"Objective3TargetID,omitempty"`
	RequiredAmount1 int `json:"RequiredAmount1,omitempty"`
	Image string `json:"Image,omitempty"`
	Item1Target string `json:"Item1Target,omitempty"`
	Objective1Target string `json:"Objective1Target,omitempty"`
	Objective1TargetID int `json:"Objective1TargetID,omitempty"`
	Objective3Target string `json:"Objective3Target,omitempty"`
	Url string `json:"Url,omitempty"`
	Item2 int `json:"Item2,omitempty"`
	Objective2 struct {
		Objective_en string `json:"Objective_en,omitempty"`
		Objective_fr string `json:"Objective_fr,omitempty"`
		Objective_ja string `json:"Objective_ja,omitempty"`
		Range int `json:"Range,omitempty"`
		Objective string `json:"Objective,omitempty"`
		Objective_de string `json:"Objective_de,omitempty"`
		Type struct {
			ID int `json:"ID,omitempty"`
			Type int `json:"Type,omitempty"`
		}
		TypeTarget string `json:"TypeTarget,omitempty"`
		TypeTargetID int `json:"TypeTargetID,omitempty"`
		EObj int `json:"EObj,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	Objective2Target string `json:"Objective2Target,omitempty"`
	Objective2TargetID int `json:"Objective2TargetID,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	Item1 struct {
		ActionTarget string `json:"ActionTarget,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		Plural string `json:"Plural,omitempty"`
		Plural_ja string `json:"Plural_ja,omitempty"`
		Singular string `json:"Singular,omitempty"`
		StartsWithVowel int `json:"StartsWithVowel,omitempty"`
		ID int `json:"ID,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Quest int `json:"Quest,omitempty"`
		Rarity int `json:"Rarity,omitempty"`
		Singular_en string `json:"Singular_en,omitempty"`
		Singular_fr string `json:"Singular_fr,omitempty"`
		StackSize int `json:"StackSize,omitempty"`
		Action struct {
			CanTargetFriendly int `json:"CanTargetFriendly,omitempty"`
			CanTargetHostile int `json:"CanTargetHostile,omitempty"`
			Cast100ms int `json:"Cast100ms,omitempty"`
			CastType int `json:"CastType,omitempty"`
			IconID int `json:"IconID,omitempty"`
			Name_fr string `json:"Name_fr,omitempty"`
			Range int `json:"Range,omitempty"`
			XAxisModifier int `json:"XAxisModifier,omitempty"`
			ClassJobCategory int `json:"ClassJobCategory,omitempty"`
			Name_ja string `json:"Name_ja,omitempty"`
			ActionCategory int `json:"ActionCategory,omitempty"`
			AnimationEnd int `json:"AnimationEnd,omitempty"`
			ClassJob int `json:"ClassJob,omitempty"`
			Name_de string `json:"Name_de,omitempty"`
			Omen int `json:"Omen,omitempty"`
			StatusGainSelf int `json:"StatusGainSelf,omitempty"`
			ActionCombo int `json:"ActionCombo,omitempty"`
			ActionTimelineHit int `json:"ActionTimelineHit,omitempty"`
			CanTargetDead int `json:"CanTargetDead,omitempty"`
			CanTargetParty int `json:"CanTargetParty,omitempty"`
			CooldownGroup int `json:"CooldownGroup,omitempty"`
			CostType int `json:"CostType,omitempty"`
			EffectRange int `json:"EffectRange,omitempty"`
			IsRoleAction int `json:"IsRoleAction,omitempty"`
			Name string `json:"Name,omitempty"`
			Name_en string `json:"Name_en,omitempty"`
			Recast100ms int `json:"Recast100ms,omitempty"`
			TargetArea int `json:"TargetArea,omitempty"`
			AnimationStart int `json:"AnimationStart,omitempty"`
			AttackType int `json:"AttackType,omitempty"`
			ClassJobLevel int `json:"ClassJobLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			VFX int `json:"VFX,omitempty"`
			ActionData int `json:"ActionData,omitempty"`
			Icon string `json:"Icon,omitempty"`
			AffectsPosition int `json:"AffectsPosition,omitempty"`
			IsPvP int `json:"IsPvP,omitempty"`
			ActionProcStatus int `json:"ActionProcStatus,omitempty"`
			Aspect int `json:"Aspect,omitempty"`
			CanTargetSelf int `json:"CanTargetSelf,omitempty"`
			Cost int `json:"Cost,omitempty"`
			PreservesCombo int `json:"PreservesCombo,omitempty"`
		}
		IconID int `json:"IconID,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Plural_de string `json:"Plural_de,omitempty"`
		ActionTargetID int `json:"ActionTargetID,omitempty"`
		CastTime int `json:"CastTime,omitempty"`
		Icon string `json:"Icon,omitempty"`
		Plural_en string `json:"Plural_en,omitempty"`
		Plural_fr string `json:"Plural_fr,omitempty"`
		Singular_de string `json:"Singular_de,omitempty"`
		Singular_ja string `json:"Singular_ja,omitempty"`
	}
	Item1TargetID int `json:"Item1TargetID,omitempty"`
}
