// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type RecipeLevelTable struct {
	Difficulty int `json:"Difficulty,omitempty"`
	Durability int `json:"Durability,omitempty"`
	ID int `json:"ID,omitempty"`
	Quality int `json:"Quality,omitempty"`
	ClassJobLevel int `json:"ClassJobLevel,omitempty"`
	GameContentLinks struct {
		Recipe struct {
			RecipeLevelTable []interface{} `json:"RecipeLevelTable,omitempty"`
		}
	}
	Stars int `json:"Stars,omitempty"`
	SuggestedCraftsmanship int `json:"SuggestedCraftsmanship,omitempty"`
	Url string `json:"Url,omitempty"`
}
