// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type RecommendContents struct {
	Level struct {
		TerritoryTargetID int `json:"TerritoryTargetID,omitempty"`
		X int `json:"X,omitempty"`
		Z int `json:"Z,omitempty"`
		EventId int `json:"EventId,omitempty"`
		MapTargetID int `json:"MapTargetID,omitempty"`
		Radius int `json:"Radius,omitempty"`
		TerritoryTarget string `json:"TerritoryTarget,omitempty"`
		ObjectKey int `json:"ObjectKey,omitempty"`
		Y int `json:"Y,omitempty"`
		Map struct {
			OffsetY int `json:"OffsetY,omitempty"`
			ID int `json:"ID,omitempty"`
			OffsetX int `json:"OffsetX,omitempty"`
			Hierarchy int `json:"Hierarchy,omitempty"`
			PlaceName int `json:"PlaceName,omitempty"`
			DiscoveryArrayByte int `json:"DiscoveryArrayByte,omitempty"`
			DiscoveryIndex int `json:"DiscoveryIndex,omitempty"`
			TerritoryType int `json:"TerritoryType,omitempty"`
			MapFilenameId string `json:"MapFilenameId,omitempty"`
			PlaceNameSub int `json:"PlaceNameSub,omitempty"`
			PlaceNameRegion int `json:"PlaceNameRegion,omitempty"`
			SizeFactor int `json:"SizeFactor,omitempty"`
			MapFilename string `json:"MapFilename,omitempty"`
			MapMarkerRange int `json:"MapMarkerRange,omitempty"`
		}
		Territory struct {
			ArrayEventHandler int `json:"ArrayEventHandler,omitempty"`
			Bg string `json:"Bg,omitempty"`
			Map int `json:"Map,omitempty"`
			Name string `json:"Name,omitempty"`
			Name_en string `json:"Name_en,omitempty"`
			WeatherRate int `json:"WeatherRate,omitempty"`
			Aetheryte int `json:"Aetheryte,omitempty"`
			Bg_en string `json:"Bg_en,omitempty"`
			ID int `json:"ID,omitempty"`
			PlaceName int `json:"PlaceName,omitempty"`
			PlaceNameRegion int `json:"PlaceNameRegion,omitempty"`
			PlaceNameZone int `json:"PlaceNameZone,omitempty"`
			TerritoryIntendedUse int `json:"TerritoryIntendedUse,omitempty"`
		}
		Type int `json:"Type,omitempty"`
		Yaw int `json:"Yaw,omitempty"`
		ID int `json:"ID,omitempty"`
		MapTarget string `json:"MapTarget,omitempty"`
	}
	LevelTarget string `json:"LevelTarget,omitempty"`
	LevelTargetID int `json:"LevelTargetID,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
}
