// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type CompanyCraftType struct {
	Name_ja string `json:"Name_ja,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks struct {
		CompanyCraftDraftCategory struct {
			CompanyCraftType1 []interface{} `json:"CompanyCraftType1,omitempty"`
		}
		CompanyCraftPart struct {
			CompanyCraftType []interface{} `json:"CompanyCraftType,omitempty"`
		}
		CompanyCraftSequence struct {
			CompanyCraftType []interface{} `json:"CompanyCraftType,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	Name string `json:"Name,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
}
