// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ContentNpcTalk struct {
	ID int `json:"ID,omitempty"`
	ContentTalk1TargetID int `json:"ContentTalk1TargetID,omitempty"`
	ContentTalk4 int `json:"ContentTalk4,omitempty"`
	ContentTalk5 int `json:"ContentTalk5,omitempty"`
	ContentTalk7 int `json:"ContentTalk7,omitempty"`
	ContentTalk3TargetID int `json:"ContentTalk3TargetID,omitempty"`
	Url string `json:"Url,omitempty"`
	ContentTalk0Target string `json:"ContentTalk0Target,omitempty"`
	ContentTalk0TargetID int `json:"ContentTalk0TargetID,omitempty"`
	ContentTalk2Target string `json:"ContentTalk2Target,omitempty"`
	ContentTalk3 struct {
		Text_en string `json:"Text_en,omitempty"`
		Text_fr string `json:"Text_fr,omitempty"`
		ID int `json:"ID,omitempty"`
		Text string `json:"Text,omitempty"`
		Text_de string `json:"Text_de,omitempty"`
		Text_ja string `json:"Text_ja,omitempty"`
		ContentTalkParam struct {
			ID int `json:"ID,omitempty"`
			Param int `json:"Param,omitempty"`
			TestAction int `json:"TestAction,omitempty"`
		}
		ContentTalkParamTarget string `json:"ContentTalkParamTarget,omitempty"`
		ContentTalkParamTargetID int `json:"ContentTalkParamTargetID,omitempty"`
	}
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ContentTalk0 struct {
		ContentTalkParam struct {
			ID int `json:"ID,omitempty"`
			Param int `json:"Param,omitempty"`
			TestAction int `json:"TestAction,omitempty"`
		}
		ID int `json:"ID,omitempty"`
		Text_en string `json:"Text_en,omitempty"`
		Text_fr string `json:"Text_fr,omitempty"`
		ContentTalkParamTarget string `json:"ContentTalkParamTarget,omitempty"`
		ContentTalkParamTargetID int `json:"ContentTalkParamTargetID,omitempty"`
		Text string `json:"Text,omitempty"`
		Text_de string `json:"Text_de,omitempty"`
		Text_ja string `json:"Text_ja,omitempty"`
	}
	ContentTalk1Target string `json:"ContentTalk1Target,omitempty"`
	ContentTalk2TargetID int `json:"ContentTalk2TargetID,omitempty"`
	ContentTalk3Target string `json:"ContentTalk3Target,omitempty"`
	ContentTalk1 struct {
		Text_en string `json:"Text_en,omitempty"`
		Text_fr string `json:"Text_fr,omitempty"`
		Text_ja string `json:"Text_ja,omitempty"`
		ContentTalkParam struct {
			ID int `json:"ID,omitempty"`
			Param int `json:"Param,omitempty"`
			TestAction int `json:"TestAction,omitempty"`
		}
		ContentTalkParamTargetID int `json:"ContentTalkParamTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		Text_de string `json:"Text_de,omitempty"`
		ContentTalkParamTarget string `json:"ContentTalkParamTarget,omitempty"`
		Text string `json:"Text,omitempty"`
	}
	ContentTalk2 struct {
		Text_fr string `json:"Text_fr,omitempty"`
		Text_ja string `json:"Text_ja,omitempty"`
		ContentTalkParam struct {
			ID int `json:"ID,omitempty"`
			Param int `json:"Param,omitempty"`
			TestAction int `json:"TestAction,omitempty"`
		}
		ContentTalkParamTargetID int `json:"ContentTalkParamTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		Text string `json:"Text,omitempty"`
		Text_de string `json:"Text_de,omitempty"`
		ContentTalkParamTarget string `json:"ContentTalkParamTarget,omitempty"`
		Text_en string `json:"Text_en,omitempty"`
	}
	ContentTalk6 int `json:"ContentTalk6,omitempty"`
}
