// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ContentMemberType struct {
	GameContentLinks struct {
		ContentFinderCondition struct {
			ContentMemberType []interface{} `json:"ContentMemberType,omitempty"`
		}
		ContentRoulette struct {
			ContentMemberType []interface{} `json:"ContentMemberType,omitempty"`
		}
	}
	HealersPerParty int `json:"HealersPerParty,omitempty"`
	ID int `json:"ID,omitempty"`
	MeleesPerParty int `json:"MeleesPerParty,omitempty"`
	RangedPerParty int `json:"RangedPerParty,omitempty"`
	TanksPerParty int `json:"TanksPerParty,omitempty"`
	Url string `json:"Url,omitempty"`
}
