// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type BuddySkill struct {
	IsActive int `json:"IsActive,omitempty"`
	Url string `json:"Url,omitempty"`
	Attacker int `json:"Attacker,omitempty"`
	BuddyLevel int `json:"BuddyLevel,omitempty"`
	Defender int `json:"Defender,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	Healer int `json:"Healer,omitempty"`
	ID int `json:"ID,omitempty"`
}
