// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type BuddyAction struct {
	Name string `json:"Name,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Url string `json:"Url,omitempty"`
	Description_de string `json:"Description_de,omitempty"`
	Description_fr string `json:"Description_fr,omitempty"`
	Icon string `json:"Icon,omitempty"`
	Description string `json:"Description,omitempty"`
	Description_en string `json:"Description_en,omitempty"`
	IconStatusID int `json:"IconStatusID,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	IconID int `json:"IconID,omitempty"`
	IconStatus string `json:"IconStatus,omitempty"`
	Description_ja string `json:"Description_ja,omitempty"`
	ID int `json:"ID,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
}
