// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type SkyIsland2MissionDetail struct {
	Url string `json:"Url,omitempty"`
	TypeTargetID int `json:"TypeTargetID,omitempty"`
	ID int `json:"ID,omitempty"`
	Objective_en string `json:"Objective_en,omitempty"`
	Type struct {
		ID int `json:"ID,omitempty"`
		Type int `json:"Type,omitempty"`
	}
	GameContentLinks struct {
		SkyIsland2Mission struct {
			Objective3 []interface{} `json:"Objective3,omitempty"`
		}
	}
	EObjTarget string `json:"EObjTarget,omitempty"`
	EObjTargetID int `json:"EObjTargetID,omitempty"`
	Objective_fr string `json:"Objective_fr,omitempty"`
	Objective_ja string `json:"Objective_ja,omitempty"`
	TypeTarget string `json:"TypeTarget,omitempty"`
	EObj struct {
		Singular string `json:"Singular,omitempty"`
		Singular_de string `json:"Singular_de,omitempty"`
		Singular_en string `json:"Singular_en,omitempty"`
		Singular_fr string `json:"Singular_fr,omitempty"`
		Singular_ja string `json:"Singular_ja,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	Objective_de string `json:"Objective_de,omitempty"`
	Range int `json:"Range,omitempty"`
	Objective string `json:"Objective,omitempty"`
}
