// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ChocoboTaxi struct {
	LocationTargetID int `json:"LocationTargetID,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	Location struct {
		ID int `json:"ID,omitempty"`
		PlaceName string `json:"PlaceName,omitempty"`
		PlaceName_de string `json:"PlaceName_de,omitempty"`
		PlaceName_en string `json:"PlaceName_en,omitempty"`
		PlaceName_fr string `json:"PlaceName_fr,omitempty"`
		PlaceName_ja string `json:"PlaceName_ja,omitempty"`
	}
	LocationTarget string `json:"LocationTarget,omitempty"`
}
