// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ItemUICategory struct {
	ID int `json:"ID,omitempty"`
	Icon string `json:"Icon,omitempty"`
	IconID int `json:"IconID,omitempty"`
	Name string `json:"Name,omitempty"`
	OrderMinor int `json:"OrderMinor,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks struct {
		Item struct {
			ItemUICategory []interface{} `json:"ItemUICategory,omitempty"`
		}
	}
	Name_de string `json:"Name_de,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	OrderMajor int `json:"OrderMajor,omitempty"`
}
