// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type BacklightColor struct {
	Color int `json:"Color,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	Url string `json:"Url,omitempty"`
}
