// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type Tribe struct {
	MND int `json:"MND,omitempty"`
	INT int `json:"INT,omitempty"`
	ID int `json:"ID,omitempty"`
	Url string `json:"Url,omitempty"`
	DEX int `json:"DEX,omitempty"`
	NameFemale_en string `json:"NameFemale_en,omitempty"`
	NameFemale_ja string `json:"NameFemale_ja,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	NameFemale string `json:"NameFemale,omitempty"`
	Name string `json:"Name,omitempty"`
	NameFemale_de string `json:"NameFemale_de,omitempty"`
	NameFemale_fr string `json:"NameFemale_fr,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	PIE int `json:"PIE,omitempty"`
	STR int `json:"STR,omitempty"`
	GameContentLinks struct {
		BNpcCustomize struct {
			Tribe []interface{} `json:"Tribe,omitempty"`
		}
		CharaMakeType struct {
			Tribe []interface{} `json:"Tribe,omitempty"`
		}
		ENpcBase struct {
			Tribe []interface{} `json:"Tribe,omitempty"`
		}
		HairMakeType struct {
			Tribe []interface{} `json:"Tribe,omitempty"`
		}
	}
	VIT int `json:"VIT,omitempty"`
}
