// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type CompleteJournalCategory struct {
	FirstQuest struct {
		Cutscene10 int `json:"Cutscene10,omitempty"`
		Cutscene18 int `json:"Cutscene18,omitempty"`
		Cutscene19 int `json:"Cutscene19,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		Cutscene0TargetID int `json:"Cutscene0TargetID,omitempty"`
		Cutscene2 int `json:"Cutscene2,omitempty"`
		Cutscene20 int `json:"Cutscene20,omitempty"`
		Cutscene4 int `json:"Cutscene4,omitempty"`
		Icon string `json:"Icon,omitempty"`
		Cutscene0Target string `json:"Cutscene0Target,omitempty"`
		Cutscene13 int `json:"Cutscene13,omitempty"`
		Cutscene14 int `json:"Cutscene14,omitempty"`
		Cutscene21 int `json:"Cutscene21,omitempty"`
		Cutscene22 int `json:"Cutscene22,omitempty"`
		Cutscene0 struct {
			ID int `json:"ID,omitempty"`
			Path string `json:"Path,omitempty"`
			Path_en string `json:"Path_en,omitempty"`
		}
		Name_en string `json:"Name_en,omitempty"`
		Cutscene1Target string `json:"Cutscene1Target,omitempty"`
		Cutscene3 int `json:"Cutscene3,omitempty"`
		Cutscene6 int `json:"Cutscene6,omitempty"`
		ID int `json:"ID,omitempty"`
		IconID int `json:"IconID,omitempty"`
		Cutscene1 struct {
			ID int `json:"ID,omitempty"`
			Path string `json:"Path,omitempty"`
			Path_en string `json:"Path_en,omitempty"`
		}
		Cutscene11 int `json:"Cutscene11,omitempty"`
		Cutscene16 int `json:"Cutscene16,omitempty"`
		Cutscene23 int `json:"Cutscene23,omitempty"`
		Cutscene5 int `json:"Cutscene5,omitempty"`
		Cutscene17 int `json:"Cutscene17,omitempty"`
		Cutscene1TargetID int `json:"Cutscene1TargetID,omitempty"`
		Cutscene9 int `json:"Cutscene9,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		RequiredLevel int `json:"RequiredLevel,omitempty"`
		Cutscene12 int `json:"Cutscene12,omitempty"`
		Cutscene15 int `json:"Cutscene15,omitempty"`
		Cutscene7 int `json:"Cutscene7,omitempty"`
		Cutscene8 int `json:"Cutscene8,omitempty"`
		Name string `json:"Name,omitempty"`
	}
	ID int `json:"ID,omitempty"`
	LastQuest struct {
		Cutscene3Target string `json:"Cutscene3Target,omitempty"`
		Cutscene4Target string `json:"Cutscene4Target,omitempty"`
		Cutscene6 struct {
			ID int `json:"ID,omitempty"`
			Path string `json:"Path,omitempty"`
			Path_en string `json:"Path_en,omitempty"`
		}
		Cutscene22 int `json:"Cutscene22,omitempty"`
		Cutscene10 struct {
			Path string `json:"Path,omitempty"`
			Path_en string `json:"Path_en,omitempty"`
			ID int `json:"ID,omitempty"`
		}
		Cutscene14 int `json:"Cutscene14,omitempty"`
		Cutscene23 int `json:"Cutscene23,omitempty"`
		Cutscene3 struct {
			ID int `json:"ID,omitempty"`
			Path string `json:"Path,omitempty"`
			Path_en string `json:"Path_en,omitempty"`
		}
		Cutscene4 struct {
			ID int `json:"ID,omitempty"`
			Path string `json:"Path,omitempty"`
			Path_en string `json:"Path_en,omitempty"`
		}
		Cutscene5 struct {
			ID int `json:"ID,omitempty"`
			Path string `json:"Path,omitempty"`
			Path_en string `json:"Path_en,omitempty"`
		}
		Cutscene6Target string `json:"Cutscene6Target,omitempty"`
		Cutscene6TargetID int `json:"Cutscene6TargetID,omitempty"`
		Cutscene0 struct {
			Path_en string `json:"Path_en,omitempty"`
			ID int `json:"ID,omitempty"`
			Path string `json:"Path,omitempty"`
		}
		Cutscene12Target string `json:"Cutscene12Target,omitempty"`
		Cutscene3TargetID int `json:"Cutscene3TargetID,omitempty"`
		Cutscene9Target string `json:"Cutscene9Target,omitempty"`
		RequiredLevel int `json:"RequiredLevel,omitempty"`
		Cutscene0Target string `json:"Cutscene0Target,omitempty"`
		Cutscene12TargetID int `json:"Cutscene12TargetID,omitempty"`
		Cutscene19 int `json:"Cutscene19,omitempty"`
		Cutscene2 struct {
			ID int `json:"ID,omitempty"`
			Path string `json:"Path,omitempty"`
			Path_en string `json:"Path_en,omitempty"`
		}
		Cutscene10Target string `json:"Cutscene10Target,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		Cutscene5TargetID int `json:"Cutscene5TargetID,omitempty"`
		Name string `json:"Name,omitempty"`
		Cutscene21 int `json:"Cutscene21,omitempty"`
		Cutscene5Target string `json:"Cutscene5Target,omitempty"`
		Cutscene18 int `json:"Cutscene18,omitempty"`
		Cutscene2TargetID int `json:"Cutscene2TargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Cutscene13 int `json:"Cutscene13,omitempty"`
		Cutscene12 struct {
			ID int `json:"ID,omitempty"`
			Path string `json:"Path,omitempty"`
			Path_en string `json:"Path_en,omitempty"`
		}
		Cutscene1TargetID int `json:"Cutscene1TargetID,omitempty"`
		Cutscene8Target string `json:"Cutscene8Target,omitempty"`
		Cutscene9 struct {
			ID int `json:"ID,omitempty"`
			Path string `json:"Path,omitempty"`
			Path_en string `json:"Path_en,omitempty"`
		}
		Icon string `json:"Icon,omitempty"`
		Cutscene0TargetID int `json:"Cutscene0TargetID,omitempty"`
		Cutscene11TargetID int `json:"Cutscene11TargetID,omitempty"`
		Cutscene7TargetID int `json:"Cutscene7TargetID,omitempty"`
		Cutscene8TargetID int `json:"Cutscene8TargetID,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Cutscene10TargetID int `json:"Cutscene10TargetID,omitempty"`
		Cutscene1Target string `json:"Cutscene1Target,omitempty"`
		Cutscene7Target string `json:"Cutscene7Target,omitempty"`
		Cutscene9TargetID int `json:"Cutscene9TargetID,omitempty"`
		Cutscene1 struct {
			Path_en string `json:"Path_en,omitempty"`
			ID int `json:"ID,omitempty"`
			Path string `json:"Path,omitempty"`
		}
		Cutscene15 int `json:"Cutscene15,omitempty"`
		Cutscene17 int `json:"Cutscene17,omitempty"`
		Cutscene20 int `json:"Cutscene20,omitempty"`
		Cutscene2Target string `json:"Cutscene2Target,omitempty"`
		Cutscene4TargetID int `json:"Cutscene4TargetID,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Cutscene11Target string `json:"Cutscene11Target,omitempty"`
		Cutscene7 struct {
			Path string `json:"Path,omitempty"`
			Path_en string `json:"Path_en,omitempty"`
			ID int `json:"ID,omitempty"`
		}
		Cutscene16 int `json:"Cutscene16,omitempty"`
		Cutscene8 struct {
			ID int `json:"ID,omitempty"`
			Path string `json:"Path,omitempty"`
			Path_en string `json:"Path_en,omitempty"`
		}
		IconID int `json:"IconID,omitempty"`
		Cutscene11 struct {
			ID int `json:"ID,omitempty"`
			Path string `json:"Path,omitempty"`
			Path_en string `json:"Path_en,omitempty"`
		}
	}
	LastQuestTargetID int `json:"LastQuestTargetID,omitempty"`
	Url string `json:"Url,omitempty"`
	FirstQuestTarget string `json:"FirstQuestTarget,omitempty"`
	FirstQuestTargetID int `json:"FirstQuestTargetID,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	LastQuestTarget string `json:"LastQuestTarget,omitempty"`
}
