// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type GatheringPointName struct {
	Plural_de string `json:"Plural_de,omitempty"`
	Plural_fr string `json:"Plural_fr,omitempty"`
	ID int `json:"ID,omitempty"`
	Plural string `json:"Plural,omitempty"`
	Singular_en string `json:"Singular_en,omitempty"`
	Singular_ja string `json:"Singular_ja,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	Plural_en string `json:"Plural_en,omitempty"`
	Singular_fr string `json:"Singular_fr,omitempty"`
	StartsWithVowel int `json:"StartsWithVowel,omitempty"`
	Plural_ja string `json:"Plural_ja,omitempty"`
	Singular string `json:"Singular,omitempty"`
	Singular_de string `json:"Singular_de,omitempty"`
	Url string `json:"Url,omitempty"`
}
