// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ModelState struct {
	EndTarget string `json:"EndTarget,omitempty"`
	EndTargetID int `json:"EndTargetID,omitempty"`
	ID int `json:"ID,omitempty"`
	StartTargetID int `json:"StartTargetID,omitempty"`
	End struct {
		ID int `json:"ID,omitempty"`
		Key string `json:"Key,omitempty"`
		Key_en string `json:"Key_en,omitempty"`
	}
	Start struct {
		Key_en string `json:"Key_en,omitempty"`
		ID int `json:"ID,omitempty"`
		Key string `json:"Key,omitempty"`
	}
	StartTarget string `json:"StartTarget,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
}
