// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type JournalCategory struct {
	Name_en string `json:"Name_en,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	GameContentLinks struct {
		JournalGenre struct {
			JournalCategory []interface{} `json:"JournalCategory,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	JournalSection struct {
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
	}
	JournalSectionTarget string `json:"JournalSectionTarget,omitempty"`
	Name string `json:"Name,omitempty"`
	JournalSectionTargetID int `json:"JournalSectionTargetID,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	Url string `json:"Url,omitempty"`
}
