// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type PartyContentCutscene struct {
	Cutscene struct {
		ID int `json:"ID,omitempty"`
		Path string `json:"Path,omitempty"`
		Path_en string `json:"Path_en,omitempty"`
	}
	CutsceneTarget string `json:"CutsceneTarget,omitempty"`
	CutsceneTargetID int `json:"CutsceneTargetID,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	Url string `json:"Url,omitempty"`
}
