// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ActionParam struct {
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	Name int `json:"Name,omitempty"`
	Url string `json:"Url,omitempty"`
}
