// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type WeeklyLotBonus struct {
	WeeklyLotBonusThreshold12TargetID int `json:"WeeklyLotBonusThreshold12TargetID,omitempty"`
	WeeklyLotBonusThreshold18 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold2 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold24TargetID int `json:"WeeklyLotBonusThreshold24TargetID,omitempty"`
	WeeklyLotBonusThreshold25 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold2TargetID int `json:"WeeklyLotBonusThreshold2TargetID,omitempty"`
	WeeklyLotBonusThreshold19 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold13 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold13TargetID int `json:"WeeklyLotBonusThreshold13TargetID,omitempty"`
	WeeklyLotBonusThreshold14TargetID int `json:"WeeklyLotBonusThreshold14TargetID,omitempty"`
	WeeklyLotBonusThreshold28 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold4TargetID int `json:"WeeklyLotBonusThreshold4TargetID,omitempty"`
	WeeklyLotBonusThreshold7Target string `json:"WeeklyLotBonusThreshold7Target,omitempty"`
	WeeklyLotBonusThreshold8Target string `json:"WeeklyLotBonusThreshold8Target,omitempty"`
	WeeklyLotBonusThreshold0 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold0TargetID int `json:"WeeklyLotBonusThreshold0TargetID,omitempty"`
	WeeklyLotBonusThreshold14 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold22TargetID int `json:"WeeklyLotBonusThreshold22TargetID,omitempty"`
	WeeklyLotBonusThreshold23Target string `json:"WeeklyLotBonusThreshold23Target,omitempty"`
	WeeklyLotBonusThreshold9Target string `json:"WeeklyLotBonusThreshold9Target,omitempty"`
	WeeklyLotBonusThreshold0Target string `json:"WeeklyLotBonusThreshold0Target,omitempty"`
	WeeklyLotBonusThreshold11Target string `json:"WeeklyLotBonusThreshold11Target,omitempty"`
	WeeklyLotBonusThreshold13Target string `json:"WeeklyLotBonusThreshold13Target,omitempty"`
	WeeklyLotBonusThreshold15Target string `json:"WeeklyLotBonusThreshold15Target,omitempty"`
	WeeklyLotBonusThreshold1TargetID int `json:"WeeklyLotBonusThreshold1TargetID,omitempty"`
	WeeklyLotBonusThreshold30TargetID int `json:"WeeklyLotBonusThreshold30TargetID,omitempty"`
	WeeklyLotBonusThreshold5 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold17Target string `json:"WeeklyLotBonusThreshold17Target,omitempty"`
	WeeklyLotBonusThreshold19TargetID int `json:"WeeklyLotBonusThreshold19TargetID,omitempty"`
	WeeklyLotBonusThreshold20 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold25Target string `json:"WeeklyLotBonusThreshold25Target,omitempty"`
	WeeklyLotBonusThreshold3TargetID int `json:"WeeklyLotBonusThreshold3TargetID,omitempty"`
	ID int `json:"ID,omitempty"`
	WeeklyLotBonusThreshold18Target string `json:"WeeklyLotBonusThreshold18Target,omitempty"`
	WeeklyLotBonusThreshold21 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold28TargetID int `json:"WeeklyLotBonusThreshold28TargetID,omitempty"`
	WeeklyLotBonusThreshold29Target string `json:"WeeklyLotBonusThreshold29Target,omitempty"`
	WeeklyLotBonusThreshold4Target string `json:"WeeklyLotBonusThreshold4Target,omitempty"`
	WeeklyLotBonusThreshold6TargetID int `json:"WeeklyLotBonusThreshold6TargetID,omitempty"`
	WeeklyLotBonusThreshold8TargetID int `json:"WeeklyLotBonusThreshold8TargetID,omitempty"`
	WeeklyLotBonusThreshold10Target string `json:"WeeklyLotBonusThreshold10Target,omitempty"`
	WeeklyLotBonusThreshold14Target string `json:"WeeklyLotBonusThreshold14Target,omitempty"`
	WeeklyLotBonusThreshold18TargetID int `json:"WeeklyLotBonusThreshold18TargetID,omitempty"`
	WeeklyLotBonusThreshold26 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold28Target string `json:"WeeklyLotBonusThreshold28Target,omitempty"`
	WeeklyLotBonusThreshold3 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold8 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold9TargetID int `json:"WeeklyLotBonusThreshold9TargetID,omitempty"`
	WeeklyLotBonusThreshold30 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold15 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold16 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold16Target string `json:"WeeklyLotBonusThreshold16Target,omitempty"`
	WeeklyLotBonusThreshold16TargetID int `json:"WeeklyLotBonusThreshold16TargetID,omitempty"`
	WeeklyLotBonusThreshold21TargetID int `json:"WeeklyLotBonusThreshold21TargetID,omitempty"`
	WeeklyLotBonusThreshold24 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold26Target string `json:"WeeklyLotBonusThreshold26Target,omitempty"`
	WeeklyLotBonusThreshold5TargetID int `json:"WeeklyLotBonusThreshold5TargetID,omitempty"`
	Url string `json:"Url,omitempty"`
	WeeklyLotBonusThreshold12 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold17TargetID int `json:"WeeklyLotBonusThreshold17TargetID,omitempty"`
	WeeklyLotBonusThreshold20Target string `json:"WeeklyLotBonusThreshold20Target,omitempty"`
	WeeklyLotBonusThreshold5Target string `json:"WeeklyLotBonusThreshold5Target,omitempty"`
	WeeklyLotBonusThreshold6 struct {
		ID int `json:"ID,omitempty"`
	}
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	WeeklyLotBonusThreshold11 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold17 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold22Target string `json:"WeeklyLotBonusThreshold22Target,omitempty"`
	WeeklyLotBonusThreshold25TargetID int `json:"WeeklyLotBonusThreshold25TargetID,omitempty"`
	WeeklyLotBonusThreshold27TargetID int `json:"WeeklyLotBonusThreshold27TargetID,omitempty"`
	WeeklyLotBonusThreshold29TargetID int `json:"WeeklyLotBonusThreshold29TargetID,omitempty"`
	WeeklyLotBonusThreshold7TargetID int `json:"WeeklyLotBonusThreshold7TargetID,omitempty"`
	WeeklyLotBonusThreshold1 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold10TargetID int `json:"WeeklyLotBonusThreshold10TargetID,omitempty"`
	WeeklyLotBonusThreshold11TargetID int `json:"WeeklyLotBonusThreshold11TargetID,omitempty"`
	WeeklyLotBonusThreshold2Target string `json:"WeeklyLotBonusThreshold2Target,omitempty"`
	WeeklyLotBonusThreshold3Target string `json:"WeeklyLotBonusThreshold3Target,omitempty"`
	WeeklyLotBonusThreshold4 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold22 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold26TargetID int `json:"WeeklyLotBonusThreshold26TargetID,omitempty"`
	WeeklyLotBonusThreshold27 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold27Target string `json:"WeeklyLotBonusThreshold27Target,omitempty"`
	WeeklyLotBonusThreshold29 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold12Target string `json:"WeeklyLotBonusThreshold12Target,omitempty"`
	WeeklyLotBonusThreshold23 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold24Target string `json:"WeeklyLotBonusThreshold24Target,omitempty"`
	WeeklyLotBonusThreshold30Target string `json:"WeeklyLotBonusThreshold30Target,omitempty"`
	WeeklyLotBonusThreshold7 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold9 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold10 struct {
		ID int `json:"ID,omitempty"`
	}
	WeeklyLotBonusThreshold15TargetID int `json:"WeeklyLotBonusThreshold15TargetID,omitempty"`
	WeeklyLotBonusThreshold19Target string `json:"WeeklyLotBonusThreshold19Target,omitempty"`
	WeeklyLotBonusThreshold1Target string `json:"WeeklyLotBonusThreshold1Target,omitempty"`
	WeeklyLotBonusThreshold23TargetID int `json:"WeeklyLotBonusThreshold23TargetID,omitempty"`
	WeeklyLotBonusThreshold6Target string `json:"WeeklyLotBonusThreshold6Target,omitempty"`
	WeeklyLotBonusThreshold20TargetID int `json:"WeeklyLotBonusThreshold20TargetID,omitempty"`
	WeeklyLotBonusThreshold21Target string `json:"WeeklyLotBonusThreshold21Target,omitempty"`
}
