// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type InstanceContentBuff struct {
	EchoDeath int `json:"EchoDeath,omitempty"`
	EchoStart int `json:"EchoStart,omitempty"`
	GameContentLinks struct {
		InstanceContent struct {
			InstanceContentBuff []interface{} `json:"InstanceContentBuff,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	Url string `json:"Url,omitempty"`
}
