// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type DeepDungeonItem struct {
	IconID int `json:"IconID,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Singular_en string `json:"Singular_en,omitempty"`
	Icon string `json:"Icon,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Singular_fr string `json:"Singular_fr,omitempty"`
	Tooltip_fr string `json:"Tooltip_fr,omitempty"`
	Tooltip_ja string `json:"Tooltip_ja,omitempty"`
	Url string `json:"Url,omitempty"`
	ActionTargetID int `json:"ActionTargetID,omitempty"`
	ID int `json:"ID,omitempty"`
	Plural_fr string `json:"Plural_fr,omitempty"`
	Tooltip_de string `json:"Tooltip_de,omitempty"`
	Name string `json:"Name,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	Tooltip string `json:"Tooltip,omitempty"`
	Action struct {
		ActionCategory int `json:"ActionCategory,omitempty"`
		ActionData int `json:"ActionData,omitempty"`
		ActionProcStatus int `json:"ActionProcStatus,omitempty"`
		ActionTimelineHit struct {
			ID int `json:"ID,omitempty"`
			Key string `json:"Key,omitempty"`
			Key_en string `json:"Key_en,omitempty"`
		}
		CanTargetFriendly int `json:"CanTargetFriendly,omitempty"`
		ClassJobCategory int `json:"ClassJobCategory,omitempty"`
		Cost int `json:"Cost,omitempty"`
		Icon string `json:"Icon,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		CanTargetParty int `json:"CanTargetParty,omitempty"`
		ID int `json:"ID,omitempty"`
		Omen int `json:"Omen,omitempty"`
		AffectsPosition int `json:"AffectsPosition,omitempty"`
		Aspect int `json:"Aspect,omitempty"`
		EffectRange int `json:"EffectRange,omitempty"`
		PreservesCombo int `json:"PreservesCombo,omitempty"`
		Range int `json:"Range,omitempty"`
		ActionCombo int `json:"ActionCombo,omitempty"`
		AnimationEndTarget string `json:"AnimationEndTarget,omitempty"`
		AttackType int `json:"AttackType,omitempty"`
		ClassJob int `json:"ClassJob,omitempty"`
		IsRoleAction int `json:"IsRoleAction,omitempty"`
		Name string `json:"Name,omitempty"`
		StatusGainSelf int `json:"StatusGainSelf,omitempty"`
		AnimationEnd struct {
			ID int `json:"ID,omitempty"`
			Key string `json:"Key,omitempty"`
			Key_en string `json:"Key_en,omitempty"`
		}
		ClassJobLevel int `json:"ClassJobLevel,omitempty"`
		CostType int `json:"CostType,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		XAxisModifier int `json:"XAxisModifier,omitempty"`
		ActionTimelineHitTarget string `json:"ActionTimelineHitTarget,omitempty"`
		AnimationStart int `json:"AnimationStart,omitempty"`
		CanTargetDead int `json:"CanTargetDead,omitempty"`
		CanTargetHostile int `json:"CanTargetHostile,omitempty"`
		CanTargetSelf int `json:"CanTargetSelf,omitempty"`
		Cast100ms int `json:"Cast100ms,omitempty"`
		IconID int `json:"IconID,omitempty"`
		IsPvP int `json:"IsPvP,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		VFX int `json:"VFX,omitempty"`
		ActionTimelineHitTargetID int `json:"ActionTimelineHitTargetID,omitempty"`
		AnimationEndTargetID int `json:"AnimationEndTargetID,omitempty"`
		CastType int `json:"CastType,omitempty"`
		CooldownGroup int `json:"CooldownGroup,omitempty"`
		Recast100ms int `json:"Recast100ms,omitempty"`
		TargetArea int `json:"TargetArea,omitempty"`
	}
	Plural_en string `json:"Plural_en,omitempty"`
	Tooltip_en string `json:"Tooltip_en,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	Singular string `json:"Singular,omitempty"`
	Singular_de string `json:"Singular_de,omitempty"`
	ActionTarget string `json:"ActionTarget,omitempty"`
	Plural_de string `json:"Plural_de,omitempty"`
	Singular_ja string `json:"Singular_ja,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	Plural string `json:"Plural,omitempty"`
	Plural_ja string `json:"Plural_ja,omitempty"`
}
