// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type VFX struct {
	GameContentLinks struct {
		ActionCastTimeline struct {
			VFX []interface{} `json:"VFX,omitempty"`
		}
		ActionCastVFX struct {
			VFX []interface{} `json:"VFX,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	Location string `json:"Location,omitempty"`
	Location_en string `json:"Location_en,omitempty"`
	Url string `json:"Url,omitempty"`
}
