// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ActivityFeedImages struct {
	ActivityFeedEN string `json:"ActivityFeedEN,omitempty"`
	ActivityFeedEN_en string `json:"ActivityFeedEN_en,omitempty"`
	ActivityFeedFR string `json:"ActivityFeedFR,omitempty"`
	ActivityFeedFR_en string `json:"ActivityFeedFR_en,omitempty"`
	ActivityFeedJA string `json:"ActivityFeedJA,omitempty"`
	ExpansionImage string `json:"ExpansionImage,omitempty"`
	ActivityFeedDE string `json:"ActivityFeedDE,omitempty"`
	ActivityFeedDE_en string `json:"ActivityFeedDE_en,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	ActivityFeedJA_en string `json:"ActivityFeedJA_en,omitempty"`
	ExpansionImage_en string `json:"ExpansionImage_en,omitempty"`
}
