// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type Title struct {
	GameContentLinks struct {
		Achievement struct {
			Title []interface{} `json:"Title,omitempty"`
		}
	}
	Icon string `json:"Icon,omitempty"`
	NameFemale_en string `json:"NameFemale_en,omitempty"`
	NameFemale_ja string `json:"NameFemale_ja,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	GamePatch struct {
		Name_cn string `json:"Name_cn,omitempty"`
		Version int `json:"Version,omitempty"`
		ExVersion int `json:"ExVersion,omitempty"`
		IsExpansion bool `json:"IsExpansion,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_kr string `json:"Name_kr,omitempty"`
		ID int `json:"ID,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Url string `json:"Url,omitempty"`
		Banner string `json:"Banner,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		ReleaseDate int `json:"ReleaseDate,omitempty"`
	}
	ID int `json:"ID,omitempty"`
	IsPrefix int `json:"IsPrefix,omitempty"`
	NameFemale_de string `json:"NameFemale_de,omitempty"`
	NameFemale_fr string `json:"NameFemale_fr,omitempty"`
	Url string `json:"Url,omitempty"`
	Name string `json:"Name,omitempty"`
	NameFemale string `json:"NameFemale,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
}
