// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type MonsterNoteTarget struct {
	PlaceNameLocation2 struct {
		NameNoArticle_de string `json:"NameNoArticle_de,omitempty"`
		NameNoArticle_fr string `json:"NameNoArticle_fr,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		ID int `json:"ID,omitempty"`
		Icon string `json:"Icon,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		NameNoArticle string `json:"NameNoArticle,omitempty"`
		NameNoArticle_en string `json:"NameNoArticle_en,omitempty"`
		NameNoArticle_ja string `json:"NameNoArticle_ja,omitempty"`
	}
	PlaceNameZone0 struct {
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		Icon string `json:"Icon,omitempty"`
		NameNoArticle_en string `json:"NameNoArticle_en,omitempty"`
		NameNoArticle_fr string `json:"NameNoArticle_fr,omitempty"`
		Name string `json:"Name,omitempty"`
		NameNoArticle string `json:"NameNoArticle,omitempty"`
		NameNoArticle_de string `json:"NameNoArticle_de,omitempty"`
		NameNoArticle_ja string `json:"NameNoArticle_ja,omitempty"`
	}
	PlaceNameZone2 struct {
		Icon string `json:"Icon,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		ID int `json:"ID,omitempty"`
		Name string `json:"Name,omitempty"`
		NameNoArticle string `json:"NameNoArticle,omitempty"`
		NameNoArticle_de string `json:"NameNoArticle_de,omitempty"`
		NameNoArticle_en string `json:"NameNoArticle_en,omitempty"`
		NameNoArticle_fr string `json:"NameNoArticle_fr,omitempty"`
		NameNoArticle_ja string `json:"NameNoArticle_ja,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
	}
	PlaceNameZone2Target string `json:"PlaceNameZone2Target,omitempty"`
	IconID int `json:"IconID,omitempty"`
	PlaceNameLocation1 struct {
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Icon string `json:"Icon,omitempty"`
		Name string `json:"Name,omitempty"`
		NameNoArticle string `json:"NameNoArticle,omitempty"`
		NameNoArticle_en string `json:"NameNoArticle_en,omitempty"`
		NameNoArticle_ja string `json:"NameNoArticle_ja,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		NameNoArticle_de string `json:"NameNoArticle_de,omitempty"`
		NameNoArticle_fr string `json:"NameNoArticle_fr,omitempty"`
	}
	ID int `json:"ID,omitempty"`
	PlaceNameLocation2Target string `json:"PlaceNameLocation2Target,omitempty"`
	PlaceNameZone2TargetID int `json:"PlaceNameZone2TargetID,omitempty"`
	BNpcNameTarget string `json:"BNpcNameTarget,omitempty"`
	GameContentLinks struct {
		MonsterNote struct {
			MonsterNoteTarget0 []interface{} `json:"MonsterNoteTarget0,omitempty"`
		}
	}
	PlaceNameLocation0TargetID int `json:"PlaceNameLocation0TargetID,omitempty"`
	PlaceNameLocation1TargetID int `json:"PlaceNameLocation1TargetID,omitempty"`
	PlaceNameLocation2TargetID int `json:"PlaceNameLocation2TargetID,omitempty"`
	PlaceNameZone0TargetID int `json:"PlaceNameZone0TargetID,omitempty"`
	PlaceNameZone1TargetID int `json:"PlaceNameZone1TargetID,omitempty"`
	Url string `json:"Url,omitempty"`
	PlaceNameLocation0 struct {
		ID int `json:"ID,omitempty"`
		NameNoArticle_de string `json:"NameNoArticle_de,omitempty"`
		NameNoArticle_en string `json:"NameNoArticle_en,omitempty"`
		NameNoArticle_ja string `json:"NameNoArticle_ja,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		Icon string `json:"Icon,omitempty"`
		Name string `json:"Name,omitempty"`
		NameNoArticle string `json:"NameNoArticle,omitempty"`
		NameNoArticle_fr string `json:"NameNoArticle_fr,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
	}
	PlaceNameLocation0Target string `json:"PlaceNameLocation0Target,omitempty"`
	Icon string `json:"Icon,omitempty"`
	PlaceNameLocation1Target string `json:"PlaceNameLocation1Target,omitempty"`
	PlaceNameZone0Target string `json:"PlaceNameZone0Target,omitempty"`
	PlaceNameZone1 struct {
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		ID int `json:"ID,omitempty"`
		Icon string `json:"Icon,omitempty"`
		NameNoArticle string `json:"NameNoArticle,omitempty"`
		NameNoArticle_de string `json:"NameNoArticle_de,omitempty"`
		NameNoArticle_en string `json:"NameNoArticle_en,omitempty"`
		NameNoArticle_ja string `json:"NameNoArticle_ja,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name string `json:"Name,omitempty"`
		NameNoArticle_fr string `json:"NameNoArticle_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
	}
	PlaceNameZone1Target string `json:"PlaceNameZone1Target,omitempty"`
	BNpcName struct {
		StartsWithVowel int `json:"StartsWithVowel,omitempty"`
		ID int `json:"ID,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		Plural_de string `json:"Plural_de,omitempty"`
		Plural_ja string `json:"Plural_ja,omitempty"`
		Icon string `json:"Icon,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Plural string `json:"Plural,omitempty"`
		Plural_en string `json:"Plural_en,omitempty"`
		Plural_fr string `json:"Plural_fr,omitempty"`
	}
	BNpcNameTargetID int `json:"BNpcNameTargetID,omitempty"`
}
