// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ScenarioTreeTips struct {
	Tips2Target string `json:"Tips2Target,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	Tips1Target string `json:"Tips1Target,omitempty"`
	Tips1TargetID int `json:"Tips1TargetID,omitempty"`
	Tips2 struct {
		ID int `json:"ID,omitempty"`
		Image struct {
			ID int `json:"ID,omitempty"`
			Image string `json:"Image,omitempty"`
			ImageID int `json:"ImageID,omitempty"`
		}
		ImageTarget string `json:"ImageTarget,omitempty"`
		ImageTargetID int `json:"ImageTargetID,omitempty"`
		Type int `json:"Type,omitempty"`
	}
	ID int `json:"ID,omitempty"`
	Tips1 struct {
		Level int `json:"Level,omitempty"`
		LevelTarget string `json:"LevelTarget,omitempty"`
		LevelTargetID int `json:"LevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	Tips2TargetID int `json:"Tips2TargetID,omitempty"`
}
