// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type GatheringType struct {
	IconMainID int `json:"IconMainID,omitempty"`
	IconOffID int `json:"IconOffID,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	GameContentLinks struct {
		GatheringPointBase struct {
			GatheringType []interface{} `json:"GatheringType,omitempty"`
		}
	}
	IconMain string `json:"IconMain,omitempty"`
	Name string `json:"Name,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	Url string `json:"Url,omitempty"`
	ID int `json:"ID,omitempty"`
	IconOff string `json:"IconOff,omitempty"`
}
