// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type RetainerTaskLvRange struct {
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	Max int `json:"Max,omitempty"`
	Min int `json:"Min,omitempty"`
	Url string `json:"Url,omitempty"`
}
