// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ContentType struct {
	IconID int `json:"IconID,omitempty"`
	Name string `json:"Name,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks struct {
		ContentFinderCondition struct {
			ContentType []interface{} `json:"ContentType,omitempty"`
		}
		ContentsNoteCategory struct {
			Type []interface{} `json:"Type,omitempty"`
		}
	}
	IconDutyFinder string `json:"IconDutyFinder,omitempty"`
	IconDutyFinderID int `json:"IconDutyFinderID,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	ID int `json:"ID,omitempty"`
	Icon string `json:"Icon,omitempty"`
}
