// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type BGMSituation struct {
	BGMField struct {
		File string `json:"File,omitempty"`
		File_en string `json:"File_en,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	BGMFieldTarget string `json:"BGMFieldTarget,omitempty"`
	Url string `json:"Url,omitempty"`
	BGMDayTargetID int `json:"BGMDayTargetID,omitempty"`
	BGMNight struct {
		File string `json:"File,omitempty"`
		File_en string `json:"File_en,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	ID int `json:"ID,omitempty"`
	BGMBattleTarget string `json:"BGMBattleTarget,omitempty"`
	BGMBattleTargetID int `json:"BGMBattleTargetID,omitempty"`
	BGMDayTarget string `json:"BGMDayTarget,omitempty"`
	BGMBattle struct {
		File string `json:"File,omitempty"`
		File_en string `json:"File_en,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	BGMFieldTargetID int `json:"BGMFieldTargetID,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	BGMDay struct {
		File string `json:"File,omitempty"`
		File_en string `json:"File_en,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	BGMNightTarget string `json:"BGMNightTarget,omitempty"`
	BGMNightTargetID int `json:"BGMNightTargetID,omitempty"`
}
