// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type MapMarker struct {
	MapMarkerRegionTarget string `json:"MapMarkerRegionTarget,omitempty"`
	MapMarkerRegionTargetID int `json:"MapMarkerRegionTargetID,omitempty"`
	PlaceNameSubtextTarget string `json:"PlaceNameSubtextTarget,omitempty"`
	DataType int `json:"DataType,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	Url string `json:"Url,omitempty"`
	X int `json:"X,omitempty"`
	IconID int `json:"IconID,omitempty"`
	SubtextOrientation int `json:"SubtextOrientation,omitempty"`
	PlaceNameSubtextTargetID int `json:"PlaceNameSubtextTargetID,omitempty"`
	Y int `json:"Y,omitempty"`
	Icon string `json:"Icon,omitempty"`
	MapMarkerRegion struct {
		ID int `json:"ID,omitempty"`
		X int `json:"X,omitempty"`
	}
	PlaceNameSubtext struct {
		Icon string `json:"Icon,omitempty"`
		Name string `json:"Name,omitempty"`
		NameNoArticle_de string `json:"NameNoArticle_de,omitempty"`
		NameNoArticle_en string `json:"NameNoArticle_en,omitempty"`
		NameNoArticle_fr string `json:"NameNoArticle_fr,omitempty"`
		NameNoArticle_ja string `json:"NameNoArticle_ja,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		NameNoArticle string `json:"NameNoArticle,omitempty"`
	}
	Type int `json:"Type,omitempty"`
	DataKey int `json:"DataKey,omitempty"`
	ID int `json:"ID,omitempty"`
}
