// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type TripleTriadCardResident struct {
	Bottom int `json:"Bottom,omitempty"`
	ID int `json:"ID,omitempty"`
	SortKey int `json:"SortKey,omitempty"`
	TripleTriadCardRarityTarget string `json:"TripleTriadCardRarityTarget,omitempty"`
	Url string `json:"Url,omitempty"`
	Right int `json:"Right,omitempty"`
	Top int `json:"Top,omitempty"`
	TripleTriadCardRarity struct {
		ID int `json:"ID,omitempty"`
		Stars int `json:"Stars,omitempty"`
	}
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	Left int `json:"Left,omitempty"`
	SaleValue int `json:"SaleValue,omitempty"`
	TripleTriadCardType struct {
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	TripleTriadCardTypeTarget string `json:"TripleTriadCardTypeTarget,omitempty"`
	TripleTriadCardRarityTargetID int `json:"TripleTriadCardRarityTargetID,omitempty"`
	TripleTriadCardTypeTargetID int `json:"TripleTriadCardTypeTargetID,omitempty"`
}
