// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ContentCloseCycle struct {
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	TimeSeconds int `json:"TimeSeconds,omitempty"`
	Unixtime int `json:"Unixtime,omitempty"`
	Url string `json:"Url,omitempty"`
}
