// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type EquipSlotCategory struct {
	Feet int `json:"Feet,omitempty"`
	ID int `json:"ID,omitempty"`
	MainHand int `json:"MainHand,omitempty"`
	SoulCrystal int `json:"SoulCrystal,omitempty"`
	Gloves int `json:"Gloves,omitempty"`
	Head int `json:"Head,omitempty"`
	OffHand int `json:"OffHand,omitempty"`
	Url string `json:"Url,omitempty"`
	Waist int `json:"Waist,omitempty"`
	Wrists int `json:"Wrists,omitempty"`
	Body int `json:"Body,omitempty"`
	Ears int `json:"Ears,omitempty"`
	FingerL int `json:"FingerL,omitempty"`
	FingerR int `json:"FingerR,omitempty"`
	GameContentLinks struct {
		Item struct {
			EquipSlotCategory []interface{} `json:"EquipSlotCategory,omitempty"`
		}
	}
	Legs int `json:"Legs,omitempty"`
	Neck int `json:"Neck,omitempty"`
}
