// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type LogKind struct {
	LogKindCategoryTextTargetID int `json:"LogKindCategoryTextTargetID,omitempty"`
	Example_en string `json:"Example_en,omitempty"`
	Example_fr string `json:"Example_fr,omitempty"`
	GameContentLinks struct {
		LogFilter struct {
			LogKind []interface{} `json:"LogKind,omitempty"`
		}
		LogMessage struct {
			LogKind []interface{} `json:"LogKind,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	Example string `json:"Example,omitempty"`
	Example_ja string `json:"Example_ja,omitempty"`
	LogKindCategoryTextTarget string `json:"LogKindCategoryTextTarget,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Name string `json:"Name,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Url string `json:"Url,omitempty"`
	Format string `json:"Format,omitempty"`
	Format_de string `json:"Format_de,omitempty"`
	Format_ja string `json:"Format_ja,omitempty"`
	LogKindCategoryText struct {
		Text_en string `json:"Text_en,omitempty"`
		Text_fr string `json:"Text_fr,omitempty"`
		Text_ja string `json:"Text_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		Text string `json:"Text,omitempty"`
		Text_de string `json:"Text_de,omitempty"`
	}
	Example_de string `json:"Example_de,omitempty"`
	Format_en string `json:"Format_en,omitempty"`
	Format_fr string `json:"Format_fr,omitempty"`
}
