// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type SubmarineExploration struct {
	Location_fr string `json:"Location_fr,omitempty"`
	Location_ja string `json:"Location_ja,omitempty"`
	RankReq int `json:"RankReq,omitempty"`
	Location string `json:"Location,omitempty"`
	Location_en string `json:"Location_en,omitempty"`
	Destination_en string `json:"Destination_en,omitempty"`
	Destination_ja string `json:"Destination_ja,omitempty"`
	DistanceForSurvey int `json:"DistanceForSurvey,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	Destination_de string `json:"Destination_de,omitempty"`
	Destination_fr string `json:"Destination_fr,omitempty"`
	Location_de string `json:"Location_de,omitempty"`
	ID int `json:"ID,omitempty"`
	Url string `json:"Url,omitempty"`
	CeruleumTankReq int `json:"CeruleumTankReq,omitempty"`
	Destination string `json:"Destination,omitempty"`
	DurationMin int `json:"DurationMin,omitempty"`
	ExpReward int `json:"ExpReward,omitempty"`
}
