// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type Emote struct {
	LogMessageTargeted struct {
		ID int `json:"ID,omitempty"`
		LogKindTarget string `json:"LogKindTarget,omitempty"`
		Text string `json:"Text,omitempty"`
		Text_fr string `json:"Text_fr,omitempty"`
		Text_ja string `json:"Text_ja,omitempty"`
		LogKind struct {
			Format_ja string `json:"Format_ja,omitempty"`
			ID int `json:"ID,omitempty"`
			Name_fr string `json:"Name_fr,omitempty"`
			Example_en string `json:"Example_en,omitempty"`
			Format string `json:"Format,omitempty"`
			Format_de string `json:"Format_de,omitempty"`
			Name string `json:"Name,omitempty"`
			Name_de string `json:"Name_de,omitempty"`
			Example_de string `json:"Example_de,omitempty"`
			Format_en string `json:"Format_en,omitempty"`
			Format_fr string `json:"Format_fr,omitempty"`
			LogKindCategoryText int `json:"LogKindCategoryText,omitempty"`
			Name_en string `json:"Name_en,omitempty"`
			Example_ja string `json:"Example_ja,omitempty"`
			Example_fr string `json:"Example_fr,omitempty"`
			Name_ja string `json:"Name_ja,omitempty"`
			Example string `json:"Example,omitempty"`
		}
		LogKindTargetID int `json:"LogKindTargetID,omitempty"`
		Text_de string `json:"Text_de,omitempty"`
		Text_en string `json:"Text_en,omitempty"`
	}
	ActionTimeline2 struct {
		Key string `json:"Key,omitempty"`
		Key_en string `json:"Key_en,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	ActionTimeline2Target string `json:"ActionTimeline2Target,omitempty"`
	TextCommandTargetID int `json:"TextCommandTargetID,omitempty"`
	ActionTimeline0TargetID int `json:"ActionTimeline0TargetID,omitempty"`
	EmoteCategoryTarget string `json:"EmoteCategoryTarget,omitempty"`
	IconID int `json:"IconID,omitempty"`
	LogMessageTargetedTarget string `json:"LogMessageTargetedTarget,omitempty"`
	LogMessageUntargeted struct {
		Text_ja string `json:"Text_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		LogKind struct {
			Example_de string `json:"Example_de,omitempty"`
			Example_fr string `json:"Example_fr,omitempty"`
			Format_fr string `json:"Format_fr,omitempty"`
			Name_fr string `json:"Name_fr,omitempty"`
			Example_ja string `json:"Example_ja,omitempty"`
			Format_ja string `json:"Format_ja,omitempty"`
			ID int `json:"ID,omitempty"`
			Name string `json:"Name,omitempty"`
			Name_en string `json:"Name_en,omitempty"`
			Example string `json:"Example,omitempty"`
			Example_en string `json:"Example_en,omitempty"`
			Format string `json:"Format,omitempty"`
			Name_de string `json:"Name_de,omitempty"`
			Name_ja string `json:"Name_ja,omitempty"`
			Format_de string `json:"Format_de,omitempty"`
			Format_en string `json:"Format_en,omitempty"`
			LogKindCategoryText int `json:"LogKindCategoryText,omitempty"`
		}
		LogKindTarget string `json:"LogKindTarget,omitempty"`
		LogKindTargetID int `json:"LogKindTargetID,omitempty"`
		Text string `json:"Text,omitempty"`
		Text_de string `json:"Text_de,omitempty"`
		Text_en string `json:"Text_en,omitempty"`
		Text_fr string `json:"Text_fr,omitempty"`
	}
	ActionTimeline4Target string `json:"ActionTimeline4Target,omitempty"`
	Icon string `json:"Icon,omitempty"`
	ActionTimeline4TargetID int `json:"ActionTimeline4TargetID,omitempty"`
	ActionTimeline5 int `json:"ActionTimeline5,omitempty"`
	EmoteCategoryTargetID int `json:"EmoteCategoryTargetID,omitempty"`
	EmoteMode int `json:"EmoteMode,omitempty"`
	GameContentLinks struct {
		Adventure struct {
			Emote []interface{} `json:"Emote,omitempty"`
		}
	}
	Name_en string `json:"Name_en,omitempty"`
	ActionTimeline0 struct {
		ID int `json:"ID,omitempty"`
		Key string `json:"Key,omitempty"`
		Key_en string `json:"Key_en,omitempty"`
	}
	ActionTimeline0Target string `json:"ActionTimeline0Target,omitempty"`
	TextCommandTarget string `json:"TextCommandTarget,omitempty"`
	EmoteCategory struct {
		ID int `json:"ID,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
	}
	Name_fr string `json:"Name_fr,omitempty"`
	ReceivedFrom int `json:"ReceivedFrom,omitempty"`
	ActionTimeline3Target string `json:"ActionTimeline3Target,omitempty"`
	ActionTimeline4 struct {
		ID int `json:"ID,omitempty"`
		Key string `json:"Key,omitempty"`
		Key_en string `json:"Key_en,omitempty"`
	}
	LogMessageUntargetedTargetID int `json:"LogMessageUntargetedTargetID,omitempty"`
	Name string `json:"Name,omitempty"`
	ActionTimeline6 int `json:"ActionTimeline6,omitempty"`
	ID int `json:"ID,omitempty"`
	GamePatch interface{} `json:"GamePatch,omitempty"`
	LogMessageTargetedTargetID int `json:"LogMessageTargetedTargetID,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	Url string `json:"Url,omitempty"`
	ActionTimeline1 int `json:"ActionTimeline1,omitempty"`
	ActionTimeline3 struct {
		ID int `json:"ID,omitempty"`
		Key string `json:"Key,omitempty"`
		Key_en string `json:"Key_en,omitempty"`
	}
	LogMessageUntargetedTarget string `json:"LogMessageUntargetedTarget,omitempty"`
	TextCommand struct {
		ShortAlias_fr string `json:"ShortAlias_fr,omitempty"`
		ShortCommand string `json:"ShortCommand,omitempty"`
		Command string `json:"Command,omitempty"`
		Command_de string `json:"Command_de,omitempty"`
		Command_fr string `json:"Command_fr,omitempty"`
		Description_ja string `json:"Description_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		ShortAlias_en string `json:"ShortAlias_en,omitempty"`
		ShortCommand_de string `json:"ShortCommand_de,omitempty"`
		Alias string `json:"Alias,omitempty"`
		Command_en string `json:"Command_en,omitempty"`
		Command_ja string `json:"Command_ja,omitempty"`
		Description_fr string `json:"Description_fr,omitempty"`
		ShortAlias string `json:"ShortAlias,omitempty"`
		ShortCommand_ja string `json:"ShortCommand_ja,omitempty"`
		Alias_de string `json:"Alias_de,omitempty"`
		Alias_fr string `json:"Alias_fr,omitempty"`
		Alias_ja string `json:"Alias_ja,omitempty"`
		Description_de string `json:"Description_de,omitempty"`
		Description_en string `json:"Description_en,omitempty"`
		ShortAlias_ja string `json:"ShortAlias_ja,omitempty"`
		Alias_en string `json:"Alias_en,omitempty"`
		Description string `json:"Description,omitempty"`
		ShortAlias_de string `json:"ShortAlias_de,omitempty"`
		ShortCommand_en string `json:"ShortCommand_en,omitempty"`
		ShortCommand_fr string `json:"ShortCommand_fr,omitempty"`
	}
	ActionTimeline2TargetID int `json:"ActionTimeline2TargetID,omitempty"`
	ActionTimeline3TargetID int `json:"ActionTimeline3TargetID,omitempty"`
}
