// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type DeepDungeonEquipment struct {
	Singular string `json:"Singular,omitempty"`
	Singular_de string `json:"Singular_de,omitempty"`
	Singular_en string `json:"Singular_en,omitempty"`
	Description_de string `json:"Description_de,omitempty"`
	Description_fr string `json:"Description_fr,omitempty"`
	Icon string `json:"Icon,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	Plural_en string `json:"Plural_en,omitempty"`
	Plural_fr string `json:"Plural_fr,omitempty"`
	Singular_ja string `json:"Singular_ja,omitempty"`
	Description_ja string `json:"Description_ja,omitempty"`
	ID int `json:"ID,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	Url string `json:"Url,omitempty"`
	Plural_ja string `json:"Plural_ja,omitempty"`
	Description_en string `json:"Description_en,omitempty"`
	IconID int `json:"IconID,omitempty"`
	Plural_de string `json:"Plural_de,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Plural string `json:"Plural,omitempty"`
	Singular_fr string `json:"Singular_fr,omitempty"`
	Description string `json:"Description,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	Name string `json:"Name,omitempty"`
}
