// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type OrchestrionUiparam struct {
	Order int `json:"Order,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	OrchestrionCategory struct {
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		Name string `json:"Name,omitempty"`
	}
	OrchestrionCategoryTarget string `json:"OrchestrionCategoryTarget,omitempty"`
	OrchestrionCategoryTargetID int `json:"OrchestrionCategoryTargetID,omitempty"`
}
