// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type GatheringPointBonus struct {
	ID int `json:"ID,omitempty"`
	BonusType struct {
		ID int `json:"ID,omitempty"`
		Text string `json:"Text,omitempty"`
		Text_de string `json:"Text_de,omitempty"`
		Text_en string `json:"Text_en,omitempty"`
		Text_fr string `json:"Text_fr,omitempty"`
		Text_ja string `json:"Text_ja,omitempty"`
	}
	BonusTypeTargetID int `json:"BonusTypeTargetID,omitempty"`
	BonusValue int `json:"BonusValue,omitempty"`
	ConditionTargetID int `json:"ConditionTargetID,omitempty"`
	ConditionValue int `json:"ConditionValue,omitempty"`
	BonusTypeTarget string `json:"BonusTypeTarget,omitempty"`
	Condition struct {
		Text_fr string `json:"Text_fr,omitempty"`
		Text_ja string `json:"Text_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		Text string `json:"Text,omitempty"`
		Text_de string `json:"Text_de,omitempty"`
		Text_en string `json:"Text_en,omitempty"`
	}
	ConditionTarget string `json:"ConditionTarget,omitempty"`
	GameContentLinks struct {
		GatheringPoint struct {
			GatheringPointBonus0 []interface{} `json:"GatheringPointBonus0,omitempty"`
		}
	}
	Url string `json:"Url,omitempty"`
}
