// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type BGMSystemDefine struct {
	ID int `json:"ID,omitempty"`
	Url string `json:"Url,omitempty"`
	Define int `json:"Define,omitempty"`
	GameContentLinks struct {
		BGMSwitch struct {
			BGMSystemDefine []interface{} `json:"BGMSystemDefine,omitempty"`
		}
	}
}
