// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type Salvage struct {
	GameContentLinks struct {
		Item struct {
			Salvage []interface{} `json:"Salvage,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	OptimalSkill int `json:"OptimalSkill,omitempty"`
	Url string `json:"Url,omitempty"`
}
