// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type GatheringLeve struct {
	RequiredItem1 struct {
		CastTime int `json:"CastTime,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Singular_de string `json:"Singular_de,omitempty"`
		Singular_en string `json:"Singular_en,omitempty"`
		Singular_fr string `json:"Singular_fr,omitempty"`
		Singular_ja string `json:"Singular_ja,omitempty"`
		ActionTargetID int `json:"ActionTargetID,omitempty"`
		StackSize int `json:"StackSize,omitempty"`
		Icon string `json:"Icon,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Plural_de string `json:"Plural_de,omitempty"`
		Plural_fr string `json:"Plural_fr,omitempty"`
		Rarity int `json:"Rarity,omitempty"`
		StartsWithVowel int `json:"StartsWithVowel,omitempty"`
		ID int `json:"ID,omitempty"`
		Plural_en string `json:"Plural_en,omitempty"`
		Quest int `json:"Quest,omitempty"`
		Singular string `json:"Singular,omitempty"`
		Action struct {
			StatusGainSelf int `json:"StatusGainSelf,omitempty"`
			AnimationEnd int `json:"AnimationEnd,omitempty"`
			CanTargetFriendly int `json:"CanTargetFriendly,omitempty"`
			CanTargetHostile int `json:"CanTargetHostile,omitempty"`
			Name_en string `json:"Name_en,omitempty"`
			Name_ja string `json:"Name_ja,omitempty"`
			ActionProcStatus int `json:"ActionProcStatus,omitempty"`
			AttackType int `json:"AttackType,omitempty"`
			CastType int `json:"CastType,omitempty"`
			ClassJob int `json:"ClassJob,omitempty"`
			Cost int `json:"Cost,omitempty"`
			ID int `json:"ID,omitempty"`
			PreservesCombo int `json:"PreservesCombo,omitempty"`
			Range int `json:"Range,omitempty"`
			ActionCombo int `json:"ActionCombo,omitempty"`
			AnimationStart int `json:"AnimationStart,omitempty"`
			VFX int `json:"VFX,omitempty"`
			Recast100ms int `json:"Recast100ms,omitempty"`
			TargetArea int `json:"TargetArea,omitempty"`
			IconID int `json:"IconID,omitempty"`
			Name_fr string `json:"Name_fr,omitempty"`
			XAxisModifier int `json:"XAxisModifier,omitempty"`
			ActionCategory int `json:"ActionCategory,omitempty"`
			ClassJobCategory int `json:"ClassJobCategory,omitempty"`
			CooldownGroup int `json:"CooldownGroup,omitempty"`
			Icon string `json:"Icon,omitempty"`
			IsRoleAction int `json:"IsRoleAction,omitempty"`
			Omen int `json:"Omen,omitempty"`
			AffectsPosition int `json:"AffectsPosition,omitempty"`
			Cast100ms int `json:"Cast100ms,omitempty"`
			CanTargetDead int `json:"CanTargetDead,omitempty"`
			CanTargetParty int `json:"CanTargetParty,omitempty"`
			ActionData int `json:"ActionData,omitempty"`
			Aspect int `json:"Aspect,omitempty"`
			CostType int `json:"CostType,omitempty"`
			ActionTimelineHit int `json:"ActionTimelineHit,omitempty"`
			CanTargetSelf int `json:"CanTargetSelf,omitempty"`
			IsPvP int `json:"IsPvP,omitempty"`
			Name string `json:"Name,omitempty"`
			Name_de string `json:"Name_de,omitempty"`
			ClassJobLevel int `json:"ClassJobLevel,omitempty"`
			EffectRange int `json:"EffectRange,omitempty"`
		}
		IconID int `json:"IconID,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		Plural string `json:"Plural,omitempty"`
		Plural_ja string `json:"Plural_ja,omitempty"`
		ActionTarget string `json:"ActionTarget,omitempty"`
	}
	RequiredItem1Target string `json:"RequiredItem1Target,omitempty"`
	RequiredItem1TargetID int `json:"RequiredItem1TargetID,omitempty"`
	RequiredItem2 int `json:"RequiredItem2,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	LeveLevel int `json:"LeveLevel,omitempty"`
}
