// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type GatheringPointBonusType struct {
	Url string `json:"Url,omitempty"`
	GameContentLinks struct {
		GatheringPointBonus struct {
			BonusType []interface{} `json:"BonusType,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	Text string `json:"Text,omitempty"`
	Text_de string `json:"Text_de,omitempty"`
	Text_en string `json:"Text_en,omitempty"`
	Text_fr string `json:"Text_fr,omitempty"`
	Text_ja string `json:"Text_ja,omitempty"`
}
