// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type Weather struct {
	GameContentLinks struct {
		ChocoboRaceWeather struct {
			WeatherType2 []interface{} `json:"WeatherType2,omitempty"`
			WeatherType1 []interface{} `json:"WeatherType1,omitempty"`
		}
		WeatherRate struct {
			Weather6 []interface{} `json:"Weather6,omitempty"`
			Weather0 []interface{} `json:"Weather0,omitempty"`
			Weather1 []interface{} `json:"Weather1,omitempty"`
			Weather2 []interface{} `json:"Weather2,omitempty"`
			Weather3 []interface{} `json:"Weather3,omitempty"`
			Weather4 []interface{} `json:"Weather4,omitempty"`
			Weather5 []interface{} `json:"Weather5,omitempty"`
		}
	}
	GamePatch interface{} `json:"GamePatch,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Description_de string `json:"Description_de,omitempty"`
	Icon string `json:"Icon,omitempty"`
	Description string `json:"Description,omitempty"`
	Description_en string `json:"Description_en,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Url string `json:"Url,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	Description_fr string `json:"Description_fr,omitempty"`
	Description_ja string `json:"Description_ja,omitempty"`
	ID int `json:"ID,omitempty"`
	IconID int `json:"IconID,omitempty"`
	Name string `json:"Name,omitempty"`
}
