// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type RetainerTask struct {
	RetainerTaskParameterTargetID int `json:"RetainerTaskParameterTargetID,omitempty"`
	Task int `json:"Task,omitempty"`
	ClassJobCategory struct {
		ACN int `json:"ACN,omitempty"`
		GSM int `json:"GSM,omitempty"`
		RDM int `json:"RDM,omitempty"`
		WHM int `json:"WHM,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		PGL int `json:"PGL,omitempty"`
		SCH int `json:"SCH,omitempty"`
		AST int `json:"AST,omitempty"`
		BLM int `json:"BLM,omitempty"`
		CRP int `json:"CRP,omitempty"`
		DRG int `json:"DRG,omitempty"`
		MRD int `json:"MRD,omitempty"`
		BSM int `json:"BSM,omitempty"`
		GLA int `json:"GLA,omitempty"`
		ROG int `json:"ROG,omitempty"`
		PLD int `json:"PLD,omitempty"`
		ADV int `json:"ADV,omitempty"`
		ALC int `json:"ALC,omitempty"`
		ARC int `json:"ARC,omitempty"`
		DRK int `json:"DRK,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		BTN int `json:"BTN,omitempty"`
		MCH int `json:"MCH,omitempty"`
		MIN int `json:"MIN,omitempty"`
		Name string `json:"Name,omitempty"`
		CNJ int `json:"CNJ,omitempty"`
		CUL int `json:"CUL,omitempty"`
		FSH int `json:"FSH,omitempty"`
		LNC int `json:"LNC,omitempty"`
		LTW int `json:"LTW,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		ARM int `json:"ARM,omitempty"`
		THM int `json:"THM,omitempty"`
		WAR int `json:"WAR,omitempty"`
		WVR int `json:"WVR,omitempty"`
		SAM int `json:"SAM,omitempty"`
		SMN int `json:"SMN,omitempty"`
		BRD int `json:"BRD,omitempty"`
		ID int `json:"ID,omitempty"`
		MNK int `json:"MNK,omitempty"`
		NIN int `json:"NIN,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
	}
	ClassJobCategoryTargetID int `json:"ClassJobCategoryTargetID,omitempty"`
	ID int `json:"ID,omitempty"`
	MaxTimeMin int `json:"MaxTimeMin,omitempty"`
	VentureCost int `json:"VentureCost,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	IsRandom int `json:"IsRandom,omitempty"`
	RequiredGathering int `json:"RequiredGathering,omitempty"`
	RequiredItemLevel int `json:"RequiredItemLevel,omitempty"`
	RetainerTaskParameterTarget string `json:"RetainerTaskParameterTarget,omitempty"`
	ClassJobCategoryTarget string `json:"ClassJobCategoryTarget,omitempty"`
	Experience int `json:"Experience,omitempty"`
	RetainerLevel int `json:"RetainerLevel,omitempty"`
	RetainerTaskParameter struct {
		ItemLevelDoW0 int `json:"ItemLevelDoW0,omitempty"`
		ItemLevelDoW1 int `json:"ItemLevelDoW1,omitempty"`
		GatheringDoL0 int `json:"GatheringDoL0,omitempty"`
		GatheringDoL1 int `json:"GatheringDoL1,omitempty"`
		GatheringFSH0 int `json:"GatheringFSH0,omitempty"`
		GatheringFSH1 int `json:"GatheringFSH1,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	Url string `json:"Url,omitempty"`
}
