// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type GatheringExp struct {
	Exp int `json:"Exp,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	Url string `json:"Url,omitempty"`
}
