// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ScenarioTree struct {
	Image struct {
		ID int `json:"ID,omitempty"`
		Image string `json:"Image,omitempty"`
		ImageID int `json:"ImageID,omitempty"`
	}
	ImageTarget string `json:"ImageTarget,omitempty"`
	Type struct {
		ID int `json:"ID,omitempty"`
		Type string `json:"Type,omitempty"`
		Type_de string `json:"Type_de,omitempty"`
		Type_en string `json:"Type_en,omitempty"`
		Type_fr string `json:"Type_fr,omitempty"`
		Type_ja string `json:"Type_ja,omitempty"`
	}
	TypeTarget string `json:"TypeTarget,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	ImageTargetID int `json:"ImageTargetID,omitempty"`
	TypeTargetID int `json:"TypeTargetID,omitempty"`
	Url string `json:"Url,omitempty"`
}
