// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type AnimaWeaponFUITalk struct {
	ID int `json:"ID,omitempty"`
	Url string `json:"Url,omitempty"`
	Dialogue struct {
		Epilogue string `json:"Epilogue,omitempty"`
		Epilogue_de string `json:"Epilogue_de,omitempty"`
		Epilogue_en string `json:"Epilogue_en,omitempty"`
		Epilogue_ja string `json:"Epilogue_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		Prologue_de string `json:"Prologue_de,omitempty"`
		Prologue_fr string `json:"Prologue_fr,omitempty"`
		Prologue_ja string `json:"Prologue_ja,omitempty"`
		Epilogue_fr string `json:"Epilogue_fr,omitempty"`
		Prologue string `json:"Prologue,omitempty"`
		Prologue_en string `json:"Prologue_en,omitempty"`
	}
	DialogueTarget string `json:"DialogueTarget,omitempty"`
	DialogueTargetID int `json:"DialogueTargetID,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
}
