// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type Mount struct {
	DescriptionEnhanced_de string `json:"DescriptionEnhanced_de,omitempty"`
	DescriptionEnhanced_fr string `json:"DescriptionEnhanced_fr,omitempty"`
	FlyingCondition int `json:"FlyingCondition,omitempty"`
	Tooltip string `json:"Tooltip,omitempty"`
	Tooltip_ja string `json:"Tooltip_ja,omitempty"`
	Name string `json:"Name,omitempty"`
	Plural_fr string `json:"Plural_fr,omitempty"`
	RideBGM struct {
		ID int `json:"ID,omitempty"`
		File string `json:"File,omitempty"`
		File_en string `json:"File_en,omitempty"`
	}
	RideBGMTarget string `json:"RideBGMTarget,omitempty"`
	DescriptionEnhanced string `json:"DescriptionEnhanced,omitempty"`
	DescriptionEnhanced_en string `json:"DescriptionEnhanced_en,omitempty"`
	GameContentLinks struct {
		Quest struct {
			MountRequired []interface{} `json:"MountRequired,omitempty"`
		}
	}
	GamePatch struct {
		Version int `json:"Version,omitempty"`
		Banner string `json:"Banner,omitempty"`
		ExVersion int `json:"ExVersion,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		ReleaseDate int `json:"ReleaseDate,omitempty"`
		ID int `json:"ID,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_cn string `json:"Name_cn,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		Name_kr string `json:"Name_kr,omitempty"`
	}
	Name_de string `json:"Name_de,omitempty"`
	Tooltip_de string `json:"Tooltip_de,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Plural_ja string `json:"Plural_ja,omitempty"`
	DescriptionEnhanced_ja string `json:"DescriptionEnhanced_ja,omitempty"`
	Description_fr string `json:"Description_fr,omitempty"`
	Icon string `json:"Icon,omitempty"`
	IconID int `json:"IconID,omitempty"`
	IsFlying int `json:"IsFlying,omitempty"`
	Plural_en string `json:"Plural_en,omitempty"`
	RideBGMTargetID int `json:"RideBGMTargetID,omitempty"`
	Description string `json:"Description,omitempty"`
	Description_de string `json:"Description_de,omitempty"`
	IconSmall string `json:"IconSmall,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	Plural_de string `json:"Plural_de,omitempty"`
	Description_en string `json:"Description_en,omitempty"`
	ID int `json:"ID,omitempty"`
	Description_ja string `json:"Description_ja,omitempty"`
	Order int `json:"Order,omitempty"`
	Plural string `json:"Plural,omitempty"`
	Tooltip_en string `json:"Tooltip_en,omitempty"`
	Tooltip_fr string `json:"Tooltip_fr,omitempty"`
	Url string `json:"Url,omitempty"`
}
