// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ScenarioType struct {
	Type_de string `json:"Type_de,omitempty"`
	Type_en string `json:"Type_en,omitempty"`
	Type_fr string `json:"Type_fr,omitempty"`
	Type_ja string `json:"Type_ja,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks struct {
		ScenarioTree struct {
			Type []interface{} `json:"Type,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	Type string `json:"Type,omitempty"`
}
