// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type EventAction struct {
	Name_en string `json:"Name_en,omitempty"`
	Animation0Target string `json:"Animation0Target,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	Icon string `json:"Icon,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Animation0 struct {
		Key string `json:"Key,omitempty"`
		Key_en string `json:"Key_en,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	Animation1TargetID int `json:"Animation1TargetID,omitempty"`
	IconID int `json:"IconID,omitempty"`
	Name string `json:"Name,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	CastTime int `json:"CastTime,omitempty"`
	Url string `json:"Url,omitempty"`
	Animation0TargetID int `json:"Animation0TargetID,omitempty"`
	Animation1 struct {
		Key_en string `json:"Key_en,omitempty"`
		ID int `json:"ID,omitempty"`
		Key string `json:"Key,omitempty"`
	}
	Animation1Target string `json:"Animation1Target,omitempty"`
	Animation2 struct {
		Key_en string `json:"Key_en,omitempty"`
		ID int `json:"ID,omitempty"`
		Key string `json:"Key,omitempty"`
	}
	Animation2TargetID int `json:"Animation2TargetID,omitempty"`
	Animation2Target string `json:"Animation2Target,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
}
