// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type PlantPotFlowerSeed struct {
	SeedIcon8 string `json:"SeedIcon8,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	SeedIcon0ID int `json:"SeedIcon0ID,omitempty"`
	SeedIcon1ID int `json:"SeedIcon1ID,omitempty"`
	SeedIcon5 string `json:"SeedIcon5,omitempty"`
	SeedIcon6 string `json:"SeedIcon6,omitempty"`
	SeedIcon1 string `json:"SeedIcon1,omitempty"`
	SeedIcon4 string `json:"SeedIcon4,omitempty"`
	SeedIcon6ID int `json:"SeedIcon6ID,omitempty"`
	SeedIcon7ID int `json:"SeedIcon7ID,omitempty"`
	ID int `json:"ID,omitempty"`
	SeedIcon0 string `json:"SeedIcon0,omitempty"`
	SeedIcon2 string `json:"SeedIcon2,omitempty"`
	SeedIcon3 string `json:"SeedIcon3,omitempty"`
	SeedIcon5ID int `json:"SeedIcon5ID,omitempty"`
	SeedIcon2ID int `json:"SeedIcon2ID,omitempty"`
	SeedIcon3ID int `json:"SeedIcon3ID,omitempty"`
	SeedIcon4ID int `json:"SeedIcon4ID,omitempty"`
	SeedIcon7 string `json:"SeedIcon7,omitempty"`
	SeedIcon8ID int `json:"SeedIcon8ID,omitempty"`
}
