// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type WeatherRate struct {
	Rate0 int `json:"Rate0,omitempty"`
	Weather6Target string `json:"Weather6Target,omitempty"`
	Weather5Target string `json:"Weather5Target,omitempty"`
	ID int `json:"ID,omitempty"`
	Rate5 int `json:"Rate5,omitempty"`
	Weather0 struct {
		ID int `json:"ID,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		Description string `json:"Description,omitempty"`
		Description_ja string `json:"Description_ja,omitempty"`
		Description_fr string `json:"Description_fr,omitempty"`
		Icon string `json:"Icon,omitempty"`
		IconID int `json:"IconID,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Description_de string `json:"Description_de,omitempty"`
		Description_en string `json:"Description_en,omitempty"`
	}
	Weather3TargetID int `json:"Weather3TargetID,omitempty"`
	Weather5 struct {
		Description_ja string `json:"Description_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		Description_de string `json:"Description_de,omitempty"`
		Description_en string `json:"Description_en,omitempty"`
		Icon string `json:"Icon,omitempty"`
		IconID int `json:"IconID,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Description string `json:"Description,omitempty"`
		Description_fr string `json:"Description_fr,omitempty"`
	}
	Weather4TargetID int `json:"Weather4TargetID,omitempty"`
	GameContentLinks struct {
		WeatherGroup struct {
			WeatherRate []interface{} `json:"WeatherRate,omitempty"`
		}
	}
	Rate4 int `json:"Rate4,omitempty"`
	Rate6 int `json:"Rate6,omitempty"`
	Weather2Target string `json:"Weather2Target,omitempty"`
	Weather3 struct {
		Icon string `json:"Icon,omitempty"`
		IconID int `json:"IconID,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Description string `json:"Description,omitempty"`
		Description_de string `json:"Description_de,omitempty"`
		Description_en string `json:"Description_en,omitempty"`
		Description_ja string `json:"Description_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		Description_fr string `json:"Description_fr,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
	}
	Rate7 int `json:"Rate7,omitempty"`
	Url string `json:"Url,omitempty"`
	Weather6TargetID int `json:"Weather6TargetID,omitempty"`
	Weather7 int `json:"Weather7,omitempty"`
	Weather0Target string `json:"Weather0Target,omitempty"`
	Weather1Target string `json:"Weather1Target,omitempty"`
	Weather2 struct {
		ID int `json:"ID,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		Description string `json:"Description,omitempty"`
		Description_en string `json:"Description_en,omitempty"`
		Description_fr string `json:"Description_fr,omitempty"`
		IconID int `json:"IconID,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Description_de string `json:"Description_de,omitempty"`
		Description_ja string `json:"Description_ja,omitempty"`
		Icon string `json:"Icon,omitempty"`
	}
	Weather2TargetID int `json:"Weather2TargetID,omitempty"`
	Weather4 struct {
		ID int `json:"ID,omitempty"`
		Icon string `json:"Icon,omitempty"`
		IconID int `json:"IconID,omitempty"`
		Name string `json:"Name,omitempty"`
		Description_de string `json:"Description_de,omitempty"`
		Description_fr string `json:"Description_fr,omitempty"`
		Description_ja string `json:"Description_ja,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		Description string `json:"Description,omitempty"`
		Description_en string `json:"Description_en,omitempty"`
	}
	Rate2 int `json:"Rate2,omitempty"`
	Rate3 int `json:"Rate3,omitempty"`
	Weather1TargetID int `json:"Weather1TargetID,omitempty"`
	Weather5TargetID int `json:"Weather5TargetID,omitempty"`
	Weather3Target string `json:"Weather3Target,omitempty"`
	Weather4Target string `json:"Weather4Target,omitempty"`
	Weather6 struct {
		Description_de string `json:"Description_de,omitempty"`
		Description_fr string `json:"Description_fr,omitempty"`
		Description_ja string `json:"Description_ja,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Description string `json:"Description,omitempty"`
		Description_en string `json:"Description_en,omitempty"`
		ID int `json:"ID,omitempty"`
		Icon string `json:"Icon,omitempty"`
		IconID int `json:"IconID,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
	}
	Rate1 int `json:"Rate1,omitempty"`
	Weather0TargetID int `json:"Weather0TargetID,omitempty"`
	Weather1 struct {
		Description string `json:"Description,omitempty"`
		Description_de string `json:"Description_de,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		IconID int `json:"IconID,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Description_en string `json:"Description_en,omitempty"`
		Description_fr string `json:"Description_fr,omitempty"`
		Description_ja string `json:"Description_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		Icon string `json:"Icon,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
	}
}
