// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type MacroIcon struct {
	Icon string `json:"Icon,omitempty"`
	IconID int `json:"IconID,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
}
