// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ActivityFeedCaptions struct {
	DE_en string `json:"DE_en,omitempty"`
	FR_en string `json:"FR_en,omitempty"`
	ID int `json:"ID,omitempty"`
	Url string `json:"Url,omitempty"`
	DE string `json:"DE,omitempty"`
	EN_en string `json:"EN_en,omitempty"`
	FR string `json:"FR,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	JA string `json:"JA,omitempty"`
	JA_en string `json:"JA_en,omitempty"`
	EN string `json:"EN,omitempty"`
}
