// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ContentGaugeColor struct {
	ID int `json:"ID,omitempty"`
	Url string `json:"Url,omitempty"`
	AndroidColor1 int `json:"AndroidColor1,omitempty"`
	AndroidColor2 int `json:"AndroidColor2,omitempty"`
	AndroidColor3 int `json:"AndroidColor3,omitempty"`
	GameContentLinks struct {
		ContentGauge struct {
			Color []interface{} `json:"Color,omitempty"`
		}
	}
}
