// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type CompanyAction struct {
	FCRank struct {
		ID int `json:"ID,omitempty"`
	}
	Name_en string `json:"Name_en,omitempty"`
	Description string `json:"Description,omitempty"`
	Description_fr string `json:"Description_fr,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	Icon string `json:"Icon,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Description_de string `json:"Description_de,omitempty"`
	Description_en string `json:"Description_en,omitempty"`
	ID int `json:"ID,omitempty"`
	IconID int `json:"IconID,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	Order int `json:"Order,omitempty"`
	Purchasable int `json:"Purchasable,omitempty"`
	Cost int `json:"Cost,omitempty"`
	Description_ja string `json:"Description_ja,omitempty"`
	FCRankTarget string `json:"FCRankTarget,omitempty"`
	FCRankTargetID int `json:"FCRankTargetID,omitempty"`
	GamePatch struct {
		ReleaseDate int `json:"ReleaseDate,omitempty"`
		Version int `json:"Version,omitempty"`
		Banner string `json:"Banner,omitempty"`
		ID int `json:"ID,omitempty"`
		Name_cn string `json:"Name_cn,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		Name_kr string `json:"Name_kr,omitempty"`
		ExVersion int `json:"ExVersion,omitempty"`
		Name string `json:"Name,omitempty"`
	}
	Name string `json:"Name,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Url string `json:"Url,omitempty"`
}
