// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type Status struct {
	Description string `json:"Description,omitempty"`
	Description_de string `json:"Description_de,omitempty"`
	Description_fr string `json:"Description_fr,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks struct {
		Recipe struct {
			StatusRequired []interface{} `json:"StatusRequired,omitempty"`
		}
	}
	HitEffectTargetID int `json:"HitEffectTargetID,omitempty"`
	ID int `json:"ID,omitempty"`
	IconID int `json:"IconID,omitempty"`
	InflictedByActor int `json:"InflictedByActor,omitempty"`
	LockActions int `json:"LockActions,omitempty"`
	Category int `json:"Category,omitempty"`
	GamePatch struct {
		Banner interface{} `json:"Banner,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_cn string `json:"Name_cn,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_kr string `json:"Name_kr,omitempty"`
		Version int `json:"Version,omitempty"`
		ExVersion int `json:"ExVersion,omitempty"`
		ID int `json:"ID,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		ReleaseDate int `json:"ReleaseDate,omitempty"`
	}
	HitEffectTarget string `json:"HitEffectTarget,omitempty"`
	Icon string `json:"Icon,omitempty"`
	Transfiguration int `json:"Transfiguration,omitempty"`
	IsFcBuff int `json:"IsFcBuff,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	VFX int `json:"VFX,omitempty"`
	IsPermanent int `json:"IsPermanent,omitempty"`
	MaxStacks int `json:"MaxStacks,omitempty"`
	LockControl int `json:"LockControl,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	CanDispel int `json:"CanDispel,omitempty"`
	Description_ja string `json:"Description_ja,omitempty"`
	Description_en string `json:"Description_en,omitempty"`
	HitEffect struct {
		Location struct {
			ID int `json:"ID,omitempty"`
			Location string `json:"Location,omitempty"`
			Location_en string `json:"Location_en,omitempty"`
		}
		LocationTarget string `json:"LocationTarget,omitempty"`
		LocationTargetID int `json:"LocationTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	Invisibility int `json:"Invisibility,omitempty"`
	LockMovement int `json:"LockMovement,omitempty"`
	Name string `json:"Name,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
}
