// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type BaseParam struct {
	Description_fr string `json:"Description_fr,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	ChestLegsGloves% int `json:"ChestLegsGloves%,omitempty"`
	Description_en string `json:"Description_en,omitempty"`
	ChestLegsFeet% int `json:"ChestLegsFeet%,omitempty"`
	Head% int `json:"Head%,omitempty"`
	Waist% int `json:"Waist%,omitempty"`
	2HWpn% int `json:"2HWpn%,omitempty"`
	Earring% int `json:"Earring%,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	OH% int `json:"OH%,omitempty"`
	LegsFeet% int `json:"LegsFeet%,omitempty"`
	Name string `json:"Name,omitempty"`
	Hands% int `json:"Hands%,omitempty"`
	ID int `json:"ID,omitempty"`
	Necklace% int `json:"Necklace%,omitempty"`
	1HWpn% int `json:"1HWpn%,omitempty"`
	ChestHeadLegsFeet% int `json:"ChestHeadLegsFeet%,omitempty"`
	Url string `json:"Url,omitempty"`
	ChestHead% int `json:"ChestHead%,omitempty"`
	Description_de string `json:"Description_de,omitempty"`
	Description_ja string `json:"Description_ja,omitempty"`
	Feet% int `json:"Feet%,omitempty"`
	GameContentLinks struct {
		Materia struct {
			BaseParam []interface{} `json:"BaseParam,omitempty"`
		}
		Item struct {
			BaseParam1 []interface{} `json:"BaseParam1,omitempty"`
			BaseParam2 []interface{} `json:"BaseParam2,omitempty"`
			BaseParamSpecial4 []interface{} `json:"BaseParamSpecial4,omitempty"`
			BaseParam0 []interface{} `json:"BaseParam0,omitempty"`
			BaseParam4 []interface{} `json:"BaseParam4,omitempty"`
			BaseParamSpecial0 []interface{} `json:"BaseParamSpecial0,omitempty"`
			BaseParamSpecial2 []interface{} `json:"BaseParamSpecial2,omitempty"`
			BaseParamSpecial3 []interface{} `json:"BaseParamSpecial3,omitempty"`
			BaseParamSpecial5 []interface{} `json:"BaseParamSpecial5,omitempty"`
			BaseParam3 []interface{} `json:"BaseParam3,omitempty"`
		}
		ItemFood struct {
			BaseParam0 []interface{} `json:"BaseParam0,omitempty"`
			BaseParam1 []interface{} `json:"BaseParam1,omitempty"`
		}
	}
	Ring% int `json:"Ring%,omitempty"`
	Chest% int `json:"Chest%,omitempty"`
	Description string `json:"Description,omitempty"`
	Legs% int `json:"Legs%,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	Bracelet% int `json:"Bracelet%,omitempty"`
	HeadChestHandsLegsFeet% int `json:"HeadChestHandsLegsFeet%,omitempty"`
}
