// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type CharaMakeCustomize struct {
	Data int `json:"Data,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	Icon string `json:"Icon,omitempty"`
	IconID int `json:"IconID,omitempty"`
	IsPurchasable int `json:"IsPurchasable,omitempty"`
	Url string `json:"Url,omitempty"`
}
