// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type MountTransient struct {
	DescriptionEnhanced_de string `json:"DescriptionEnhanced_de,omitempty"`
	Tooltip string `json:"Tooltip,omitempty"`
	Description_fr string `json:"Description_fr,omitempty"`
	Tooltip_de string `json:"Tooltip_de,omitempty"`
	Tooltip_en string `json:"Tooltip_en,omitempty"`
	Url string `json:"Url,omitempty"`
	Description string `json:"Description,omitempty"`
	DescriptionEnhanced_ja string `json:"DescriptionEnhanced_ja,omitempty"`
	Description_de string `json:"Description_de,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	Tooltip_ja string `json:"Tooltip_ja,omitempty"`
	DescriptionEnhanced string `json:"DescriptionEnhanced,omitempty"`
	DescriptionEnhanced_fr string `json:"DescriptionEnhanced_fr,omitempty"`
	Description_en string `json:"Description_en,omitempty"`
	Tooltip_fr string `json:"Tooltip_fr,omitempty"`
	DescriptionEnhanced_en string `json:"DescriptionEnhanced_en,omitempty"`
	Description_ja string `json:"Description_ja,omitempty"`
	ID int `json:"ID,omitempty"`
}
