// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type Perform struct {
	AnimationIdleTarget string `json:"AnimationIdleTarget,omitempty"`
	AnimationPlay01Target string `json:"AnimationPlay01Target,omitempty"`
	AnimationPlay02Target string `json:"AnimationPlay02Target,omitempty"`
	Instrument_de string `json:"Instrument_de,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Text_fr string `json:"Text_fr,omitempty"`
	AnimationEndTargetID int `json:"AnimationEndTargetID,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	AnimationEnd struct {
		ID int `json:"ID,omitempty"`
		Key string `json:"Key,omitempty"`
		Key_en string `json:"Key_en,omitempty"`
	}
	AnimationEndTarget string `json:"AnimationEndTarget,omitempty"`
	AnimationPlay01 struct {
		Key string `json:"Key,omitempty"`
		Key_en string `json:"Key_en,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	Instrument string `json:"Instrument,omitempty"`
	Instrument_fr string `json:"Instrument_fr,omitempty"`
	Instrument_ja string `json:"Instrument_ja,omitempty"`
	Text_de string `json:"Text_de,omitempty"`
	Text_en string `json:"Text_en,omitempty"`
	AnimationStartTarget string `json:"AnimationStartTarget,omitempty"`
	Instrument_en string `json:"Instrument_en,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	TransientTarget string `json:"TransientTarget,omitempty"`
	TransientTargetID int `json:"TransientTargetID,omitempty"`
	Url string `json:"Url,omitempty"`
	AnimationPlay01TargetID int `json:"AnimationPlay01TargetID,omitempty"`
	AnimationPlay02 struct {
		ID int `json:"ID,omitempty"`
		Key string `json:"Key,omitempty"`
		Key_en string `json:"Key_en,omitempty"`
	}
	AnimationPlay02TargetID int `json:"AnimationPlay02TargetID,omitempty"`
	ID int `json:"ID,omitempty"`
	Transient struct {
		Text_en string `json:"Text_en,omitempty"`
		Text_fr string `json:"Text_fr,omitempty"`
		Text_ja string `json:"Text_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		Text string `json:"Text,omitempty"`
		Text_de string `json:"Text_de,omitempty"`
	}
	AnimationIdle struct {
		Key string `json:"Key,omitempty"`
		Key_en string `json:"Key_en,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	AnimationStart struct {
		ID int `json:"ID,omitempty"`
		Key string `json:"Key,omitempty"`
		Key_en string `json:"Key_en,omitempty"`
	}
	ModelKey string `json:"ModelKey,omitempty"`
	Name string `json:"Name,omitempty"`
	StopAnimation int `json:"StopAnimation,omitempty"`
	Text_ja string `json:"Text_ja,omitempty"`
	AnimationIdleTargetID int `json:"AnimationIdleTargetID,omitempty"`
	AnimationStartTargetID int `json:"AnimationStartTargetID,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	Text string `json:"Text,omitempty"`
}
