// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type AirshipExplorationPart struct {
	Url string `json:"Url,omitempty"`
	Favor int `json:"Favor,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	Range int `json:"Range,omitempty"`
	Retrieval int `json:"Retrieval,omitempty"`
	Surveillance int `json:"Surveillance,omitempty"`
	Components int `json:"Components,omitempty"`
	ID int `json:"ID,omitempty"`
	Rank int `json:"Rank,omitempty"`
	RepairMaterials int `json:"RepairMaterials,omitempty"`
	Speed int `json:"Speed,omitempty"`
}
