// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type MinionRules struct {
	Description_de string `json:"Description_de,omitempty"`
	Description_fr string `json:"Description_fr,omitempty"`
	ID int `json:"ID,omitempty"`
	Rule_de string `json:"Rule_de,omitempty"`
	Rule_fr string `json:"Rule_fr,omitempty"`
	Rule_ja string `json:"Rule_ja,omitempty"`
	Description string `json:"Description,omitempty"`
	Description_en string `json:"Description_en,omitempty"`
	Description_ja string `json:"Description_ja,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	Rule string `json:"Rule,omitempty"`
	Rule_en string `json:"Rule_en,omitempty"`
	Url string `json:"Url,omitempty"`
}
