// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type TopicSelect struct {
	Shop2 int `json:"Shop2,omitempty"`
	Shop3 int `json:"Shop3,omitempty"`
	Shop5 int `json:"Shop5,omitempty"`
	Shop9 int `json:"Shop9,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Shop0 int `json:"Shop0,omitempty"`
	Shop4 int `json:"Shop4,omitempty"`
	Shop6 int `json:"Shop6,omitempty"`
	Url string `json:"Url,omitempty"`
	Name string `json:"Name,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	Shop1 int `json:"Shop1,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Shop8 int `json:"Shop8,omitempty"`
	ID int `json:"ID,omitempty"`
	Shop7 int `json:"Shop7,omitempty"`
}
