// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type SkyIsland2MissionType struct {
	GameContentLinks struct {
		SkyIsland2MissionDetail struct {
			Type []interface{} `json:"Type,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	Type int `json:"Type,omitempty"`
	Url string `json:"Url,omitempty"`
}
