// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type MainCommand struct {
	Description string `json:"Description,omitempty"`
	MainCommandCategory struct {
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
	}
	Name_de string `json:"Name_de,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	Description_de string `json:"Description_de,omitempty"`
	Description_en string `json:"Description_en,omitempty"`
	Description_fr string `json:"Description_fr,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	Description_ja string `json:"Description_ja,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	Icon string `json:"Icon,omitempty"`
	IconID int `json:"IconID,omitempty"`
	MainCommandCategoryTarget string `json:"MainCommandCategoryTarget,omitempty"`
	MainCommandCategoryTargetID int `json:"MainCommandCategoryTargetID,omitempty"`
	ID int `json:"ID,omitempty"`
	Name string `json:"Name,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Url string `json:"Url,omitempty"`
}
