// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type GFATE struct {
	Icon13 string `json:"Icon13,omitempty"`
	Icon14 string `json:"Icon14,omitempty"`
	Icon14ID int `json:"Icon14ID,omitempty"`
	Icon3ID int `json:"Icon3ID,omitempty"`
	Icon6 string `json:"Icon6,omitempty"`
	Icon9ID int `json:"Icon9ID,omitempty"`
	ID int `json:"ID,omitempty"`
	Icon0 string `json:"Icon0,omitempty"`
	Icon1 string `json:"Icon1,omitempty"`
	Icon11 string `json:"Icon11,omitempty"`
	Icon12 string `json:"Icon12,omitempty"`
	Icon4 string `json:"Icon4,omitempty"`
	Icon12ID int `json:"Icon12ID,omitempty"`
	Icon2 string `json:"Icon2,omitempty"`
	Icon6ID int `json:"Icon6ID,omitempty"`
	Icon7 string `json:"Icon7,omitempty"`
	Icon7ID int `json:"Icon7ID,omitempty"`
	Icon15ID int `json:"Icon15ID,omitempty"`
	Icon10 string `json:"Icon10,omitempty"`
	Icon10ID int `json:"Icon10ID,omitempty"`
	Icon5 string `json:"Icon5,omitempty"`
	Icon8ID int `json:"Icon8ID,omitempty"`
	Icon9 string `json:"Icon9,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	Icon0ID int `json:"Icon0ID,omitempty"`
	Icon11ID int `json:"Icon11ID,omitempty"`
	Icon15 string `json:"Icon15,omitempty"`
	Icon1ID int `json:"Icon1ID,omitempty"`
	Icon2ID int `json:"Icon2ID,omitempty"`
	Icon3 string `json:"Icon3,omitempty"`
	Icon5ID int `json:"Icon5ID,omitempty"`
	Icon8 string `json:"Icon8,omitempty"`
	Url string `json:"Url,omitempty"`
	Icon13ID int `json:"Icon13ID,omitempty"`
	Icon4ID int `json:"Icon4ID,omitempty"`
}
