// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type PvPSelectTrait struct {
	Effect string `json:"Effect,omitempty"`
	Effect_en string `json:"Effect_en,omitempty"`
	Effect_fr string `json:"Effect_fr,omitempty"`
	IconID int `json:"IconID,omitempty"`
	Url string `json:"Url,omitempty"`
	Value int `json:"Value,omitempty"`
	Effect_de string `json:"Effect_de,omitempty"`
	Effect_ja string `json:"Effect_ja,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	Icon string `json:"Icon,omitempty"`
}
