// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type JournalGenre struct {
	JournalCategoryTargetID int `json:"JournalCategoryTargetID,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	Url string `json:"Url,omitempty"`
	IconID int `json:"IconID,omitempty"`
	JournalCategory struct {
		Name_en string `json:"Name_en,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		JournalSection struct {
			Name_fr string `json:"Name_fr,omitempty"`
			Name_ja string `json:"Name_ja,omitempty"`
			ID int `json:"ID,omitempty"`
			Name string `json:"Name,omitempty"`
			Name_de string `json:"Name_de,omitempty"`
			Name_en string `json:"Name_en,omitempty"`
		}
		JournalSectionTarget string `json:"JournalSectionTarget,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		JournalSectionTargetID int `json:"JournalSectionTargetID,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
	}
	Icon string `json:"Icon,omitempty"`
	JournalCategoryTarget string `json:"JournalCategoryTarget,omitempty"`
	Name string `json:"Name,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	GameContentLinks struct {
		Quest struct {
			JournalGenre []interface{} `json:"JournalGenre,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
}
