// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type BuddyEquip struct {
	Singular_de string `json:"Singular_de,omitempty"`
	IconHead string `json:"IconHead,omitempty"`
	IconLegsID int `json:"IconLegsID,omitempty"`
	ModelBody int `json:"ModelBody,omitempty"`
	Plural string `json:"Plural,omitempty"`
	Plural_en string `json:"Plural_en,omitempty"`
	Rarity int `json:"Rarity,omitempty"`
	Singular string `json:"Singular,omitempty"`
	Url string `json:"Url,omitempty"`
	IconBody string `json:"IconBody,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	Singular_en string `json:"Singular_en,omitempty"`
	GrandCompany struct {
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		Name string `json:"Name,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
	}
	IconLegs string `json:"IconLegs,omitempty"`
	ModelLegs int `json:"ModelLegs,omitempty"`
	IconHeadID int `json:"IconHeadID,omitempty"`
	Plural_fr string `json:"Plural_fr,omitempty"`
	Singular_ja string `json:"Singular_ja,omitempty"`
	ID int `json:"ID,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	Plural_de string `json:"Plural_de,omitempty"`
	IconBodyID int `json:"IconBodyID,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ModelTop int `json:"ModelTop,omitempty"`
	Singular_fr string `json:"Singular_fr,omitempty"`
	Plural_ja string `json:"Plural_ja,omitempty"`
	StartsWithVowel int `json:"StartsWithVowel,omitempty"`
	GrandCompanyTarget string `json:"GrandCompanyTarget,omitempty"`
	GrandCompanyTargetID int `json:"GrandCompanyTargetID,omitempty"`
	Name string `json:"Name,omitempty"`
}
