// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type GatheringNotebookList struct {
	GatheringItem4 struct {
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
		GatheringItemLevel struct {
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
	}
	GatheringItem88 int `json:"GatheringItem88,omitempty"`
	GatheringItem3Target string `json:"GatheringItem3Target,omitempty"`
	GatheringItem22TargetID int `json:"GatheringItem22TargetID,omitempty"`
	GatheringItem27TargetID int `json:"GatheringItem27TargetID,omitempty"`
	GatheringItem80 int `json:"GatheringItem80,omitempty"`
	GatheringItem87 int `json:"GatheringItem87,omitempty"`
	GatheringItem12 struct {
		GatheringItemLevel struct {
			Stars int `json:"Stars,omitempty"`
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
	}
	GatheringItem20TargetID int `json:"GatheringItem20TargetID,omitempty"`
	GatheringItem68 int `json:"GatheringItem68,omitempty"`
	GatheringItem14 struct {
		GatheringItemLevel struct {
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
	}
	GatheringItem14Target string `json:"GatheringItem14Target,omitempty"`
	GatheringItem25TargetID int `json:"GatheringItem25TargetID,omitempty"`
	GatheringItem7Target string `json:"GatheringItem7Target,omitempty"`
	Url string `json:"Url,omitempty"`
	GatheringItem0TargetID int `json:"GatheringItem0TargetID,omitempty"`
	GatheringItem12TargetID int `json:"GatheringItem12TargetID,omitempty"`
	GatheringItem51 int `json:"GatheringItem51,omitempty"`
	GatheringItem52 int `json:"GatheringItem52,omitempty"`
	GatheringItem86 int `json:"GatheringItem86,omitempty"`
	GatheringItem16 struct {
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
		GatheringItemLevel struct {
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
	}
	GatheringItem24 struct {
		GatheringItemLevel struct {
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
	}
	GatheringItem11TargetID int `json:"GatheringItem11TargetID,omitempty"`
	GatheringItem21Target string `json:"GatheringItem21Target,omitempty"`
	GatheringItem48 int `json:"GatheringItem48,omitempty"`
	GatheringItem7 struct {
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
		GatheringItemLevel struct {
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
		}
	}
	GatheringItem71 int `json:"GatheringItem71,omitempty"`
	GatheringItem89 int `json:"GatheringItem89,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	GatheringItem0Target string `json:"GatheringItem0Target,omitempty"`
	GatheringItem91 int `json:"GatheringItem91,omitempty"`
	GatheringItem22Target string `json:"GatheringItem22Target,omitempty"`
	GatheringItem30TargetID int `json:"GatheringItem30TargetID,omitempty"`
	GatheringItem31 struct {
		GatheringItemLevel struct {
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
	}
	GatheringItem56 int `json:"GatheringItem56,omitempty"`
	GatheringItem60 int `json:"GatheringItem60,omitempty"`
	GatheringItem65 int `json:"GatheringItem65,omitempty"`
	GatheringItem10 struct {
		GatheringItemLevel struct {
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
	}
	GatheringItem17 struct {
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
		GatheringItemLevel struct {
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
		}
	}
	GatheringItem99 int `json:"GatheringItem99,omitempty"`
	GatheringItem83 int `json:"GatheringItem83,omitempty"`
	GatheringItem8TargetID int `json:"GatheringItem8TargetID,omitempty"`
	GatheringItem98 int `json:"GatheringItem98,omitempty"`
	GatheringItem0 struct {
		GatheringItemLevel struct {
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
	}
	GatheringItem63 int `json:"GatheringItem63,omitempty"`
	GatheringItem20Target string `json:"GatheringItem20Target,omitempty"`
	GatheringItem25Target string `json:"GatheringItem25Target,omitempty"`
	GatheringItem27 struct {
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
		GatheringItemLevel struct {
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	GatheringItem30 struct {
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
		GatheringItemLevel struct {
			Stars int `json:"Stars,omitempty"`
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	GatheringItem32 struct {
		GatheringItemLevel struct {
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
	}
	GatheringItem32Target string `json:"GatheringItem32Target,omitempty"`
	GatheringItem15 struct {
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
		GatheringItemLevel struct {
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
	}
	GatheringItem19Target string `json:"GatheringItem19Target,omitempty"`
	GatheringItem9 struct {
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
		GatheringItemLevel struct {
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
	}
	GatheringItem64 int `json:"GatheringItem64,omitempty"`
	GatheringItem6TargetID int `json:"GatheringItem6TargetID,omitempty"`
	GatheringItem45 int `json:"GatheringItem45,omitempty"`
	GatheringItem69 int `json:"GatheringItem69,omitempty"`
	GatheringItem85 int `json:"GatheringItem85,omitempty"`
	GatheringItem2TargetID int `json:"GatheringItem2TargetID,omitempty"`
	GatheringItem37 int `json:"GatheringItem37,omitempty"`
	GatheringItem78 int `json:"GatheringItem78,omitempty"`
	GatheringItem34 int `json:"GatheringItem34,omitempty"`
	GatheringItem58 int `json:"GatheringItem58,omitempty"`
	GatheringItem70 int `json:"GatheringItem70,omitempty"`
	GatheringItem73 int `json:"GatheringItem73,omitempty"`
	GatheringItem30Target string `json:"GatheringItem30Target,omitempty"`
	GatheringItem33 struct {
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
		GatheringItemLevel struct {
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
	}
	GatheringItem76 int `json:"GatheringItem76,omitempty"`
	GatheringItem82 int `json:"GatheringItem82,omitempty"`
	GatheringItem94 int `json:"GatheringItem94,omitempty"`
	GatheringItem21 struct {
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
		GatheringItemLevel struct {
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
	}
	GatheringItem29TargetID int `json:"GatheringItem29TargetID,omitempty"`
	GatheringItem31Target string `json:"GatheringItem31Target,omitempty"`
	GatheringItem3 struct {
		GatheringItemLevel struct {
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
	}
	GatheringItem43 int `json:"GatheringItem43,omitempty"`
	GatheringItem53 int `json:"GatheringItem53,omitempty"`
	GatheringItem81 int `json:"GatheringItem81,omitempty"`
	GatheringItem11 struct {
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
		GatheringItemLevel struct {
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
	}
	GatheringItem26 struct {
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
		GatheringItemLevel struct {
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
		}
	}
	GatheringItem26Target string `json:"GatheringItem26Target,omitempty"`
	GatheringItem27Target string `json:"GatheringItem27Target,omitempty"`
	GatheringItem49 int `json:"GatheringItem49,omitempty"`
	GatheringItem4Target string `json:"GatheringItem4Target,omitempty"`
	GatheringItem15Target string `json:"GatheringItem15Target,omitempty"`
	GatheringItem18 struct {
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
		GatheringItemLevel struct {
			Stars int `json:"Stars,omitempty"`
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
	}
	GatheringItem23TargetID int `json:"GatheringItem23TargetID,omitempty"`
	GatheringItem24Target string `json:"GatheringItem24Target,omitempty"`
	GatheringItem97 int `json:"GatheringItem97,omitempty"`
	GatheringItem17TargetID int `json:"GatheringItem17TargetID,omitempty"`
	GatheringItem19TargetID int `json:"GatheringItem19TargetID,omitempty"`
	GatheringItem46 int `json:"GatheringItem46,omitempty"`
	GatheringItem67 int `json:"GatheringItem67,omitempty"`
	GatheringItem6Target string `json:"GatheringItem6Target,omitempty"`
	GatheringItem79 int `json:"GatheringItem79,omitempty"`
	GatheringItem8Target string `json:"GatheringItem8Target,omitempty"`
	GatheringItem2 struct {
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
		GatheringItemLevel struct {
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
		}
	}
	GatheringItem36 int `json:"GatheringItem36,omitempty"`
	GatheringItem5 struct {
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
		GatheringItemLevel struct {
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
	}
	GatheringItem57 int `json:"GatheringItem57,omitempty"`
	GatheringItem7TargetID int `json:"GatheringItem7TargetID,omitempty"`
	GatheringItem18TargetID int `json:"GatheringItem18TargetID,omitempty"`
	GatheringItem3TargetID int `json:"GatheringItem3TargetID,omitempty"`
	GatheringItem13Target string `json:"GatheringItem13Target,omitempty"`
	GatheringItem39 int `json:"GatheringItem39,omitempty"`
	GatheringItem35 int `json:"GatheringItem35,omitempty"`
	GatheringItem47 int `json:"GatheringItem47,omitempty"`
	GatheringItem62 int `json:"GatheringItem62,omitempty"`
	GatheringItem10Target string `json:"GatheringItem10Target,omitempty"`
	GatheringItem28Target string `json:"GatheringItem28Target,omitempty"`
	GatheringItem22 struct {
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
		GatheringItemLevel struct {
			Stars int `json:"Stars,omitempty"`
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
	}
	GatheringItem23 struct {
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
		GatheringItemLevel struct {
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
	}
	GatheringItem25 struct {
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
		GatheringItemLevel struct {
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
		}
	}
	GatheringItem29Target string `json:"GatheringItem29Target,omitempty"`
	GatheringItem8 struct {
		Item int `json:"Item,omitempty"`
		GatheringItemLevel struct {
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
	}
	GatheringItem13 struct {
		GatheringItemLevel struct {
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
	}
	GatheringItem15TargetID int `json:"GatheringItem15TargetID,omitempty"`
	GatheringItem74 int `json:"GatheringItem74,omitempty"`
	GatheringItem13TargetID int `json:"GatheringItem13TargetID,omitempty"`
	GatheringItem17Target string `json:"GatheringItem17Target,omitempty"`
	GatheringItem55 int `json:"GatheringItem55,omitempty"`
	GatheringItem5Target string `json:"GatheringItem5Target,omitempty"`
	GatheringItem11Target string `json:"GatheringItem11Target,omitempty"`
	GatheringItem14TargetID int `json:"GatheringItem14TargetID,omitempty"`
	GatheringItem24TargetID int `json:"GatheringItem24TargetID,omitempty"`
	GatheringItem31TargetID int `json:"GatheringItem31TargetID,omitempty"`
	GatheringItem42 int `json:"GatheringItem42,omitempty"`
	GatheringItem75 int `json:"GatheringItem75,omitempty"`
	GatheringItem1 struct {
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
		GatheringItemLevel struct {
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
		}
	}
	GatheringItem1TargetID int `json:"GatheringItem1TargetID,omitempty"`
	GatheringItem20 struct {
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
		GatheringItemLevel struct {
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
	}
	GatheringItem28 struct {
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
		GatheringItemLevel struct {
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
	}
	GatheringItem33Target string `json:"GatheringItem33Target,omitempty"`
	GatheringItem33TargetID int `json:"GatheringItem33TargetID,omitempty"`
	GatheringItem38 int `json:"GatheringItem38,omitempty"`
	GatheringItem5TargetID int `json:"GatheringItem5TargetID,omitempty"`
	GatheringItem10TargetID int `json:"GatheringItem10TargetID,omitempty"`
	GatheringItem12Target string `json:"GatheringItem12Target,omitempty"`
	GatheringItem77 int `json:"GatheringItem77,omitempty"`
	GatheringItem92 int `json:"GatheringItem92,omitempty"`
	GatheringItem40 int `json:"GatheringItem40,omitempty"`
	GatheringItem18Target string `json:"GatheringItem18Target,omitempty"`
	GatheringItem29 struct {
		GatheringItemLevel struct {
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
	}
	GatheringItem2Target string `json:"GatheringItem2Target,omitempty"`
	GatheringItem44 int `json:"GatheringItem44,omitempty"`
	GatheringItem4TargetID int `json:"GatheringItem4TargetID,omitempty"`
	GatheringItem59 int `json:"GatheringItem59,omitempty"`
	GatheringItem66 int `json:"GatheringItem66,omitempty"`
	GatheringItem84 int `json:"GatheringItem84,omitempty"`
	GatheringItem16TargetID int `json:"GatheringItem16TargetID,omitempty"`
	GatheringItem26TargetID int `json:"GatheringItem26TargetID,omitempty"`
	GatheringItem90 int `json:"GatheringItem90,omitempty"`
	GatheringItem6 struct {
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
		GatheringItemLevel struct {
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
	}
	ID int `json:"ID,omitempty"`
	GatheringItem1Target string `json:"GatheringItem1Target,omitempty"`
	GatheringItem28TargetID int `json:"GatheringItem28TargetID,omitempty"`
	GatheringItem41 int `json:"GatheringItem41,omitempty"`
	GatheringItem50 int `json:"GatheringItem50,omitempty"`
	GatheringItem54 int `json:"GatheringItem54,omitempty"`
	GatheringItem61 int `json:"GatheringItem61,omitempty"`
	GatheringItem95 int `json:"GatheringItem95,omitempty"`
	GatheringItem23Target string `json:"GatheringItem23Target,omitempty"`
	GatheringItem32TargetID int `json:"GatheringItem32TargetID,omitempty"`
	GatheringItem21TargetID int `json:"GatheringItem21TargetID,omitempty"`
	GatheringItem72 int `json:"GatheringItem72,omitempty"`
	GatheringItem93 int `json:"GatheringItem93,omitempty"`
	GatheringItem96 int `json:"GatheringItem96,omitempty"`
	GatheringItem9Target string `json:"GatheringItem9Target,omitempty"`
	GatheringItem9TargetID int `json:"GatheringItem9TargetID,omitempty"`
	GatheringItem16Target string `json:"GatheringItem16Target,omitempty"`
	GatheringItem19 struct {
		GatheringItemLevel struct {
			GatheringItemLevel int `json:"GatheringItemLevel,omitempty"`
			ID int `json:"ID,omitempty"`
			Stars int `json:"Stars,omitempty"`
		}
		GatheringItemLevelTarget string `json:"GatheringItemLevelTarget,omitempty"`
		GatheringItemLevelTargetID int `json:"GatheringItemLevelTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
		IsHidden int `json:"IsHidden,omitempty"`
		Item int `json:"Item,omitempty"`
	}
}
