// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type AnimaWeapon5SpiritTalkParam struct {
	Epilogue_ja string `json:"Epilogue_ja,omitempty"`
	Prologue string `json:"Prologue,omitempty"`
	Prologue_ja string `json:"Prologue_ja,omitempty"`
	Url string `json:"Url,omitempty"`
	Epilogue string `json:"Epilogue,omitempty"`
	Epilogue_de string `json:"Epilogue_de,omitempty"`
	GameContentLinks struct {
		AnimaWeapon5SpiritTalk struct {
			Dialogue []interface{} `json:"Dialogue,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	Prologue_de string `json:"Prologue_de,omitempty"`
	Prologue_en string `json:"Prologue_en,omitempty"`
	Prologue_fr string `json:"Prologue_fr,omitempty"`
	Epilogue_en string `json:"Epilogue_en,omitempty"`
	Epilogue_fr string `json:"Epilogue_fr,omitempty"`
}
