// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type DisposalShop struct {
	ShopName string `json:"ShopName,omitempty"`
	ShopName_de string `json:"ShopName_de,omitempty"`
	ShopName_en string `json:"ShopName_en,omitempty"`
	ShopName_fr string `json:"ShopName_fr,omitempty"`
	ShopName_ja string `json:"ShopName_ja,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
}
