// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type MasterpieceSupplyMultiplier struct {
	XpMultiplier1 int `json:"XpMultiplier1,omitempty"`
	CurrencyMultiplier0 int `json:"CurrencyMultiplier0,omitempty"`
	CurrencyMultiplier1 int `json:"CurrencyMultiplier1,omitempty"`
	GameContentLinks struct {
		MasterpieceSupplyDuty struct {
			BonusMultiplier4 []interface{} `json:"BonusMultiplier4,omitempty"`
			BonusMultiplier5 []interface{} `json:"BonusMultiplier5,omitempty"`
			BonusMultiplier6 []interface{} `json:"BonusMultiplier6,omitempty"`
			BonusMultiplier7 []interface{} `json:"BonusMultiplier7,omitempty"`
			BonusMultiplier0 []interface{} `json:"BonusMultiplier0,omitempty"`
			BonusMultiplier1 []interface{} `json:"BonusMultiplier1,omitempty"`
			BonusMultiplier2 []interface{} `json:"BonusMultiplier2,omitempty"`
			BonusMultiplier3 []interface{} `json:"BonusMultiplier3,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	Url string `json:"Url,omitempty"`
	XpMultiplier0 int `json:"XpMultiplier0,omitempty"`
}
