// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type PublicContentCutscene struct {
	Cutscene struct {
		ID int `json:"ID,omitempty"`
		Path string `json:"Path,omitempty"`
		Path_en string `json:"Path_en,omitempty"`
	}
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	Url string `json:"Url,omitempty"`
	Cutscene2 struct {
		Path string `json:"Path,omitempty"`
		Path_en string `json:"Path_en,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	Cutscene2Target string `json:"Cutscene2Target,omitempty"`
	Cutscene2TargetID int `json:"Cutscene2TargetID,omitempty"`
	CutsceneTarget string `json:"CutsceneTarget,omitempty"`
	CutsceneTargetID int `json:"CutsceneTargetID,omitempty"`
	ID int `json:"ID,omitempty"`
}
