// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ContentGauge struct {
	TextString_en string `json:"TextString_en,omitempty"`
	TextString_fr string `json:"TextString_fr,omitempty"`
	TextString_ja string `json:"TextString_ja,omitempty"`
	ColorTargetID int `json:"ColorTargetID,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	TextString string `json:"TextString,omitempty"`
	Color struct {
		AndroidColor1 int `json:"AndroidColor1,omitempty"`
		AndroidColor2 int `json:"AndroidColor2,omitempty"`
		AndroidColor3 int `json:"AndroidColor3,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	Name_ja string `json:"Name_ja,omitempty"`
	Url string `json:"Url,omitempty"`
	ID int `json:"ID,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	TextString_de string `json:"TextString_de,omitempty"`
	ColorTarget string `json:"ColorTarget,omitempty"`
	Name string `json:"Name,omitempty"`
}
