// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ActionTimelineReplace struct {
	ID int `json:"ID,omitempty"`
	NewTargetID int `json:"NewTargetID,omitempty"`
	Url string `json:"Url,omitempty"`
	Old struct {
		ID int `json:"ID,omitempty"`
		Key string `json:"Key,omitempty"`
		Key_en string `json:"Key_en,omitempty"`
	}
	OldTarget string `json:"OldTarget,omitempty"`
	OldTargetID int `json:"OldTargetID,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	New struct {
		Key string `json:"Key,omitempty"`
		Key_en string `json:"Key_en,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	NewTarget string `json:"NewTarget,omitempty"`
}
