// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type FCReputation struct {
	Url string `json:"Url,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	RequiredPoints int `json:"RequiredPoints,omitempty"`
	Name string `json:"Name,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	PointsToNext int `json:"PointsToNext,omitempty"`
}
