// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ContentsNoteCategory struct {
	GameContentLinks struct {
		ContentsNote struct {
			ContentType []interface{} `json:"ContentType,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	Type string `json:"Type,omitempty"`
	Url string `json:"Url,omitempty"`
}
