// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ContentTalkParam struct {
	GameContentLinks struct {
		ContentTalk struct {
			ContentTalkParam []interface{} `json:"ContentTalkParam,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	Param int `json:"Param,omitempty"`
	TestAction int `json:"TestAction,omitempty"`
	Url string `json:"Url,omitempty"`
}
