// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type WeeklyBingoRewardData struct {
	RewardType1 int `json:"RewardType1,omitempty"`
	ID int `json:"ID,omitempty"`
	RewardItem1 int `json:"RewardItem1,omitempty"`
	RewardOption1 int `json:"RewardOption1,omitempty"`
	RewardQuantity2 int `json:"RewardQuantity2,omitempty"`
	Url string `json:"Url,omitempty"`
	RewardHQ0 int `json:"RewardHQ0,omitempty"`
	RewardHQ2 int `json:"RewardHQ2,omitempty"`
	RewardQuantity0 int `json:"RewardQuantity0,omitempty"`
	RewardQuantity1 int `json:"RewardQuantity1,omitempty"`
	RewardType0 int `json:"RewardType0,omitempty"`
	GameContentLinks struct {
		WeeklyBingoRewardData struct {
			RewardOption1 []interface{} `json:"RewardOption1,omitempty"`
		}
	}
	RewardItem0 int `json:"RewardItem0,omitempty"`
	RewardOption0 int `json:"RewardOption0,omitempty"`
	RewardHQ1 int `json:"RewardHQ1,omitempty"`
	RewardItem2 int `json:"RewardItem2,omitempty"`
}
