// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type AirshipExplorationPoint struct {
	Name string `json:"Name,omitempty"`
	NameShort_ja string `json:"NameShort_ja,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	RequiredLevel int `json:"RequiredLevel,omitempty"`
	Url string `json:"Url,omitempty"`
	DurationMin int `json:"DurationMin,omitempty"`
	NameShort string `json:"NameShort,omitempty"`
	NameShort_de string `json:"NameShort_de,omitempty"`
	NameShort_fr string `json:"NameShort_fr,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	ExpReward int `json:"ExpReward,omitempty"`
	ID int `json:"ID,omitempty"`
	NameShort_en string `json:"NameShort_en,omitempty"`
	RequiredFuel int `json:"RequiredFuel,omitempty"`
	RequiredSurveillance int `json:"RequiredSurveillance,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
}
