// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ActionTimeline struct {
	GameContentLinks struct {
		Action struct {
			ActionTimelineHit []interface{} `json:"ActionTimelineHit,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	Key string `json:"Key,omitempty"`
	Key_en string `json:"Key_en,omitempty"`
	Url string `json:"Url,omitempty"`
}
