// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ChocoboRace struct {
	Url string `json:"Url,omitempty"`
	ChocoboRaceRankTargetID int `json:"ChocoboRaceRankTargetID,omitempty"`
	ChocoboRaceTerritoryTarget string `json:"ChocoboRaceTerritoryTarget,omitempty"`
	ChocoboRaceTerritoryTargetID int `json:"ChocoboRaceTerritoryTargetID,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	ChocoboRaceRank struct {
		Icon string `json:"Icon,omitempty"`
		IconID int `json:"IconID,omitempty"`
		Fee int `json:"Fee,omitempty"`
		Name struct {
			Text_en string `json:"Text_en,omitempty"`
			Text_fr string `json:"Text_fr,omitempty"`
			Text_ja string `json:"Text_ja,omitempty"`
			ID int `json:"ID,omitempty"`
			Text string `json:"Text,omitempty"`
			Text_de string `json:"Text_de,omitempty"`
		}
		NameTarget string `json:"NameTarget,omitempty"`
		NameTargetID int `json:"NameTargetID,omitempty"`
		RatingMax int `json:"RatingMax,omitempty"`
		RatingMin int `json:"RatingMin,omitempty"`
		ID int `json:"ID,omitempty"`
	}
	ChocoboRaceRankTarget string `json:"ChocoboRaceRankTarget,omitempty"`
	ChocoboRaceTerritory struct {
		Icon string `json:"Icon,omitempty"`
		IconID int `json:"IconID,omitempty"`
		Name struct {
			Text_en string `json:"Text_en,omitempty"`
			Text_fr string `json:"Text_fr,omitempty"`
			Text_ja string `json:"Text_ja,omitempty"`
			ID int `json:"ID,omitempty"`
			Text string `json:"Text,omitempty"`
			Text_de string `json:"Text_de,omitempty"`
		}
		NameTarget string `json:"NameTarget,omitempty"`
		NameTargetID int `json:"NameTargetID,omitempty"`
		ID int `json:"ID,omitempty"`
	}
}
