// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type StatusHitEffect struct {
	LocationTargetID int `json:"LocationTargetID,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks struct {
		Status struct {
			HitEffect []interface{} `json:"HitEffect,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	Location struct {
		ID int `json:"ID,omitempty"`
		Location string `json:"Location,omitempty"`
		Location_en string `json:"Location_en,omitempty"`
	}
	LocationTarget string `json:"LocationTarget,omitempty"`
}
