// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type TextCommand struct {
	Alias_ja string `json:"Alias_ja,omitempty"`
	Command string `json:"Command,omitempty"`
	ShortAlias_de string `json:"ShortAlias_de,omitempty"`
	ShortAlias_fr string `json:"ShortAlias_fr,omitempty"`
	ShortCommand string `json:"ShortCommand,omitempty"`
	Url string `json:"Url,omitempty"`
	Alias_en string `json:"Alias_en,omitempty"`
	Alias_fr string `json:"Alias_fr,omitempty"`
	Command_en string `json:"Command_en,omitempty"`
	Description_en string `json:"Description_en,omitempty"`
	ShortAlias string `json:"ShortAlias,omitempty"`
	Alias string `json:"Alias,omitempty"`
	Alias_de string `json:"Alias_de,omitempty"`
	Description string `json:"Description,omitempty"`
	ShortAlias_ja string `json:"ShortAlias_ja,omitempty"`
	ShortCommand_en string `json:"ShortCommand_en,omitempty"`
	Description_fr string `json:"Description_fr,omitempty"`
	ID int `json:"ID,omitempty"`
	ShortCommand_fr string `json:"ShortCommand_fr,omitempty"`
	Command_de string `json:"Command_de,omitempty"`
	Description_de string `json:"Description_de,omitempty"`
	GameContentLinks struct {
		Emote struct {
			TextCommand []interface{} `json:"TextCommand,omitempty"`
		}
	}
	ShortAlias_en string `json:"ShortAlias_en,omitempty"`
	ShortCommand_ja string `json:"ShortCommand_ja,omitempty"`
	Command_ja string `json:"Command_ja,omitempty"`
	Description_ja string `json:"Description_ja,omitempty"`
	ShortCommand_de string `json:"ShortCommand_de,omitempty"`
	Command_fr string `json:"Command_fr,omitempty"`
}
