// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type HousingEmploymentNpcRace struct {
	Race_en string `json:"Race_en,omitempty"`
	Race_fr string `json:"Race_fr,omitempty"`
	Race_ja string `json:"Race_ja,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks struct {
		HousingEmploymentNpcList struct {
			Race []interface{} `json:"Race,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	Race string `json:"Race,omitempty"`
	Race_de string `json:"Race_de,omitempty"`
}
