// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type MoveVfx struct {
	VFXNormalTarget string `json:"VFXNormalTarget,omitempty"`
	VFXWalkingTarget string `json:"VFXWalkingTarget,omitempty"`
	VFXWalkingTargetID int `json:"VFXWalkingTargetID,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	Url string `json:"Url,omitempty"`
	VFXNormal struct {
		Location_en string `json:"Location_en,omitempty"`
		ID int `json:"ID,omitempty"`
		Location string `json:"Location,omitempty"`
	}
	VFXNormalTargetID int `json:"VFXNormalTargetID,omitempty"`
	VFXWalking struct {
		ID int `json:"ID,omitempty"`
		Location string `json:"Location,omitempty"`
		Location_en string `json:"Location_en,omitempty"`
	}
	ID int `json:"ID,omitempty"`
}
