// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type Omen struct {
	FileName string `json:"FileName,omitempty"`
	FileName_en string `json:"FileName_en,omitempty"`
	GameContentLinks struct {
		Action struct {
			Omen []interface{} `json:"Omen,omitempty"`
		}
	}
	ID int `json:"ID,omitempty"`
	Url string `json:"Url,omitempty"`
}
