// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type Behavior struct {
	Balloon struct {
		Dialogue_ja string `json:"Dialogue_ja,omitempty"`
		ID int `json:"ID,omitempty"`
		Dialogue string `json:"Dialogue,omitempty"`
		Dialogue_de string `json:"Dialogue_de,omitempty"`
		Dialogue_en string `json:"Dialogue_en,omitempty"`
		Dialogue_fr string `json:"Dialogue_fr,omitempty"`
	}
	BalloonTarget string `json:"BalloonTarget,omitempty"`
	BalloonTargetID int `json:"BalloonTargetID,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	Url string `json:"Url,omitempty"`
}
