// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type TraitRecast struct {
	Trait int `json:"Trait,omitempty"`
	Url string `json:"Url,omitempty"`
	Action int `json:"Action,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	TimeDs int `json:"TimeDs,omitempty"`
}
