// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type RacingChocoboNameInfo struct {
	RacingChocoboNameCategory struct {
		Name_de string `json:"Name_de,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		SortKey int `json:"SortKey,omitempty"`
		ID int `json:"ID,omitempty"`
		Name string `json:"Name,omitempty"`
	}
	RacingChocoboNameCategoryTarget string `json:"RacingChocoboNameCategoryTarget,omitempty"`
	RacingChocoboNameCategoryTargetID int `json:"RacingChocoboNameCategoryTargetID,omitempty"`
	Url string `json:"Url,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
}
