// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type ContentFinderConditionTransient struct {
	ID int `json:"ID,omitempty"`
	Url string `json:"Url,omitempty"`
	Description string `json:"Description,omitempty"`
	Description_de string `json:"Description_de,omitempty"`
	Description_en string `json:"Description_en,omitempty"`
	Description_fr string `json:"Description_fr,omitempty"`
	Description_ja string `json:"Description_ja,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
}
