// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type PreHandler struct {
	ActionTimeline struct {
		ID int `json:"ID,omitempty"`
		Key string `json:"Key,omitempty"`
		Key_en string `json:"Key_en,omitempty"`
	}
	ActionTimelineTargetID int `json:"ActionTimelineTargetID,omitempty"`
	GilShopTargetID int `json:"GilShopTargetID,omitempty"`
	Url string `json:"Url,omitempty"`
	ActionTimelineTarget string `json:"ActionTimelineTarget,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	GilShop struct {
		ID int `json:"ID,omitempty"`
		IconID int `json:"IconID,omitempty"`
		Name_en string `json:"Name_en,omitempty"`
		Name_fr string `json:"Name_fr,omitempty"`
		QuestRequired2 int `json:"QuestRequired2,omitempty"`
		FailTalk int `json:"FailTalk,omitempty"`
		Name_ja string `json:"Name_ja,omitempty"`
		Name string `json:"Name,omitempty"`
		QuestRequired3 int `json:"QuestRequired3,omitempty"`
		AcceptTalk int `json:"AcceptTalk,omitempty"`
		Icon string `json:"Icon,omitempty"`
		Name_de string `json:"Name_de,omitempty"`
		QuestRequired0 int `json:"QuestRequired0,omitempty"`
		QuestRequired1 int `json:"QuestRequired1,omitempty"`
	}
	GilShopTarget string `json:"GilShopTarget,omitempty"`
	ID int `json:"ID,omitempty"`
}
