// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type EObj struct {
	Data int `json:"Data,omitempty"`
	GameContentLinks []interface{} `json:"GameContentLinks,omitempty"`
	ID int `json:"ID,omitempty"`
	Url string `json:"Url,omitempty"`
}
