// Code generated by generate_structs - DO NOT EDIT.

package xivapi

type TripleTriadCard struct {
	Description_en string `json:"Description_en,omitempty"`
	GameContentLinks struct {
		TripleTriad struct {
			TripleTriadCardVariable1 []interface{} `json:"TripleTriadCardVariable1,omitempty"`
			TripleTriadCardVariable2 []interface{} `json:"TripleTriadCardVariable2,omitempty"`
			TripleTriadCardVariable3 []interface{} `json:"TripleTriadCardVariable3,omitempty"`
			TripleTriadCardVariable4 []interface{} `json:"TripleTriadCardVariable4,omitempty"`
			TripleTriadCardFixed0 []interface{} `json:"TripleTriadCardFixed0,omitempty"`
			TripleTriadCardFixed2 []interface{} `json:"TripleTriadCardFixed2,omitempty"`
		}
	}
	Name string `json:"Name,omitempty"`
	Name_fr string `json:"Name_fr,omitempty"`
	Description_de string `json:"Description_de,omitempty"`
	Name_en string `json:"Name_en,omitempty"`
	Name_ja string `json:"Name_ja,omitempty"`
	Description_fr string `json:"Description_fr,omitempty"`
	ID int `json:"ID,omitempty"`
	Url string `json:"Url,omitempty"`
	Description string `json:"Description,omitempty"`
	Description_ja string `json:"Description_ja,omitempty"`
	Name_de string `json:"Name_de,omitempty"`
	StartsWithVowel int `json:"StartsWithVowel,omitempty"`
}
